- src/wasm-gen.c
- src/wasm-parse.c
- src/wasm-parse.h
This allows getting the export name without having to get the module and
peek at the back of the export vector.
> Make after_export parser callback pass a WasmExport* instead of just int

- src/wasm-gen.c
- src/wasm-keywords.gperf
- src/wasm-keywords.h
- src/wasm-parse.c
- src/wasm-parse.h
- test/assert/assert-after-module.txt
- test/assert/assertreturn.txt
- test/assert/bad-assert-before-module.txt
- test/assert/bad-asserteq-too-few.txt
- test/assert/bad-asserteq-too-many.txt
- test/assert/bad-asserteq-unknown-function.txt
- test/assert/bad-assertreturn-too-few.txt
- test/assert/bad-assertreturn-too-many.txt
- test/assert/bad-assertreturn-unknown-function.txt
This matches recent changes in the spec repo. I left assert_eq as an
alias for assert_return to accomodate existing tests for now (although
the semantics for FP compares are subtly different), but renamed the
enums and event names to assert_return. I also left the d8
and spec tests alone for now.
> Rename assert_eq to assert_return

- src/wasm-parse.c
The callback isn't very useful with just the name
> Pass exported function to after_export callback

- known_gcc_test_failures.txt
The following wasmate fix:
https://github.com/WebAssembly/experimental/pull/82
Makes (import ...) use 'result' instead of 'return', fixing a few failures (some of them were hiding further failures).
> Update torture failures

- src/wasm-binary-writer.c
- src/wasm-check.c
- src/wasm-common.h
- src/wasm-parser.c
- src/wasm-parser.y
- src/wasm.c
- src/wasm.h
Rename 'export' field of WasmModuleField because 'export' is a reserved
word in C++ (and regenerate the parser).
Wrap functions declared in wasm.h in extern "C"
> Support use of parser and AST in C++ programs

- src/wasm-check.c
- test/typecheck/label-redefinition.txt
The ml-proto allows duplicate block labels. This is noted as convenient in the discussions https://github.com/WebAssembly/spec/issues/210 as is supports 'locality and compositionality'. Perhaps something to consider for sexp-wasm.
> Accept duplicate block labels.

- test/spec/address.txt
Thank you for merging the memory-in-pages change. Retesting shows one failure in the expected output when using the pending spec tests.
> Fix a test expected output after the memory-in-pages change.

- .gitignore
- src/wasm.c
Implementation of vsnprintf was under the wrong check on Windows.
> Windows: vsnprintf

- CMakeLists.txt
- Makefile
- scripts/travis-build.sh
This is used by the Wasm waterfall.
> Add options to build without GTest submodule

- src/prebuilt/wasm-ast-lexer-gen.c
- src/prebuilt/wasm-ast-parser-gen.c
- src/sexpr-wasm.c
- src/wasm-ast-checker.c
- src/wasm-ast-checker.h
- src/wasm-ast-lexer.c
- src/wasm-ast-parser-lexer-shared.h
- src/wasm-ast-parser.y
- src/wasm-ast.c
- src/wasm-ast.h
- test/parse/assert/assertinvalid-binary-module.txt
- test/parse/module/bad-binary-module-magic.txt
If we decode the binary module when parsing, then any errors will be
displayed too early. Instead, we store the binary data, ready to be
decoded.
This is only done for assert_invalid, where we assume that the module
will not actually be used. Otherwise, it is more convenient to always
have a WasmModule, so we decode directly while parsing the AST.
> defer decoding binary modules in assert_invalid

- CMakeLists.txt
- src/wasm-binary-writer.c
- src/wasm-config.h.in
- src/wasm-interp-sq.c
- src/wasm-interpreter.c
Fix implementation of ctz64, clz64 & popcnt64 for Win32
Fixed a few warnings in msvc.
The current ctz implementation for 32 & 64 bits were incorrect as `_BitScanForward` has the same result as `__builtin_ctz`. I don't know why we used to do `return sizeof(unsigned long) * 8 - (index + 1);`
I haven't fully tested the with the product yet. I mostly focused on making sure the ctz/clz/popcnt implementations were correct.
> Fix build for Win32

- src/sexpr-wasm.c
- src/wasm-ast-checker.c
- src/wasm-ast-checker.h
- src/wasm-binary-writer-spec.c
- test/dump/nocheck.txt
- test/help/sexpr-wasm.txt
- test/parse/assert/nocheck-assertinvalid.txt
- test/typecheck/nocheck.txt
* `--no-check` disables all checking except for validating names (without
which you couldn't generate a binary file).
* `--no-check-assert-invalid` skips running the `assert_invalid` checks
in spec test files.
> add flags to turn off AST checking in sexpr-wasm

- src/prebuilt/wasm-ast-parser-gen.c
- src/wasm-ast-parser.y
- src/wasm-binary-reader-interpreter.c
- src/wasm-interp.c
- src/wasm-stack-allocator.c
- test/binary/bad-data-size.txt
- test/binary/bad-function-body-size.txt
- test/run-gen-wasm-interp.py
- test/run-tests.py
There were a couple of integer underflows and overflows that could result in out-of-bounds memory accesses, and some uninitialized memory that could result in bad calls to the free pointer of the memory allocator.
> fix bugs found by afl and asan

- test/find_exe.py
- test/run-js.py
- test/spec.js
- test/utils.py
- test/wasm.js
Added support for ch.exe (run-js.py and polyfills in js scripts)
Todo, currently no script to build/download ch.exe it has to be built separately.
> Teach test scripts about ch.exe

- src/wasm-ast-checker.c
- src/wasm-ast-writer.c
- src/wasm-binary-reader-ast.c
- src/wasm-binary-reader-interpreter.c
- src/wasm-binary-writer.c
- src/wasm-common.c
- src/wasm-common.h
- test/interp/spec/br.txt
- test/interp/spec/br_if.txt
- test/interp/spec/br_table.txt
- test/interp/spec/func.txt
- test/interp/spec/get_local.txt
- test/interp/spec/of_string-overflow-hex-u32.fail.txt
- test/interp/spec/of_string-overflow-hex-u64.fail.txt
- test/interp/spec/of_string-overflow-s32.fail.txt
- test/interp/spec/of_string-overflow-s64.fail.txt
- test/interp/spec/of_string-overflow-u32.fail.txt
- test/interp/spec/of_string-overflow-u64.fail.txt
- test/interp/spec/switch.txt
- test/parse/expr/bad-br-bad-depth.txt
- test/parse/expr/bad-br-defined-later.txt
- test/parse/expr/bad-br-no-label.txt
- test/parse/expr/bad-br-undefined.txt
- test/parse/expr/bad-brtable-bad-depth.txt
`(func (br 0))` is valid, because the function introduces an implicit
block scope. This change also updates the testsuite (which has tests for
this behavior).
> functions have an implicit block scope

- src/wasm-apply-names.c
- src/wasm-ast-checker.c
- src/wasm-ast-parser-lexer-shared.c
- src/wasm-ast-parser.y
- src/wasm-ast-writer.c
- src/wasm-ast.h
- src/wasm-binary-reader-ast.c
- src/wasm-binary-writer-spec.c
- src/wasm-binary-writer.c
- test/parse/func/bad-sig-result-type-mismatch.txt
- test/parse/func/bad-sig-result-type-not-void.txt
- test/parse/func/bad-sig-result-type-void.txt
Prior to this change, the AST parser would always set `sig`, even if the
function had no explicit signature (i.e. it used a function type
variable instead).
This is OK, but it makes the flag confusing.
`WASM_FUNC_DECLARATION_FLAG_HAS_SIGNATURE` will be clear and
`wasm_decl_has_signature` will return false, but `sig` will be valid.
This change makes it so `sig` is only set when there is an explicit
signature. The correct way to get the function signature is to call
`wasm_decl_get_signature`, which will check whether there is a func
type, and if not, will check for an explicit function signature.
> WasmFuncDeclaration does not always set `sig`

- src/wasm-binary-reader.c
- src/wasm-binary-reader.h
- src/wasm-wast.c
The `--verbose` flag has been there for a while, but wasn't hooked up to
anything. Now it displays info while reading from the binary file, which
could be useful for debugging.
> use the wasm-wast verbose flag

- test/gen-spec-js.py
The error message wanted to print some file name and line number, but these values are not passed to invoke(). Additionally I propose to increase the passed and failed counters in invoke.
> Fix error message in the generated invoke function

- src/wasm-binary-reader.c
- test/binary/bad-magic.txt
- test/binary/bad-version.txt
- test/interp/spec/binary.txt
- test/parse/assert/assertinvalid-binary-module.txt
- test/parse/module/bad-binary-module-magic.txt
As a newcomer it was not obvious what version wasm-interp
was expecting and what I had provided.
> Improve error message on bad file version

- README.md
- test/run-tests.py
Introduces the name change from "sexpr-wasm-prototype" to WABT in
README.md but does not yet change all the URL references or code
references.
> Introduction to WABT

- src/wasm-ast-checker.c
- test/parse/module/bad-memory-segment-address-negative.txt
- test/parse/module/bad-memory-segment-address-oob.txt
- test/parse/module/bad-memory-segment-end-oob.txt
A segment has to fit in the initial size, not the max size. Also, when
building on a 32-bit arch, the offset must be cast to a 64-bit int so
the overflow check works properly.
> fix a bug when checking whether a segment is valid

- s2wasm_known_gcc_test_failures.txt
These are now passing on the waterfall.
> Remove known failures related to `call_indirect with no table`

- src/wasm-binary-reader-interpreter.c
- src/wasm-interp.c
- src/wasm-interpreter.c
- src/wasm-interpreter.h
- src/wasm-vector.c
- test/interp/callimport-zero-args.txt
- test/interp/import.txt
- test/run-tests.py
* elem segment entries should be func_index not sig_index
* change the call_stack and value_stack tops to pointers instead of
integers; this is more convenient for the interpreter, and means we
don't have to convert back and forth between the two when calling to
helper functions (e.g. `call_import`)
* pass dummy results `WasmInterpreterTypedValueVector` to
`run_export_wrapper`, it's required now
* rename all uses of `vs_` -> `value_stack_`, `cs_` -> `call_stack_`
* destroy the func_imports array when destroying the
`WasmInterpreterModule`.
> fix interp tests

- src/wasm-ast-writer.c
- src/wasm-binary-reader-ast.c
- test/roundtrip/func-index.txt
- test/roundtrip/generate-global-names.txt
- test/roundtrip/generate-import-names.txt
- test/roundtrip/generate-local-names.txt
- test/roundtrip/generate-some-names.txt
- test/roundtrip/global-index.txt
- test/roundtrip/label.txt
- test/roundtrip/memory-index.txt
- test/roundtrip/table-index.txt
Also:
* change block comment to "label" instead of "exit"
* remove text parameter to write_end_block, it's always "end"
* write decimal float values for float constants (it's easier to read
than hex floats)
* fix assertion in begin_global_init_expr, it wasn't taking into account
imported globals
* add some new tests that show the correct indexing behavior when
importing funcs, tables, memories and globals
> fix displayed index when writing out wast files

- src/wasm-ast-checker.c
- src/wasm-ast-checker.h
- src/wasm-common.c
- src/wasm-common.h
- src/wast2wasm.c
- test/help/sexpr-wasm.txt
- test/parse/assert/assertmalformed.txt
- test/parse/assert/bad-assertmalformed-succeeds.txt
- test/parse/assert/nocheck-assertmalformed.txt
Checking for malformed modules is almost the same as checking for
invalid modules, the difference being that assert_malformed only tries
to decode the binary format, but doesn't do any other validation.
* Renamed check_assert_invalid -> check_assert_invalid_and_malformed
* Add wasm_default_assert_malformed_source_error_callback, which is the
same as the assert_invalid one, but prints out "assert_malformed"
instead
* Add some basic tests for assert_malformed
> implement assert_malformed

- src/wasm-ast-checker.c
- test/parse/module/import-global-getglobal.txt
Because the index space of globals merges imported and defined locals,
the checker's Context::current_global_index must be incremented for when
checking both.
Fixes #143.
> fix bug defining a global by an imported global

- src/wast2wasm.c
- test/dump/basic_dump_only.txt
Initialize the s_log_stream in all cases since its
used with -v and -d both.
Add a test for -d on its own.
> Fix crash bug when -d specified without -v

- src/wasm-binary-reader-ast.c
- src/wasm-binary-reader-interpreter.c
- src/wasm-binary-reader-opcnt.c
- src/wasm-binary-reader-opcnt.h
- src/wasm-binary-reader.c
- src/wasm-binary-reader.h
- src/wasmopcodecnt.c
- test/run-interp.py
This includes the user_data pointer that was previously
passed but also includes information about the current
reader context such as the offset with in the binary.
> Add WasmBinaryReaderContext type which is passed to reader callback

- src/wasm-binary-reader-objdump.c
Mingw-w64 gcc and MSVC don't have `%zx` or `%zd`.
> Replace zx with PRIzx

- CMakeLists.txt
- src/tools/wasm-interp.c
- src/wasm-ast.c
- src/wasm-ast.h
- src/wasm-binary-reader-interpreter.c
- src/wasm-binary-reader-interpreter.h
- src/wasm-binary-reader.c
- src/wasm-binding-hash.c
- src/wasm-binding-hash.h
- src/wasm-common.c
- src/wasm-common.h
- src/wasm-interpreter.c
- src/wasm-interpreter.h
- src/wasm-writer.c
- src/wasm-writer.h
- test/binary/bad-data-size.txt
- test/interp/callimport-zero-args.txt
- test/interp/import.txt
* Create WasmInterpreterEnvironment to hold all modules, functions,
globals, tables and memories
* There are now three index spaces: "module", "environment" and
"defined".
- The "module" index space matches up w/ the normal WebAssembly index
space, which is distinct for functions, globals, tables, etc.
- The "environment" index space is a combined index space for all loaded
modules.
- The "defined" index space only includes defined objects, not
imported objects. This is used, for example, when iterating over the
code section; the function bodies are only specified for defined
functions.
* A thread is implicitly associated with a module and environment, so
simplify many function signatures to remove those additional arguments
* Any importable kind can be imported from a host module. …
> Refactor interpreter for linking support

- src/wasm-binary-reader.c
- src/wasm-binary-writer.c
- test/dump/callindirect.txt
- test/dump/current-memory.txt
- test/dump/grow-memory.txt
- test/dump/no-canonicalize.txt
`call_indirect`, `grow_memory` and `current_memory` all take an additional
immediate which must be zero. After the MVP, this will be used to allow
specifying a table or memory index.
> Add reserved immediate to three operators

- CMakeLists.txt
- src/wasm-config.h.in
Do not treat warning as errors on Windows. Fix WABT_UNREACHABLE to use __assume(0) on Windows
> Win32 build

- src/wasm-binary-reader.c
- src/wasm-common.h
Fix the bug in logging_begin_global that was exposed by the
using an explictly type here.
> Convert WasmType into an enum

- src/prebuilt/wasm-ast-parser-gen.c
- src/tools/wasm-interp.c
- src/wasm-ast-checker.c
- src/wasm-ast-parser.y
- src/wasm-interpreter.h
- test/parse/assert/bad-assert-before-module.txt
- test/parse/assert/bad-invoke-no-module.txt
- test/spec/exports.txt
* Implement the "get" action, for reading exported globals
* Fix invoke/get checking when given action has a named module
* Fix module name binding when parsing wast
> Fix the export spec test

- src/common.c
- src/common.h
- src/tools/wast2wasm.c
These changes are useful for handling errors via the default binary
error handler in wasm-interp.
> Simplify the default error handler

- src/ast-parser.y
- src/binary-reader-interpreter.c
- src/binary-writer-spec.c
- src/binding-hash.c
- src/binding-hash.h
- src/common.c
- src/common.h
- src/interpreter.c
- src/interpreter.h
- src/prebuilt/ast-parser-gen.c
- src/tools/wasm-interp.c
- test/spec/imports.txt
- test/spec/memory.txt
* Properly handle registering an unnamed module (most recently read) in
AST parser
* register command has optional name in spec JSON format
* Implement spectest_import_{table,memory,global}
* Implement on_register_command in wasm-interp (wires up module binding)
* Implement assert_unlinkable
* Set module's table_index and memory_index when importing table/memory
* Translate {get,set}_global index from module -> environment index
space
* Don't close the environment's istream writer if the module read fails;
this will destroy the output buffer. Just leave it as is, with extra
unused data in the environment
* Add registered_module_bindings hash; this has the registered name of
the module (not to be confused with the module name, which is internal
only)
* Add {GET,SET}_GLOBAL opcodes to …
> Fix spec imports test

- src/binary-reader-interpreter.c
- src/binary-writer-spec.c
- src/interpreter.c
- src/interpreter.h
- src/tools/wasm-interp.c
- test/spec/linking.txt
* The func_fixups table is specified in the "defined" index-space, not
module
* Always fill function tables with the unitialized value when created
* The global_index_mapping table should include imported globals
* Use the "defined" global index space when initializing module globals
* Write table_index to istream for call_indirect
* Write memory_index to istream for all memory ops
* WasmInterpreterThread should not be tied to a particular module;
originally this was to match it to a given module's memory or table,
but now those values are in the instruction stream
* Use just one WasmInterpreterThread now in wasm-interp
* Lazily allocate thread's host_args vector, rather than trying to
determine the maximum size from all signatures
> Fix spec/linking test

- src/common.c
- test/spec/binary.txt
Also, don't fail in wasm_read_file when reading a file of size 0.
> Fix spec/binary test

- src/binary-reader.c
- test/dump/debug-import-names.txt
- test/roundtrip/debug-import-names.txt
- test/roundtrip/debug-names-after-data.txt
This worked before, but only if there was a defined function as well.
I believe this should fix #214 and #215.
> Allow named imports in the names section

- src/binary-reader-objdump.c
- src/binary-reader.c
- src/binary-reader.h
- src/binary-writer.c
- src/binary.h
- test/binary/user-section.txt
- test/dump/debug-import-names.txt
- test/gen-wasm.py
- test/parse/module/bad-global-invalid-expr.txt
- test/run-gen-wasm.py
Handle user sections interspersed with other section
types and add tests from these.
Switch from calling these sections "Unknown" to
"User".
Fixes #214
> Parse arbitrary user sections

- src/binary-reader-objdump.c
- test/dump/debug-names.txt
- test/run-wasmdump.py
Also add `--dump-verbose` flag to `run-wasmdump.py` in order to
be able test the output of `wasmdump -v`
> wasmdump: Dump contents of `name` section

- src/binary-writer-spec.c
- src/binary-writer.c
- src/binary-writer.h
- src/tools/wasm-interp.c
I was able to convert all assert_invalid tests in the spec repository using this change
> Adjust asserts to allow writing invalid modules

- src/binary-reader-ast.c
- src/binary-reader-objdump.c
- src/binary-reader.c
- src/binary-reader.h
- src/binary-writer.c
- src/binary-writer.h
- test/dump/basic.txt
- test/dump/call.txt
- test/dump/callimport.txt
- test/dump/callindirect.txt
- test/dump/current-memory.txt
- test/dump/debug-import-names.txt
- test/dump/grow-memory.txt
- test/dump/memory-1-byte.txt
- test/dump/memory-data-size.txt
- test/dump/memory-hex.txt
- test/dump/memory.txt
- test/dump/no-canonicalize.txt
- test/dump/table.txt
This is mostly a refactor to make some of the internal
binary reading/writing utilities public and available
to the wasm linker prototype that I'm working on.
> Make some binary reading/writing utilities public

- src/validator.c
- test/parse/module/bad-table-invalid-function.txt
They must reference a valid function.
> Validate function vars in elem segments

- src/binary-writer.c
- test/dump/invalid-data-segment-no-memory.txt
- test/dump/invalid-data-segment-offset.txt
- test/dump/invalid-elem-segment-no-table.txt
- test/dump/invalid-elem-segment-offset.txt
The binary writer should write invalid modules. This change allows
writing data/element segments if there is no memory/table segment,
respectively. It also writes the full init_expr, even if that would be
invalid.
Fixes issue #256.
> Write modules w/ invalid segments

- src/tools/wasm2wast.c
- test/binary/bad-function-names-too-many.txt
- test/binary/names.txt
- test/binary/no-names.txt
- test/help/wasm-wast.txt
- test/run-gen-wasm.py
- test/run-roundtrip.py
You can now disable this behavior by passing `--no-debug-names`.
> wasm2wast: parse the name section by default

- CMakeLists.txt
- scripts/travis-test.sh
- test/find_exe.py
- test/gen-spec-js.py
- test/run-gen-spec-js.py
- test/run-gen-wasm-interp.py
- test/run-gen-wasm.py
- test/run-interp.py
- test/run-opcodecnt.py
- test/run-roundtrip.py
- test/run-tests.py
- test/run-wasm-link.py
- test/run-wasmdump.py
This simplifies the invocations and aids maintainability.
> Pass --bindir to test helpers rather than full path to each tool

- .style.yapf
- scripts/gen-emscripten-exported-json.py
- test/find_exe.py
- test/gen-spec-js.py
- test/gen-wasm.py
- test/run-gen-spec-js.py
- test/run-gen-wasm-interp.py
- test/run-gen-wasm.py
- test/run-interp.py
- test/run-opcodecnt.py
- test/run-roundtrip.py
- test/run-tests.py
- test/run-wasm-link.py
- test/run-wasmdump.py
- test/update-spec-tests.py
- test/utils.py
This changs adds .style.yapf to define the python style
we are using.
I also ran yapf over all the python files:
$ yapf -i `git ls-files *.py`
Going forward, we should probably add a travis test to
prevent regressions.  We should probably also switch to
more conventional 4-space indentation, which is used by
almost everybody outside of Google.
> Add support for yapf python formatting tool

- src/binary-reader.c
- test/binary/bad-function-names-too-many.txt
ast-binary-reader will still fail if there are too
many names but the binary-reader itself will allow this
since the spec allows it.
> Allow more names than function in binary-reader

- src/binary-reader-ast.c
- src/binary-reader-interpreter.c
- src/binary-reader-objdump.c
- src/binary-reader.c
- src/binary-reader.h
- src/tools/wasm-link.c
It was being passed before as "index", which is confusing because the
other callbacks have recently been changed to pass the
func/global/memory/table index instead.
> Pass import_index to binary reader import callbacks

- src/binary-reader-objdump.h
- src/tools/wasmdump.c
- test/run-interp.py
- test/run-wasm-link.py
- test/run-wasmdump.py
These changes make wasmdump more closely match objdump.
Change -v/--verbose to -x/--details.  Change -r/--raw to
-s/--full-contents.  Error out unless on of -x/-d/-r/-h is
specified.  Previously wasmdump would simply print nothing
at all which was confusing.
> Improve wasmdump command line options

- src/binary-writer-spec.c
- src/binary-writer.c
- src/binary-writer.h
These assertions aren't useful if we allow writing invalid modules. I
asked @Cellule to pipe through `is_invalid` instead, but now I think
it's better to just remove the assertions.
> Remove index assertions in binary-writer.c

- src/apply-names.c
- test/binary/no-global-names.txt
The name section currently only provides names for functions and locals.
This fixes issue #286.
> Don't apply names in name section to globals

- src/binary-reader.c
- src/tools/wasm-link.c
- test/binary/relocs.txt
The string name of the target section comes before
the relocation count.
This was not tested because we don't currently generate
any relocations for custom sections, so I also added
a binary/relocs.txt test to generate a binary that
does.
> Fix reading of custom section relocations

- src/ast.c
- src/ast.h
- src/binary-writer-spec.c
- src/resolve-names.c
- src/validator.c
- test/parse/assert/nocheck-assertinvalid-resolve-names.txt
Names should be resolved in assert_invalid modules, even when running
wast2wasm with --no-check-assert-invalid-and-malformed.
This fixes issue #292.
> Resolve names in assert_invalid modules

- README.md
As of #253, wasm2wast now includes debug-names by default, letting you opt-out via `--no-debug-names`.
I also noticed that now wasm2wast and wast2wasm are inconsistent in that regard. The later still defaulting to excluding debug names. Is that intentional? Happy to PR if it too should be reversed. There's mostly a tradition of toolchains requiring opt-in for optimizations like excluding debug names, but I'm new around here 🤓
> Update README now that wasm2wast defaults to including debug names

- appveyor.yml
Looks like MSYS was rev'd from 5.3.0 -> 6.3.0 recently, breaking the appveyor bots, see https://ci.appveyor.com/project/WebAssembly/wabt/build/1.0.610/job/o0ad22qnjcjg1x62 for example.
This change uses the old image for now. We should figure out what's wrong w/ the errors there though.
> Roll back to previous MSYS2

- src/binary-writer.cc
- src/common.cc
Example: `unable to read file /path/to/file: No such file or directory`
Modified it locally when debugging an issue on my end, figured I might as well PR..
Also changed the single sprintf usage to wabt_snprintf
> Use perror to output error messages when reading files

- CMakeLists.txt
- Makefile
- src/ast-lexer.cc
- src/prebuilt/ast-lexer-gen.cc
- src/prebuilt/ast-parser-gen.cc
- src/prebuilt/ast-parser-gen.hh
The built-in CMake rules look for an .hh file instead of a .h when
building for C++. Without it, the build will always think that the
generated parser is stale and rebuild it.
> Update CMake and Makefile to use .hh instead of .h

- scripts/travis-build.sh
It isn't installed on Mac. This fixes the mac build (issue #325).
> Only run flake8 on Travis Linux

- CMakeLists.txt
Hoping this resolves compilation issues some folks are having on Mac OS
X.
> Use the CMAKE_STANDARD property on all targets

- src/binary-reader-ast.cc
- src/binary-reader-linker.cc
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/common.h
- src/tools/wasm-link.cc
- test/binary/bad-function-names-too-many.txt
- test/binary/names.txt
- test/binary/no-global-names.txt
- test/dump/debug-import-names.txt
- test/dump/debug-names.txt
- test/link/names.txt
This PR should change the code to support the new extensible name section rather than the previous now-obsolete layout.
However, I've so far been unable to find any code (except for my own) that produces or reads the new format, so it's not as well-tested as it should be; it might be worth waiting for adoption in other tools, in any case.
See https://github.com/WebAssembly/wabt/issues/334.
> Extensible name section support

- README.md
- src/binary-reader-linker.cc
- src/binary-reader-linker.h
- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/binary-reader.cc
- src/tools/wasm-link.cc
- src/tools/wasmdump.cc
Enable logging in the binary reader when the --debug
flag is passed to wasmdump and wasm-link.
Also don't wrap on_error when logging is enabled otherwise
tools that don't set on_error such as wasmdump won't see
any errors (since the reader will think a handler is installed).
> Add --debug flag to wasmdump and wasm-link

- src/tools/wasmdump.cc
We need only include debug logging in the prepass
which is unconditionally performed at the start.
> Don't dump debug info more than once in wasmdump

- src/ast-parser-lexer-shared.cc
- src/binary-reader.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/common.cc
- src/generate-names.cc
I tried to use a compiler without `snprintf` and it was causing me some problems.
When I realized that there was a version in wabt, I figured the wabt version was supposed to be used everywhere, but since most compilers has snprintf it hasn't been an issue before.
> Use wabt_snprintf instead of calling snprintf directly

- CMakeLists.txt
- appveyor.yml
Partial fix for #324 
In my previous `test.cpp` example in #324:
- Change both or just one of `stdio.h` and `stdint.h` to `cstdio` and `cstdint`: warnings.
- Add `stdlib.h`: warnings.
After checking `stdlib.h`, I found out that it includes `cstdlib` for C++ code and this (for some reason I do not know) is the culprit of the print format warnings. Adding `-D_GLIBCXX_INCLUDE_NEXT_C_HEADERS=1` solves this issue.
This only fixes print format warnings `-Wformat=`.
> [Mingw64] fix print format warning

- CMakeLists.txt
- src/config.h.in
mingw32 tries to support both VC runtime printf and a POSIX-compliant
printf. It seems to randomly choose between the two, depending on
arbitrary factors like header include order. This change forces us to
always use the POSIX-compliant printf on mingw, and also changes the
WABT_PRINTF_FORMAT attribute to use the POSIX-compliant tag too
(gnu_printf, since printf defaults to ms_printf).
This seems to resolve the issues for #324, as well as the ones I found
in #342 as well.
> Fix mingw build by defining _POSIX

- src/common.cc
In #318 I incorrectly used `sizeof` on a pointer :man_facepalming: which obviously is not correct.
> use array of chars instead of pointer to chars so sizeof is correct

- src/binary-reader-ast.cc
- src/binary-reader-interpreter.cc
- src/binary-reader-linker.cc
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
I think our binary reader API can be improved by passing module/field names to the specific on_import_{func,table,...} methods rather than requiring users to store the names in their private context.
There's no real reason to think of a function import, say, as two events: it's a single event, with many parameters, but that's not a problem for the current C++ code. Particularly for simple translating binary readers, saving temporary data in between calls that you're assuming are always paired makes the code slightly less readable.
> binary reader API: pass module/field names to on_import_*

- src/binary-reader-linker.cc
- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/common.cc
- src/common.h
- src/tools/wasm-link.cc
- src/wasm-link.h
- test/link/export.txt
- test/link/function_calls.txt
- test/link/function_calls_incremental.txt
- test/link/globals.txt
- test/link/incremental.txt
- test/link/interp.txt
- test/link/names.txt
- test/link/table.txt
This brings wabt into line with what llvm is now
producing and what is soon that land in the
tool-conventions "spec" for static linking.
Adds 'index' and (options) 'addend' to relocations.
Define Relec in common.h rather than once for each
tool.
> Update relocation encoding to latest "spec"

- src/ast-parser.y
- src/binary-reader-ast.cc
- src/binary-reader-interpreter.cc
- src/binary-reader-objdump.cc
- src/binary-reader-opcnt.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/common.cc
- src/common.h
- src/prebuilt/ast-parser-gen.cc
- src/resolve-names.cc
- test/binary/bad-logging-basic.txt
- test/dump/bad-version-logging.txt
- test/dump/bad-version.txt
- test/interp/basic-logging.txt
- test/interp/basic-tracing.txt
- test/run-gen-wasm-interp.py
- test/run-interp.py
- test/run-tests.py
- test/run-wasmdump.py
When the binary logging is turned on, it can't use the
`reader->on_error` directly since that function expects that the
user_data is the BinaryReaderInterpreter context (for example), but it
is actually the LoggingContext.
Some additional changes:
* Add a test that uses logging and succeeds
* Add a test that uses logging and has an error
* Change the `run-*-interp.py` scripts to use `-t` for tracing and `-v`
for logging
> Fix crash using binary reader logging with error

- src/ast-writer.cc
- src/binary-reader-ast.cc
- src/binary-reader-interpreter.cc
- src/binary-reader-linker.cc
- src/binary-reader-linker.h
- src/binary-reader-objdump.cc
- src/binary-reader-opcnt.cc
- src/binary-reader.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/generate-names.cc
- src/resolve-names.cc
- src/tools/wasm-link.cc
- src/validator.cc
- src/wasm-link.h
Context is the most common potential problem here, but I noticed that
wasm-link.h had some others too (DataSegment and Export).
These probably aren't an issue yet, since they all have trivial
constructors. As soon as we add non-trivial types to these they break
though.
> Fix potential one-definition-rule breaking structs

- CMakeLists.txt
- appveyor.yml
- scripts/travis-test.sh
- src/hash-util.cc
- src/hash-util.h
- src/string-view.cc
- src/string-view.h
- src/test-string-view.cc
This change also adds `wabt-unittests` with `string_view` tests, and runs them on appveyor and travis.
> Add wabt::string_view, based on C++17 string_view

- .gitignore
- Makefile
This means running `make` will generate a `bin` dir and put all the binaries in there. Similarly, `make clang-debug-asan` will install those binaries to the `bin` dir as well.
> Add install target to Makefile

- src/ast-lexer.cc
- src/prebuilt/ast-lexer-gen.cc
Fix bug when lexing from buffer where subsequent read from the buffer overwrites bytes still available.
Once the lexing reaches the end of the current read buffer, it currently copies the remaining bytes at the beginning of the read buffer instead of the end. This means it overwrites bytes that hasn't been read yet.
ie:
```cpp
// full wast  `(module (func $dummy))`
// initial buffer size = 12
// Before Fill()
lexer->buffer = "(module (fun";
lexer->token = "(fun";
// calling fill because there is not enough content left in the read buffer
// after fill now
lexer->token = lexer->buffer = " $dummy))";
// after fill with this fix
lexer->token = lexer->buffer = "(func $dummy))"
```
> Fix lexing from binary buffer

- src/binary-reader-objdump.cc
- test/link/export.txt
- test/link/function_calls.txt
- test/link/function_calls_incremental.txt
- test/link/globals.txt
- test/link/incremental.txt
- test/link/interp.txt
- test/link/names.txt
- test/link/table.txt
Print the addend and make it more clear what the
different offsets mean.
> wasmdump: Improve printing on relocation information

- src/binary-reader-objdump.cc
- src/tools/wasm-link.cc
- test/dump/debug-names.txt
Previously we could nest the local names inside the
function names, but in the new names sections the locals
all come later on.
> wasmdump: Fix output of local names

- src/tools/wasm-link.cc
- test/link/names.txt
The code was assuming that all functions were named
and using a simple increment rather than calculating
the actual function index in the new binary.
> wasmlink: Fix function indexes in name section

- test/run-tests.py
There was a bunch of redundant splitting and joining
going on.
> Cleanup default test tools declartion in run-tests.py

- CMakeLists.txt
It breaks my Vim workflow :) But seriously, we should just figure out a
nicer way to handle this with Ninja if that's what we want.
> Don't force color diagnostics on Clang

- test/run-tests.py
We shouldn't eat Exceptions, just our own local Errors; that way bugs in
the test runner propagate out to give us nice stack traces.
> Properly handle keyboard interrupt in run-tests.py

- scripts/travis-test.sh
- test/binary/relocs.txt
Oops, we were silently ignoring tests failures on travis.
Also turn on -v when running travis tests so it records the tests it runs
> Return non-zero on travis if tests fail

- src/binary-reader-linker.cc
- src/binary-reader.cc
- src/binary-writer.cc
- test/binary/bad-duplicate-subsection.txt
- test/binary/bad-name-section-invalid-index.txt
- test/binary/bad-subsection-out-of-order.txt
- test/binary/bad-subsection-size.txt
- test/binary/bad-subsection-unfinished.txt
- test/dump/debug-names.txt
- test/link/names_import_only.txt
Only emit names for function that actually have one.
Previously we were emitting empty strings for functions
without names.  The new version of the names section
allow for a sparse list.
Also, cleanup the funtion name handling in wasm-link.
> Allow names section to be sparse

- src/tools/wasm-link.cc
- test/link/export.txt
- test/link/function_calls.txt
- test/link/function_calls_incremental.txt
- test/link/globals.txt
- test/link/incremental.txt
- test/link/interp.txt
- test/link/names.txt
- test/link/table.txt
We recently switched to embedding the index of the relocation
within the relocation entry itself but overlooked the fact
that this needs to be updated when writing out the linked
reloc section.
> [wasmlink] Relocate indexes in the gererated reloc section

- src/type-checker.cc
- test/typecheck/br-table-loop.txt
If a loop has a signature, it is the signature for fallthrough, not for
the branch target. So a br_table to the loop label should always be
void.
This fixes issue #389.
> Fix type-checking bug w/ br_table and loop

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/tools/wasmdump.cc
Its almost a pure refactor of the code in binary-reader-objdump.cc.  The one exception is the
change in the way the header printing is done.
> Refactor wasmdump so that the disassembly pass has its own reader class

- src/ast-parser.y
- src/prebuilt/ast-parser-gen.cc
- src/prebuilt/ast-parser-gen.hh
- test/desugar/implicit-func-type.txt
When a function is defined without an explicit type, it will first
search the already defined (implicitly or otherwise) func types. If one
is found, it will use it. Otherwise it will define its own and use that.
The code previously would define this new type after the function, which
works but doesn't roundtrip properly because it ends up defining the
same func type twice.
> Define the implicit func type before the function

- src/binary-reader-linker.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- test/dump/memory.txt
- test/link/data.txt
- test/link/export.txt
- test/link/function_calls.txt
- test/link/function_calls_incremental.txt
- test/link/globals.txt
- test/link/incremental.txt
- test/link/interp.txt
- test/link/names.txt
- test/link/table.txt
For data segments, print the file offsets so they match
the file offsets shown when dumping relocations.
For relocations, only show the addend when one is present
and correctly display negative addends in the same way that
objdump does (e.g. symbol_foo-0x10 and symbol_foo+0x10)
> Improve wasmdump output for relocations and data segments

- src/binary-reader-interpreter.cc
- test/spec/br_table.txt
- test/spec/globals.txt
- test/spec/import-after-global.fail.txt
- test/spec/memory_trap.txt
This exposed a small bug where an empty init expr would have type 0,
which would print as "(null)" since it didn't exist.
> Update the testsuite

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/tools/wasmdump.cc
- test/dump/multi_file.txt
- test/run-wasmdump.py
This mimics how objdump behaves. Also makes the code more
readable.
Looking into adding a test for this but looks tricky with the current framework.
> wasmdump: support multiple input files

- README.md
With CMake version <= 3.1 on OSX you will see errors like the following because of https://cmake.org/Bug/view.php?id=15355 
```
Make Error in CMakeLists.txt:
Target "hexfloat_test" requires the language dialect "CXX11" (with compiler
extensions), but CMake does not know the compile flags to use to enable it.
CMake Error in CMakeLists.txt:
Target "wabt-unittests" requires the language dialect "CXX11" (with
compiler extensions), but CMake does not know the compile flags to use to
enable it.
CMake Error in CMakeLists.txt:
Target "wasm-interp" requires the language dialect "CXX11" (with compiler
extensions), but CMake does not know the compile flags to use to enable it.
CMake Error in CMakeLists.txt:
Target "wasm-link" requires the language dialect "CXX11" (with compiler
extensions), but …
```
> note CMake version dependency on OSX

- README.md
Nothing groundbreaking going on here. This PR simply improves the readability of the readme's code samples by colouring comments and output lines differently.
> Add highlights to readme code-blocks

- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-writer.cc
- src/common.cc
- src/common.h
Sorry no tests for these names since they are not generated from .wast format yet.
> Update relocation names to match "spec"

- .gitattributes
- demo/custom.css
- demo/demo.js
- demo/examples.js
- demo/index.html
- demo/third_party/codemirror/LICENSE
- demo/third_party/codemirror/codemirror.css
- demo/third_party/codemirror/codemirror.js
- demo/third_party/codemirror/simple-mode.js
- demo/wast-mode.js
This also includes a simple codemirror syntax highlighter for the wast
format, using the `simple-mode.js` codemirror plugin.
I've also moved the examples out from `demo.js` to `examples.js`.
The codemirror.css and codemirror.js files are marked as binary so they
don't show up in diffs; we shouldn't be patching them anyway.
> Use codemirror for wast2wasm JS demo

- src/binary-writer.cc
- src/tools/wasm-link.cc
- test/link/table.txt
This relocation type is used for the signature type
immediate of the call_indirect instruction.
> Add support for type relocations

- src/binary-reader-linker.cc
- src/tools/wasm-link.cc
- src/wasm-link.h
- test/link/names.txt
- test/link/names_import_only_module_env.txt
Currently a module name must be `__extern` with this change any module
name is allowed.
> Allow any module name

- CMakeLists.txt
- src/binary-reader.cc
- src/binary-writer-spec.cc
- src/test-utf8.cc
- src/utf8.cc
- src/utf8.h
- test/dump/string-hex.txt
- test/parse/string-hex.txt
- test/spec/names.txt
- test/spec/utf8-custom-section-id.txt
- test/spec/utf8-import-field.txt
- test/spec/utf8-import-module.txt
- test/utils.py
This is enough to pass the testuite, but doesn't yet validate utf8
strings in the text format.
> Implement UTF-8 validation, update testsuite

- src/binary-reader-ir.cc
- src/binary-writer.cc
- src/wat-writer.cc
- test/binary/names.txt
- test/binary/no-global-names.txt
- test/dump/debug-import-names.txt
- test/dump/debug-names.txt
- test/link/names.txt
- test/link/names_import_only.txt
- test/link/names_import_only_module_env.txt
Attempt at fixing #448 .. still need to figure out how to strip the $ on parse.
> Don't include leading $ in wasm binary name section

- Makefile
Without this, Make complains:
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to
parent make rule.
> Use + with $(MAKE) to use jobserver

- src/binary-reader-objdump.cc
- test/link/function_calls.txt
- test/link/incremental.txt
- test/link/interp.txt
- test/link/table.txt
- test/run-wasm-link.py
Also, have wasmdump list debug names for function table
elements.
These changes make it easier to interpret the wasm-link
test outputs.
> Add debug names to wasm-link tests

- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader.cc
- src/binary-reader.h
This removes the use of setjmp/longjmp as well.
> Clean up BinaryReader; rename to BinaryReaderDelegate

- src/binary-reader-interpreter.cc
- src/binary-reader-interpreter.h
- src/common.h
- src/interpreter.cc
- src/interpreter.h
- src/tools/wasm-interp.cc
The only names that conflict are `wabt::Opcode` vs.
`interpreter::Opcode` and `wabt::Result` vs. `interpreter::Result`.
Other names would conflict too (e.g. `FuncSignature`) but those aren't
ever included in the interpreter-related code.
> Move interpreter stuff into its own namespace

- test/find_exe.py
This is where 'make install' will put stuff by default.
> Change default tools path from 'out' to 'bin'

- test/run-tests.py
This means we get verbose test output when (for example)
running within ninja.
> Only use single line test output if attached to a tty

- src/binary-reader-interpreter.cc
- src/binary-reader-interpreter.h
- src/interpreter.cc
- src/interpreter.h
- src/tools/wasm-interp.cc
- src/writer.h
* Make interpreter::Thread and interpreter::Environment into C++ classes
* Move function running code into interpreter (was in wasm-interp)
* Move environment searching functions into interpreter (was in
binary-reader-interpreter)
* Remove free functions, use member functions on Environment/Thread
instead.
> Clean up the interpreter

- src/wat-writer.cc
- test/roundtrip/invalid-br-var.txt
WatWriter can't rely on the module having been previously validated.
Fixes #468.
> Fix assert in wasm2wast with invalid br var

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/tools/wasm-objdump.cc
Also, use C++ constructor inheritance to avoid some
boilerplate constructors.
> [objdump] Split out state from ObjdumpOptions

- src/prebuilt/wast-parser-gen.cc
- src/validator.cc
- src/wast-parser.y
- test/parse/expr/bad-block-sig-multi.txt
- test/parse/expr/bad-if-sig-multi.txt
- test/parse/expr/bad-loop-sig-multi.txt
- test/parse/expr/bad-return-multi.txt
- test/parse/module/bad-global-invalid-expr.txt
- test/typecheck/bad-if-condition-type-mismatch.txt
The parser and typechecker allow multiple types in block signatures:
block i32 i32
...
end
But these are not currently supported in the MVP, and there is no way to
serialize them. This change makes them a validation error.
This change also fixes the default location handling of non-terminal
nodes in the parser; they used to look weird because they would use the
ending column from the last symbol in the rule, even if that symbol was
on a different line.
Fixes #473.
> Validate block signatures w/ multiple types

- src/binary-reader-linker.cc
At least this sets the current interface assumptions.
I tend to think detection of a global mutable export like `cur_stack_pointer` and a global const like `stack_start`, should be a detectable ABI convention allowing automatic handling of memory import merging in this case based on `stack_start -> stack_startA + stack_startB`, and also that the concept of relying on relocatable sections existing will just contribute to fragmenting linker ABI assumptions. But I have no leverage apart from purely saying so in these discussions!
> Disable memory imports/exports in linker

- src/binary-reader-ir.cc
- test/roundtrip/inline-export-func-name.txt
The debug name don't have a '$', and add it in when converting to IR.
This worked properly for func->name, but wasn't updated for the func
bindings.
> Fix bug in BinaryReaderIR w/ debug names

- CMakeLists.txt
- Makefile
The last build will always be in the bin directory. This also means that
`make install` will install to the "normal" place for that OS, e.g.
`/usr/local/bin`.
Fixes #495.
> Use custom command to copy to bin/

- test/binary/gen-wasm-parse-error.txt
- test/gen-wasm.py
- test/run-gen-wasm.py
- test/utils.py
Previously gen-wasm.py would return 0 on parse errors
rather than bailing out and causing tests to fail.
> Error out of parse errors in gen-wasm.py

- CMakeLists.txt
- Makefile
- cmake/FindRE2C.cmake
- src/prebuilt/wast-lexer-gen.cc
- src/wast-lexer.cc
* Fix argument parsing in FindRE2C to allow multiple flags
* Condition enum must be generated by re2c
* A couple of characters didn't need to be escaped: / and ^
* `<LINE_COMMENT> [^\n]*` allowed empty strings
* `<*> [^]` conflicted with similar states in other conditions
> Enable and fix warnings for re2c

- src/wat-writer.cc
- test/regress/regress-9.txt
There was a dumb infinite loop because of confusion between `indent` and
`indent_`.
> Fix for writing wat file with long indentation

- CMakeLists.txt
Without this you get a weird error on older versions of CMake.
> Check for USES_TERMINAL support in CMakeLists.txt

- src/literal.cc
This will make it easier to update the parser to disallow out-of-range
hexfloat values (added recently to the spec parser).
> Share float parse code literal.cc with templates

- src/binary-reader-ir.cc
- test/binary/duplicate-names.txt
While this was previously allowed, it would result
in an invalid wast file since mutliple functions
would end up with the same name.
When generating labels we now add a unique numeric
suffix (.1, .2 etc) a la llvm-link.
We could add magic behaviour to strip these out
again when producing the name sectio in wast2wasm
which would allow for cleaner roundtrip, but might
cuase confusion/issues for those who might want
to legitametly name thier functions with such
suffixes.
> Allow duplicate names in the name section

- src/literal.cc
- test/dump/hexfloat_f32.txt
- test/dump/hexfloat_f64.txt
- test/hexfloat.cc
- test/spec/const.txt
- test/spec/type.txt
* Return error when floats overflow (used to return inf)
* Significantly simplfy the significand parser in FloatParser::ParseHex
* Add some new parse tests to hexfloat.cc; the previous tests only
checked valid/canonical strings
> Update the testsuite; fix literal parsing issues

- src/binary-writer.cc
- test/exceptions/try-text.txt
- test/exceptions/try.txt
Defines how to write the contents of exception handling instructions.
Note: It doesn't yet handle exception declarations.
> Update the binary writer to handle try/catch/throw/rethrow instructions.

- src/circular-array.h
- src/wast-parser-lexer-shared.h
The current implementation of a circular array did not construct/destruct the elements in its contents array. This PR fixes this problem.
Note: This problem was pointed out by @winksaville. He showed that if you compile with -Werror that you get warnings (converted to errors) about assigning to uninitialized data.
The fix is to use a placement new to construct the elements in the constructor, and to call the destructor on all elements in the destructor.
> Fix circular array to create/destroy elements.

- src/validator.cc
- test/exceptions/bad-throw.txt
- test/exceptions/catch-all-not-last.txt
- test/exceptions/rethrow-not-in-catch.txt
- test/exceptions/rethrow-to-wrong-block.txt
- test/exceptions/try-exports.txt
- test/exceptions/try-imports.txt
Discovered that one of the exception tests was failing because of a null pointer dereference. This CL fixes the problem.
It also adds -v to exception test files (with exceptions) so that we are capturing how the constructs are being compiled into the binary form.
> Fix dereference of null pointer in validator.

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/stream.cc
- src/stream.h
- test/dump/memory.txt
- test/link/data.txt
Use the virtual address (init offset) when display
the data rather that the file offset.
Show the segment size in the header.
> Improve display of data segments

- src/binary-writer.cc
- test/exceptions/try-exports.txt
- test/exceptions/try-imports.txt
- test/exceptions/try-text.txt
- test/exceptions/try.txt
Generate exception section, imported exceptions, and exported exceptions. At this point, we can successfully convert wast files with exceptions to their corresponding wasm files.
Also updates exceptions to reflect the changes.
> Fix binary writer to handle exception declarations.

- src/type-checker.cc
- src/validator.cc
- test/exceptions/rethrow-not-in-catch.txt
- test/exceptions/rethrow-to-wrong-block.txt
Cleans up the error messages for rethrows.
In particular, it only reports on valid depth values (associated with the catch they appear in).
> Clean up errors messages for bad rethrow instruction.

- src/wast-lexer.cc
This fixes an uninitialized warning/error when compiling with c++ 7.1.1.
> Fix ununitailzed value_ in LexToken

- src/apply-names.cc
- src/ir.cc
- src/ir.h
- src/wat-writer.cc
- test/desugar/try-exports.txt
- test/desugar/try-import.txt
- test/desugar/try.txt
Updates generate/apply names, as well as the wat writer, allowing wast-desugar to work.
Also fixes the following nits:
* Fixes NameApplier::UseNameForVar() to not leak a string slice (i.e. don't override name if
it exists).
* Removes unnecessary "Module" arguments in class NameApplier (it is already a field).
> Make wast-desugar work for exception handling.

- src/binary-reader-ir.cc
- src/binary-writer.cc
- src/cast.h
- src/common.cc
- src/common.h
- src/expr-visitor.cc
- src/ir.cc
- src/ir.h
- src/prebuilt/wast-lexer-gen.cc
- src/prebuilt/wast-parser-gen.cc
- src/validator.cc
- src/wast-parser.y
- src/wat-writer.cc
Also added LLVM-style casting free functions:
- isa<T>: returns true if the object is of type T
- cast<T>: converts object to T* or asserts
- dyn_cast<T>: converts object to T* or returns nullptr
> Use type hierarchy for ModuleField instead of union

- src/wast-lexer.cc
As suggested by Sam Clegg (@sbc100) this is a simpler solution to
my first solution, PR #530.
> Explicitly initialize LexToken.value_ with 0

- src/wabt.post.js
- src/wabt.pre.js
It is currently necessary to postprocess libwabt.js to support different kinds of module loaders, especially CommonJS-style `require` and AMD-style `define`. This PR adds CommonJS and AMD module loader support directly to wabt.pre/post.js and exposes `wabt` as a global var only if neither is available.
Unfortunately, I haven't yet figured out where exactly libwabt.js is built with emscripten, so the new generated file is not included. In case you decide to merge the PR, I would appreciate if libwabt.js could be updated as well.
> Support for CommonJS and AMD loaders in libwabt.js

- src/binary-writer-spec.cc
- src/ir.cc
- src/ir.h
- src/prebuilt/wast-parser-gen.cc
- src/resolve-names.cc
- src/validator.cc
- src/wast-parser.y
Also remove CommandType::AssertInvalidNonBinary. It was only used for
the case when assert_invalid could not generate a binary file because
names could not be resolved. This error is now handled by
assert_malformed with a quoted binary.
> Use type hierarchy for Command instead of union

- CMakeLists.txt
- src/intrusive-list.h
- src/test-intrusive-list.cc
This will be used to replace lists of Exprs, ModuleFields, and other
manual linked lists.
> Add intrusive_list implementation

- src/binary-reader-ir.cc
- src/binary-writer.cc
- src/expr-visitor.cc
- src/expr-visitor.h
- src/ir.cc
- src/ir.h
- src/prebuilt/wast-parser-gen.cc
- src/prebuilt/wast-parser-gen.hh
- src/validator.cc
- src/wast-parser-lexer-shared.h
- src/wast-parser.y
- src/wat-writer.cc
Nothing much special here, but it is becoming increasingly annoying that
the parser Token cannot have value types (so everything must be moved
then deleted).
> Use intrusive_list for Expr

- src/binary-reader-ir.cc
- src/binary-writer.cc
- test/exceptions/try-imports.txt
- test/roundtrip/try-imports.txt
According to the proposal for exception handling, only exceptions not imported should be defined in the exceptions section.
This PR fixes the code, which assumed all exceptions appear in the exception section.
> Fix handling of exception section.

- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/binary-writer.cc
- src/tools/wasm-objdump.cc
- test/dump/try-exports.txt
- test/dump/try-imports.txt
- test/dump/try.txt
- test/help/wasm-objdump.txt
- test/run-objdump.py
Modifies the wasm objdump code to understand exceptions.
Adds command-line argument --future-exceptions to wasm-objdump and run-objdump.py.
Modifies class BinaryReaderNop so that its default behavior can be defined by a flag that defines if
exception handling should be accepted.
> Adds the concept of exceptions to wasm-objdump

- src/wat-writer.cc
- test/roundtrip/inline-export-multi.txt
It is possible to export the same func (or global, memory, etc.) twice
with a different name. This is supported by the inline export format,
but was broken -- it would only print the name of the last export.
> Fix inline export for multiple exported kinds

- src/wat-writer.cc
- test/roundtrip/try-exports-inline.txt
Noticed that inline exports were not handled. This PR fixes that omission, and adds a test.
> Add inline exports to wat-writer.

- src/binary-writer.cc
- test/dump/try-details.txt
- test/dump/try-exports-details.txt
- test/dump/try-exports.txt
- test/dump/try.txt
- test/exceptions/try-exports.txt
- test/exceptions/try-text.txt
- test/exceptions/try.txt
When looking at the V8 compiler, and wasm-interp, the details of exceptions must be known before the code section is processed (i.e. translated). This PR moves the (named) exception section to immediately before the code section.
> Move exception section to just before code section.

- src/apply-names.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/binding-hash.cc
- src/binding-hash.h
- src/common.h
- src/ir.cc
- src/ir.h
- src/prebuilt/wast-parser-gen.cc
- src/resolve-names.cc
- src/validator.cc
- src/wast-parser.y
- src/wat-writer.cc
This change keeps the union, but hides it behind accessors. The
implementation is a bit complex since std::string requires constructors
and destructors to be called. As a result we have to use placement new
and explicit destructors.
> Use std::string instead of StringSlice in Var

- src/tools/wasm2wast.cc
- test/binary/bad-typecheck-missing-drop.txt
Errors are binary locations, not text.
See #557.
> Fix location of error in wasm2wast

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/binary-writer.h
- src/binding-hash.h
- src/common.cc
- src/common.h
- src/generate-names.cc
- src/interpreter.h
- src/ir.cc
- src/ir.h
- src/prebuilt/wast-parser-gen.cc
- src/resolve-names.cc
- src/tools/wasm-link.cc
- src/validator.cc
- src/wast-parser-lexer-shared.h
- src/wast-parser.y
- src/wat-writer.cc
All member variables are now std::string, and most parameters are
string_view. This allows us to remove many of the destructors.
> Remove uses of StringSlice from IR

- src/binary-writer-spec.cc
- src/stream.cc
- src/stream.h
- src/writer.cc
- src/writer.h
This previously had an upper limit to the extension length.
I've also taken this opportunity to modify the Writer and Stream APIs to
take `string_view` instead of `const char*` for filenames.
> Clean up BinaryWriterSpec::GetModuleFilename

- src/string-view.cc
- src/test-string-view.cc
The position needs to be clamped when the needle is larger than the
haystack.
> Fix bug in string_view::rfind

- src/apply-names.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/binary-writer.h
- src/binding-hash.h
- src/common.h
- src/ir.cc
- src/ir.h
- src/stream.cc
- src/stream.h
- src/test-string-view.cc
- src/wat-writer.cc
- src/writer.cc
- src/writer.h
It's a value type, so it should be passed by value, just like int, etc.
For x64-clang linux ABI, it seems to be passed in two registers rather
than requiring indirection, so may be faster too.
> Always pass string_view by value

- src/binary-reader-ir.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/ir.cc
- src/ir.h
- src/prebuilt/wast-parser-gen.cc
- src/prebuilt/wast-parser-gen.hh
- src/stream.h
- src/wast-parser.y
- src/wat-writer.cc
* Also switch ScriptModule data to std::vector
* In wast-parser.y:
- Change DupTextList to write to std::vector
- quoted_text uses CopyStringContents instead of DupTextList
> Use std::vector for DataSegment data

- src/binary-reader-linker.cc
- src/common.cc
- src/common.h
- src/tools/wasm-interp.cc
- src/tools/wasm-link.cc
- src/tools/wasm-objdump.cc
- src/tools/wasm-opcodecnt.cc
- src/tools/wasm2wast.cc
- src/wasm-link.h
It would be nicer to have the various read_* functions not take a void*,
size_t pair either, but that's work for another PR (perhaps introducing
a span-like API?)
I've also been considering having ReadFile return a wrapper object
instead, so this could just mmap the file.
Fixes #570.
> Rename read_file -> ReadFile; now returns vector

- src/binary-reader-linker.cc
- src/tools/wasm-link.cc
- src/wasm-link.h
Also remove SectionDataCustom from wasm-link.h; it doesn't seem to be
used.
> Remove uses of StringSlice from wasm-link

- src/binding-hash.h
- src/common.cc
- src/common.h
- src/literal.h
- src/prebuilt/wast-lexer-gen.cc
- src/prebuilt/wast-parser-gen.cc
- src/prebuilt/wast-parser-gen.hh
- src/wast-lexer.cc
- src/wast-lexer.h
- src/wast-parser-lexer-shared.cc
- src/wast-parser-lexer-shared.h
- src/wast-parser.y
* Added StringTerminal only used by the lexer and parser, since we need an
object that has a non-trivial constructor/destructor (so it can be
included in the Token union).
* Name all terminal Token members with `t_` prefix
* Rename Literal -> LiteralTerminal, and only use for the lexer/parser.
* Move LiteralType to literal.h
* Use std::vector<std::string> for TextList and rename to TextVector
* Renamed CopyStringContents -> UnescapeString, and make it a template
so it can write to a std::string and a std::vector.
* Rename DupTextList -> UnescapeTextVector, and simplify it
considerably.
> Remove StringSlice

- src/prebuilt/wast-parser-gen.cc
- src/wast-parser.y
This combines the std::move + delete behavior that was used throughout
wast-parser.y in a cleaner way.
I've also renamed the other helper functions to MixedCase, and added the
PrependAndDelete and AppendAndDelete helper functions too.
> Add MoveAndDelete helper function to parser

- .travis.yml
- CMakeLists.txt
- src/binary-reader-opcnt.cc
- src/binary-reader-opcnt.h
- src/stream.cc
- src/stream.h
- src/tools/wasm-opcodecnt.cc
- test/opcodecnt/basic.txt
- test/opcodecnt/cutoff.txt
- test/opcodecnt/immediates.txt
- test/run-opcodecnt.py
- ubsan.blacklist
Simplify some of the code using map instead of vector. Also added the
ability to count immediates of any opcode.
> Refactor wasm-opcodecnt.

- src/type-checker.cc
- test/regress/regress-10.txt
The previous type-checking code just made sure the value on the top of
the stack is the correct type. This isn't sufficient when the stack is
polymorphic, because the concrete type is not pushed onto the stack.
Fixes #586.
> Fix tee_local typechecking bug w/ polymorphic stack

- src/type-checker.cc
- test/regress/regress-11.txt
Similar to issue #586, it is necessary to pop and re-push the type on
the top of the stack when validating br_if, because otherwise the
concerete type is not pushed on the stack (i.e. the top remains
polymorphic).
Fixes #588.
> Fix type-checking bug in br_if w/ polymorphic stack

- .gitattributes
- README.md
This PR uses some [GitHub-specific gitattributes](https://github.com/github/linguist#overrides) to enable WAST's syntax highlighting for `*.txt` test-files. They're currently being highlighted as plain text, because `.txt` isn't listed as a [registered WebAssembly extension](https://github.com/github/linguist/blob/f75c570/lib/linguist/languages.yml#L4748-L4753).
I also made sure to keep the files from counting toward the repository's language summary. Data and prose-type languages are always excluded by default (which is why you're not seeing `Text` occupy 45% of the codebase)... but since WebAssembly is a programming language, the reclassification would make them all count toward the usage total, potentially replacing the project's status as a C++ project.
Excluding large, ancillary …
> Add WAST highlighting to *.txt files in tests directories

- src/binary-reader-interpreter.cc
- src/interpreter.cc
- src/interpreter.h
- src/tools/wasm-interp.cc
- test/spec/globals.txt
- test/spec/imports.txt
- test/spec/linking.txt
* Create Import derived classes instead of using union
* Use cast/dyn_cast for interpreter Func and Module (Defined vs. Host)
* Remove OnImport callback in BinaryReaderInterpreter; do all the work
in the kind-specific callbacks (e.g. OnImportFunc)
> Refactor interpreter imports

- src/emscripten-exported.json
This commit added missing functions to the export table.  This functions used in `wabt.post.js`.
> added missing function in emscripten export

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-reader-linker.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/common.h
- src/expr-visitor.cc
- src/generate-names.cc
- src/interpreter.h
- src/ir.cc
- src/ir.h
- src/resolve-names.cc
- src/tools/wasm-link.cc
- src/validator.cc
- src/wasm-link.h
- src/wast-parser.cc
- src/wast-parser.h
- src/wat-writer.cc
* Nicer static constructors for Const (e.g. `Const::F32()`)
* Protect `type` member when used as discriminant in type hierarchy 
(e.g. `Expr`, `ModuleField`, etc.)
* Remove pointer member fields where possible. Where not, use `std::unique_ptr` instead.
* Remove nearly all uses of unions (`Var` and `Const` still use them)
> Clean up various structs in ir.h

- src/apply-names.cc
- src/binary-reader-interpreter.cc
- src/binary-reader-ir.cc
- src/binary-reader.cc
- src/common.h
- src/expr-visitor.cc
- src/generate-names.cc
- src/interpreter.cc
- src/lexer-source-line-finder.cc
- src/lexer-source.cc
- src/literal.cc
- src/result.h
- src/tools/wasm-interp.cc
- src/tools/wasm-objdump.cc
- src/type-checker.cc
- src/validator.cc
- src/wast-parser.cc
* Unify all uses of `CHECK_RESULT`
* Use `CHECK_RESULT` in a few more places
* Add `operator|` and `operator|=` to `Result`, use it instead of
`COMBINE_RESULT`
* Change a few occurrences of `!Succeeded` to `Failed`
> Move Result to its own file (result.h)

- src/binary-reader-ir.cc
- src/cast.h
- src/common.h
- src/intrusive-list.h
- src/ir.cc
- src/ir.h
- src/make-unique.h
- src/test-intrusive-list.cc
- src/wast-parser.cc
By using std::unique_ptr in more function signatures, we can avoid calls
to `std::unique_ptr<T>::release`.
This change also moves `wabt::MakeUnique` into `src/make-unique.h` so it
can be used in `intrusive-list.h` and `test-intrusive-list.cc` without
pulling in all of `common.h`.
> Use std::unique_ptr in intrusive-list API

- src/binary-reader-interpreter.cc
- src/binary-reader.cc
- test/spec/func_ptrs.txt
- test/spec/memory.txt
This is a conservative check that we can do in the binary
reader itself.  More extensive checking is still done in the
interpreter (i.e. vefiying the type of the global).
> Add type check to data segment offset

- src/emscripten-helpers.cc
- src/tools/wasm-interp.cc
- src/tools/wast-desugar.cc
- src/tools/wast2wasm.cc
- src/wast-parser.cc
- src/wast-parser.h
This removes a few more places we were using `delete`. I also checked
the emscripten build and found that the previous change to
`wabt::Result` broke this, so I fixed those too.
> Return unique_ptr<Script> from parser

- src/wast-parser.cc
- test/regress/regress-12.txt
This would previously fire an assert because it was attempting to
`ParseCommand` when `IsCommand` was false.
> Fix parsing bug in ParseCommandList

- src/stream.h
Seems to be causing a warning on some builds; I didn't see it on Travis,
though.
> Add virtual destructor to Stream

- src/emscripten-helpers.cc
- src/tools/wasm-interp.cc
- src/tools/wast-desugar.cc
- src/tools/wast2json.cc
- src/tools/wat2wasm.cc
- src/wast-parser.cc
- src/wast-parser.h
- test/parse/bad-crlf.txt
- test/parse/bad-error-long-line.txt
- test/parse/bad-error-long-token.txt
- test/parse/bad-single-semicolon.txt
- test/parse/bad-toplevel.txt
- test/parse/empty-file.txt
- test/parse/module/bad-module-multi.txt
- test/parse/module/bad-module-with-assert.txt
`.wat` files can only contain one module, and no assertions.
This fixes issue #621.
> Only allow parsing one module with wat2wasm

- src/circular-array.h
- src/test-circular-array.cc
This is necessary if we want to allow Token to have a destructor.
Also add some tests for the API.
> Support non-POD types in CircularArray

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/feature.h
- src/tools/wasm-objdump.cc
- test/help/wasm-objdump.txt
- test/run-objdump.py
Objdump should really make a best effort to display
anything its given.  There are other tools that are
better suited for validation.
Partial fix for #627
> Enable all reader features in objdump

- CMakeLists.txt
- src/lexer-source-line-finder.cc
- src/prebuilt/wast-lexer-gen.cc
- src/test-wast-parser.cc
- src/token.cc
- src/token.h
- src/wast-lexer.cc
- src/wast-lexer.h
- src/wast-parser.cc
- test/parse/bad-error-long-token.txt
Fixes issue #623.
* Move Token into its own file.
* Add WastParser tests. These ones are used because the source text is
very large, and it may be useful to generate parser tests
programmatically in the future too.
* Reorganize TokenType by the union data member it uses. This makes it
easier to determine which member needs to be
constructed/copied/destroyed.
- Bare (no data)
- Literal
- Opcode
- String
- Type
* Make Token store its string/literal data directly, rather than share
with lexer. This actually fixes the bug.
* Fix a couple of line-printing bugs:
- Very long tokens (e.g. "a" 20000 times) are now clamped to 80 chars.
- Very long lines are displayed properly in errors (e.g. a line with
65000 columns).
Fix a couple of line printing bugs, add tests
> Fix potential use-after-free in WastLexer

- src/opcode.cc
- src/opcode.h
- test/binary/bad-opcode-prefix.txt
- test/binary/bad-opcode.txt
Previously the opcode would always return 0.
Since `Opcode` only stores an enumeration, we represent invalid opcodes
as a negative number. This way `Opcode::GetInfo` can return the invalid
prefix and opcode number.
For now, these values are both 1-byte, but the current encoding can
be expanded to 2**24 opcodes.
This is a partial fix for #627.
> Correctly report the value of bad opcodes

- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/tools/wasm-interp.cc
- src/tools/wasm-objdump.cc
- src/tools/wasm2wat.cc
- test/binary/bad-opcode-prefix.txt
- test/binary/bad-opcode.txt
wasm-objdump wants to always try to read as much of the binary as
possible. This change adds a new `BinaryReader` option called
`stop_on_first_error` which can be set to `false` to enable this
behavior.
Currently this will bail on any error in a section, but will try to read
the next section. We may expand the error-handling behavior to try and
recover inside of a section as well, but it's probably best to keep it
simple for now.
Because `wasm-objdump` does multiple passes over the binary, the errors
would normally be displayed multiple times. We also add a `OnError`
override which will suppress the error message for all passes other than
the first.
I took this opportunity to clean up a `binary-reader.cc` a little too:
* Remove IN_SIZE macro and use a template instead
* Change C comments …
> [wasm-objdump] Continue reading sections on error

- CMakeLists.txt
- src/tools/spectest-interp.cc
- src/tools/wasm-interp.cc
- test/find_exe.py
- test/help/spectest-interp.txt
- test/help/wasm-interp.txt
- test/interp/callimport-zero-args.txt
- test/interp/import.txt
- test/interp/logging-all-opcodes.txt
- test/interp/tracing-all-opcodes.txt
- test/run-interp.py
- test/run-wasm-link.py
* `wasm-interp` tool now only runs `.wasm` file, not spec tests
* `wasm-interp` has a new flag `--host-print` for importing a print
function named "host.print"
* `spectest-interp` tool runs only `.json` files
> Add spectest-interp tool; split from wasm-interp

- src/tools/spectest-interp.cc
Separate SpecJSONParser into `JSONParser` and `CommandRunner`. Also add
the `spectest` namespace to avoid defining ambiguous names at the global
scope.
It's cleaner this way, and it will also make it easier to handle the new
`threads` command, which contains subcommands that need to be run in
parallel.
> Refactor spectest-interp

- src/binary-writer.cc
- src/ir.cc
- src/ir.h
- src/resolve-names.cc
- src/wast-parser.cc
- test/regress/regress-14.txt
- test/regress/regress-15.txt
- test/regress/regress-16.txt
* Assertion/hang when parsing an invalid value type list
* Assertion parsing an invalid module field
* Assertion when two start sections are specified, and one of them has a
named function
> Fix some fuzzer-found regressions

- CMakeLists.txt
- src/binary-reader-interp.cc
- src/binary-reader-interp.h
- src/interp.cc
- src/interp.h
- src/opcode.cc
- src/opcode.def
- src/tools/spectest-interp.cc
- src/tools/wasm-interp.cc
We already used `interp` in a few places, may as well be consistent.
> Rename interpreter -> interp everywhere

- src/interp.cc
- src/interp.h
- src/tools/spectest-interp.cc
- src/tools/wasm-interp.cc
* Move `Thread::Run*` functions into `Executor`. The executor abstracts
over any execution, which will allow us to simulated multi-threaded
execution (which would be awkward to implement with an API on the
Thread object).
* Add `ExecResult` type which wraps an `interp::Result` and the results
from the function. There are too many things called `Result` now, so
perhaps some should be renamed. Not sure what to call them though.
* Expose some of the low-level functionality of `Thread` as public
member functions. This means that it is possible to get `Thread` into
an invalid state, but IMO that's OK since the assumption is that you
know what you're doing if you use the `Thread` API.
* Simplify value_stack and call_stack to use array indexes instead of
pointers.
* Remove the …
> Refactor interpreter execution

- src/wast-parser.cc
- test/regress/regress-17.txt
After the switch to the recursive descent parser, this wasn't properly
being set. As a result, certain errors would not have a proper location.
> Set the `loc` member in `Const`

- src/wast-parser.cc
- src/wat-writer.cc
- test/dump/atomic.txt
- test/interp/atomic-load.txt
- test/interp/atomic-rmw-add.txt
- test/interp/atomic-rmw-and.txt
- test/interp/atomic-rmw-cmpxchg.txt
- test/interp/atomic-rmw-or.txt
- test/interp/atomic-rmw-sub.txt
- test/interp/atomic-rmw-xchg.txt
- test/interp/atomic-rmw-xor.txt
- test/interp/atomic-store.txt
- test/interp/logging-all-opcodes.txt
- test/interp/tracing-all-opcodes.txt
- test/parse/expr/atomic-align.txt
- test/parse/expr/atomic.txt
- test/parse/expr/bad-atomic-unnatural-align.txt
- test/parse/module/bad-import-table-shared.txt
- test/parse/module/bad-memory-shared-nomax.txt
- test/parse/module/import-memory-shared.txt
- test/parse/module/memory-shared.txt
- test/roundtrip/fold-atomic.txt
- test/typecheck/bad-atomic-type-mismatch.txt
This used to be `(shared <min> <max>)` and is now `<min> <max> shared`.
See https://github.com/WebAssembly/threads/pull/74.
> Change shared memory text syntax

- src/generate-names.cc
- test/regress/regress-18.txt
The name generation pass was adding an entry to the function binding
hash, but using the import index instead of the function/global/etc.
index. As a result, subsequent lookups would return the wrong function.
In this case, it would cause the wat folding code to use a function with
the wrong number of parameters.
> Fix bad folding w/ imports and generating names

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-writer.cc
- src/ir.h
- src/resolve-names.cc
- src/validator.cc
- src/wast-parser.cc
- src/wast-parser.h
- src/wat-writer.cc
- test/dump/callindirect.txt
- test/dump/no-canonicalize.txt
- test/interp/callindirect.txt
- test/interp/logging-all-opcodes.txt
- test/interp/tracing-all-opcodes.txt
- test/link/table.txt
- test/parse/expr/callindirect-named.txt
- test/parse/expr/callindirect.txt
- test/roundtrip/fold-call.txt
- test/roundtrip/generate-func-type-names.txt
- test/roundtrip/generate-some-names.txt
- test/spec/call_indirect.txt
- test/spec/imports.txt
- test/spec/return.txt
- test/typecheck/bad-call-result-mismatch.txt
- test/typecheck/bad-callindirect-func-type-mismatch.txt
- test/typecheck/bad-callindirect-type-mismatch.txt
The `call_indirect` instruction now allows the type to be specified
inline or via the common "type use" syntax (or both):
```
call_indirect (type $t1) ...
call_indirect (param i32 f32) (result f64) ...
call_indirect (type $t2) (param i32) ...
```
This means that `CallIndirectExpr` changes from storing a `Var` (the
referenced func type) to a `FuncDeclaration`, which can store both a
type use and a function signature. Most of the changes here are fallout
from that change.
The other major change is that function signature resolution and error
checking now needs to iterate over a functions expr list looking for
`call_indirect` instructions. I'm not sure if this is a significant
overhead in parsing/validation yet, but there are plenty of ways to
optimize it if it ends up in profiles.
> Update testsuite; call_indirect has new syntax

- src/type-checker.cc
- test/spec/br_table.txt
- test/spec/unreached-invalid.txt
When I refactored the type-checker to produce nicer error messages, I
forgot to handle this error:
```
(block
(block (result f32)
i32.const 0
br_table 0 1 ...
```
The label signatures are inconsistent, which is invalid. The
type-checker was returning the proper result (error) but wasn't printing
an error message.
Fixes #670.
> Fix error message w/ inconsistent br_table labels

- demo/wat2wasm/demo.js
Enabling this options allows better debugging in latest Firefox and Chrome.
> #675 Enable "write_debug_names" option in WAT2WASM online demo

- CMakeLists.txt
- src/binary-reader-objdump.cc
- src/binary-writer-spec.cc
- src/filenames.cc
- src/filenames.h
- src/test-filenames.cc
- src/tools/wat2wasm.cc
- test/run-tests.py
This involves deriving the output filename from the input
filename when none is otherwise specified.
Also split out filename handling utilities and add unittests
for them.
> wat2wasm: Always write output to a file

- src/wabt.post.js
`WasmModule#lexer` property can be `null` in `readWasm()`.
> add missing check in libwabt.js

- src/wat-writer.cc
- test/binary/invalid-name.txt
We should add a way to express all names that are valid in the binary
format in the text format. Until then, it's better to be able to
produce a valid `wat` file.
See issue #685.
> Replace invalid characters with `_` in wat-writer

- src/binary-reader-interp.cc
- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/common.h
- src/interp.cc
- src/ir.cc
- src/ir.h
- src/opcode.cc
- src/opcode.def
- src/opcode.h
- src/prebuilt/wast-lexer-gen.cc
- src/stream.h
- src/wast-lexer.cc
- src/wast-parser.cc
- src/wast-parser.h
- src/wat-writer.cc
- test/parse/expr/bad-const-type-i32-in-non-simd-const.txt
- test/parse/expr/bad-const-v128-nat-expected.txt
- test/parse/expr/bad-const-v128-nat-overflow.txt
- test/parse/expr/bad-const-v128-type-i32-expected.txt
- test/parse/expr/const.txt
- test/parse/func/bad-local-binding-no-type.txt
- test/parse/func/bad-local-binding.txt
- test/parse/func/bad-param-binding.txt
This is an initial PR for Wabt simd support to get some early feedback.
This PR only implement the v128.const instruction.
It will construct a simd 128-bits const.
The expected wat format is:
v128.const i32 0x00000000 0x11111111 0x22222222 0x33333333
For simplify, this PR only implement the wat2wasm and wasm2wat functions.
The following PRs will implement the full functions in Wabt.
such as: Interp, objdump, logging, etc....
>    Wabt simd v128.const instruction initial PR:

- test/run-interp.py
- test/run-objdump.py
- test/run-roundtrip.py
Currently run-interp.py doesn't recongize --enable-simd flag in test file.
This PR add SIMD suppor in run-interp.py/run-objdump.py/run-roundtrip.py.
> Add SIMD suppor in run-interp.py/run-objdump.py/run-roundtrip.py

- src/binary-reader-interp.cc
- src/binary-reader-logging.cc
- src/binary-reader-objdump.cc
- src/interp.cc
- src/interp.h
- src/ir.cc
- src/validator.cc
- test/interp/simd-basic.txt
This is a sequential PR of Wabt simd v128.const instruction initial PR (096f7ab84749b5725a5780671111434c34cc17ea)
The PR implement wasm interp, objdump and validate functions for v128.const.
> Wabt simd v128.const instruction PR (Part 2):

- src/ir.cc
- src/ir.h
- src/wat-writer.cc
- test/regress/regress-19.txt
The `(import...` syntax doesn't allow for inline exports, but the wat
writer assumed that all exports would be written inline, so the exports
would be omitted.
This CL fixes it by writing the exports normally:
```
(module
(import "foo" "bar" (func))
(export "baz" (func 0))
)
```
It is also possible to fix this by writing the imports inline, but this
is not currently supported by the .wat writer:
```
(module
(func (export "baz") (import "foo" "bar"))
)
```
> Fix bug when writing inline exports for import

- src/tools/wasm2wat.cc
- src/wat-writer.cc
- src/wat-writer.h
- test/help/wasm2wat.txt
- test/roundtrip/inline-import-export.txt
- test/roundtrip/inline-import-func.txt
- test/roundtrip/inline-import-global.txt
- test/roundtrip/inline-import-memory.txt
- test/roundtrip/inline-import-table.txt
- test/run-roundtrip.py
Inline imports are more flexible than regular imports, since they can be
combined with inline exports. For example:
```
(func (export "baz") (import "foo" "bar") (param i32))
```
> Add WatWriter option for inline imports

- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/common.h
- src/tools/wasm-link.cc
- test/binary/linking-section.txt
- test/link/function_calls.txt
- test/link/function_calls_incremental.txt
- test/link/globals.txt
- test/link/incremental.txt
- test/link/large_code_section.txt
- test/link/names.txt
- test/link/names_import_only.txt
- test/link/names_import_only_module_env.txt
- test/link/table.txt
Add support for init function in linking metadata
Also remove support for DataAlignment which was removed
from the "spec" (Linking.md) and only output DataSize
if its non-zero.
> Add support for init function in linking metadata

- src/binary-writer-spec.cc
- src/tools/spectest-interp.cc
This is useful to determine what the signature of the action's function
was. Without this, it is impossible to tell the difference in function
signature between these two functions:
(func $f1 (param i32) (result i32) ...)
(func $f2 (param i32) ...)
Because they have the same parameter list, and the result is discarded:
(invoke "f1") (i32.const 1)
(invoke "f2") (i32.const 1)
> Always write expected action types in .json output

- .travis.yml
- src/string-view.cc
The Travis image was updated recently (blog says Dec 12th), which
updates clang to 5.0.0.
> Use default clang install on travis for ubsan

- src/binary.h
- src/common.h
- test/binary/bad-duplicate-subsection.txt
- test/binary/bad-function-names-too-many.txt
- test/binary/bad-name-section-invalid-index.txt
- test/binary/bad-name-section-location.txt
- test/binary/bad-names-duplicate-locals.txt
- test/binary/bad-names-duplicates.txt
- test/binary/bad-names-function-locals-out-of-order.txt
- test/binary/bad-names-locals-out-of-order.txt
- test/binary/bad-names-out-of-order.txt
- test/binary/bad-subsection-out-of-order.txt
- test/binary/bad-subsection-size.txt
- test/binary/bad-subsection-unfinished.txt
- test/binary/duplicate-names.txt
- test/binary/invalid-name.txt
- test/binary/linking-section.txt
- test/binary/names.txt
- test/binary/no-global-names.txt
- test/gen-wasm.py
This is easier to read and handles the byte length automatically.
> Use `section` in gen-wasm tests for subsections

- src/interp.cc
SIMD neg are unary instructions and at wrong place in Disassemble() in interp.cc, This
Fix move them to the right place.
> Fix for SIMD i8x16.neg / i16x8.neg / i32x4.neg / i64x2.neg implementation. (#723)

- src/binary-reader-objdump.cc
These relocations point to function index space so we
can print the name of the function here.
> Print symbol names when dumping table relocations

- src/wabt.post.js
Seems that some of the library functions are no longer exported by default. This PR should fix their uses in `wabt.post.js` by calling them directly.
> Fixes for building libwabt.js with latest Emscripten

- src/binary-writer-spec.cc
- src/binary-writer-spec.h
- src/emscripten-helpers.cc
- src/tools/wast2json.cc
`WriteBinarySpecScript` writes a JSON file and its associated module
files (either `.wasm` or `.wat` files). The previous API wrote directly
to the filesystem, but it is more useful to allow the caller to specify
where to write the output instead.
The function now provides a callback `WriteBinarySpecStreamFactory`,
which takes a filename as parameter and returns a `Stream` to write to.
There is also a convenience function that will write the results to a
vector of filename/MemoryStream pairs.
> Use Streams in the WriteBinarySpecScript API

- src/common.h
- src/validator.cc
- test/parse/module/bad-memory-shared-nomax.txt
- test/parse/module/import-memory-shared.txt
- test/parse/module/memory-shared.txt
- test/typecheck/bad-no-shared-memory.txt
Shared memory is only allowed with the `--enable-threads` flag.
> Don't allow memory to be shared by default

- src/binary-reader-ir.cc
- src/common.h
Only when exceptions are enabled via the CMake `WITH_EXCEPTIONS` option.
See issue #760.
> Add try/catch around calls to reserve

- src/wat-writer.cc
Since ExprVisitor is non-recursive, this will allow modules with deeply
nested blocks to be written.
See issue #752.
> Use ExprVisitor in WatWriter

- src/binary-reader.cc
This matches the spec (and the existing code which already exists
in this file for export kind).
> Use uint8 when reading import kind

- src/binary-reader.cc
- src/binary-writer.cc
- src/common.h
- test/binary/bad-function-param-type.txt
- test/binary/bad-function-result-type.txt
These seems to match what is in the spec where these values
are specified as single type terminals.
See: https://webassembly.github.io/spec/core/binary/types.html
> Match value type enum to spec values and read/write as uint8_t

- src/binary-writer.cc
We already have a bunch of module-specific members so this
class is already only single-use anyway.
> Refactor BinaryWriter so the module being written is a member

- src/binary-writer.cc
- test/dump/relocations.txt
This is so that relocations can refer to the symbol table
entries.  The Linking.md spec will soon be updated to
reflect his requirement.
> Write linking metadata before relocations

- src/config.h.in
Remove _Check_Return_ annotation on Windows because that annotation must be a prefix to the function not a suffix which was breaking the code analysis on binary-reader.cc.
Couldn't find a way to reconcile clang/gcc/msvc to all use a prefix or suffix for that annotation, furthermore it is not used a lot in the project anyway.
> Windows warn unused annotation build break

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-writer.cc
- src/c-writer.cc
- src/generate-names.cc
- src/ir.cc
- src/ir.h
- src/wast-parser.cc
- src/wat-writer.cc
- test/regress/regress-20.txt
Since the binary format stores locals as Type+Count pairs, it is easy to
generate a function with a huge number of locals. The text format has
no way to compress this, so the resulting file will be huge.
However, if the binary file has an error, it would be useful to be able
to catch it without allocating a huge number of locals.
To do so, we store all locals as Type+Count pairs in the IR as well, and
provide accessor functions for getting the number of local types, the
type of a particular local index, etc.
This fixes issue #819.
> Store local types as Type+Count pairs

- src/binary-reader.cc
- test/binary/bad-subsection-size.txt
See https://github.com/WebAssembly/wabt/issues/760 for more info.
We assume that a count precedes a list of items that are at least one
byte that are all contained in the same section. As a result, we can do
an up-front check to prevent over-allocation. This is the same technique
that the spec interpreter uses.
> Use `ReadCount` function in BinaryReader

- src/binary-reader.cc
- test/binary/bad-simd-type.txt
- test/gen-wasm.py
> Don't allow the `v128` type without the simd flag

- src/tools/wasm2c.cc
- test/wasm2c/bad-enable-feature.txt
None of the feature flags are currently supported. Fixes issue #823.
> Error on running wasm2c with `--enable-*` flags

- src/binary-reader-ir.cc
- src/binary-reader.cc
- src/binary-writer.cc
- src/ir.cc
- src/ir.h
- test/binary/bad-function-local-count.txt
Also clean up `LocalTypes` a bit, so we can ensure that `decls_` never
has a count of 0.
Fixes issue #826. Thanks for finding @opticaliqlusion!
> Don't allow a local decl count of 0

- src/wat-writer.cc
- test/parse/expr/bad-simd-shuffle-lane-index-overflow.txt
- test/parse/expr/bad-simd-shuffle-nat-expected.txt
- test/parse/expr/simd.txt
When converting v128.shuffle from wasm format to wat format, the '$' char
must be removed as the const value in v128.shuffle instruction expects
a valid simd v128 const format,
i.e. 0xXXX 0xXXX 0xXXX 0xXXX or Int32 Int32 Int32 Int32
otherwise it will encounter errors when converting
v128.shuffle from wat format back to wasm format again.
> Fix one bug for converting v128.shuffle from wasm format to wat format.

- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/tools/spectest-interp.cc
- src/tools/wasm-interp.cc
- src/tools/wasm-validate.cc
- src/tools/wasm2c.cc
- src/tools/wasm2wat.cc
- test/binary/ignore-custom-section-error.txt
- test/help/wasm-validate.txt
- test/help/wasm2wat.txt
If a wasm engine fails to parse a custom section, it must not be an
error. In wabt we often won't want to continue if a custom section can't
be parsed, but it still may be useful to be able to continue.
This change adds a new flag `--ignore-custom-section-errors` to
`wasm2wat` and `wasm-validate`, which will partially parse a custom
section with errors. This could lead to some strange behavior (partially
completed data structures), but generally should be safe to do.
See issue #378 and the discussion on pull #830 for more info.
> Add flag to ignore errors in custom sections

- src/binary-reader.cc
- test/binary/ignore-custom-section-error-objdump.txt
- test/binary/ignore-custom-section-error-wasm2wat.txt
If the `stop_on_first_error` flag was set, it would still stop
reading the wasm file, even if `--ignore-custom-section-errors` flag was
set.
Fixes issue #836.
> Fix bug with --ignore-custom-section-errors flag

- src/interp.h
Slightly OCD perhaps, fixes minor inconsistencies in the interpreter header.
> Use named offset type and clean up PushRep doc

- src/binary-reader.cc
- test/binary/bad-too-many-locals.txt
The maximum number of locals in a function is 2**32-1.
> Fix integer overflow w/ too many locals

- .appveyor.yml
- scripts/appveyor-after-test.bat
- scripts/sha256sum.py
* Create the artifacts before they are packaged (`before_deploy` happens
afterward)
* MacOS doesn't have sha256, so use python
> Some fixes for binary releases

- CMakeLists.txt
- src/config.h.in
This was recently changed in emscripten.
> [emscripten] Use long instead of int for ssize_t

- src/interp.cc
With these changes, when my host function returns `interp::Result::TrapHostTrapped`, execution traps as desired.
By the way, great work on wabt! Useful tools!
> handle traps in host functions

- CMakeLists.txt
- src/test-interp.cc
The previous change fixed a bug that occurs if a host function traps.
This change adds a test for that case, both for when the host function
is called directly and via `call_indirect`.
> [interp] Add test for trapping host functions

- src/binary-reader-interp.cc
- src/common.h
- src/interp.cc
- src/interp.h
- src/test-interp.cc
- src/tools/spectest-interp.cc
- src/tools/wasm-interp.cc
- test/spec/imports.txt
Importing from host modules used to be handled by a delegate, which is a
powerful enough solution to allow for all host import behaviors, but
makes the common case difficult and clunky.
It also assumed that every imported function/global/etc. needed to be
newly created and added to the environment, which is OK (though
wasteful) for functions, but is incorrect for mutable values like
memories and globals.
This change simplifies the common case by providing a set of functions
on `HostModule` that can be used to add exports, e.g.
AppendFuncExport("add", {{Type::I32, Type::I32}, {Type::I32}},
AddFunc);
A generic interface for functions is provided as well, to allow for
automatically generating functions as needed. This is currently used for
functions like "host.print" in `wasm-interp`.
> [interp] Simplify host module imports

- src/validator.cc
- test/dump/setglobal.txt
- test/parse/expr/setglobal-named.txt
- test/parse/expr/setglobal.txt
- test/regress/regress-21.txt
- test/roundtrip/fold-getset-global.txt
- test/roundtrip/generate-global-names.txt
There is a spec test for this, but spectest-interp only runs the
validator in `binary-reader-interp.cc`, which is different than the
validator in `validator.cc`. This is necessarily so, since some
checks only make sense when the module is linked or instantiated.
This fixes issue #894.
> Fix: set_global on immutable global is invalid

- src/interp.cc
At the end of Executor::RunFunction(), the Thread is Reset() so that
the Executor can be reused for subsequent RunFunction()s. However in
some cases the execution won’t make it that far in RunFunction() —
for example, if a HostModule’s callback throws an exception. Move the
call to the Thread’s Reset() to the start of RunFunction() so that
the Thread’s state is always as expected when Executor starts a function.
> Reset Executor’s Thread at start of RunFunction

- man/wat-desugar.1
- src/tools/wat-desugar.cc
- test/help/wat-desugar.txt
These were long supported in `wasm2wat`
> Add `--inline-{im,ex}ports` flags to `wat-desugar`

- src/interp.cc
- src/resolve-names.cc
- src/type-checker.cc
- src/validator.cc
- src/wast-parser.cc
- test/parse/expr/block-multi-named.txt
- test/parse/expr/if-multi-named.txt
- test/parse/expr/loop-multi-named.txt
- test/spec/if.txt
- test/spec/multi-value/block.txt
- test/spec/multi-value/br.txt
- test/spec/multi-value/call.txt
- test/spec/multi-value/call_indirect.txt
- test/spec/multi-value/fac.txt
- test/spec/multi-value/func.txt
- test/spec/multi-value/if.txt
- test/spec/multi-value/loop.txt
- test/spec/multi-value/type.txt
- test/spec/unreached-invalid.txt
- test/update-spec-tests.py
Running the multi-value spec tests found a few bugs:
* DropKeep needs to copy the kept values backward when the regions
overlap.
* Type names need to be resolved to indexes in block declarations
(e.g. `block (type $foo)`)
* `if` without an `else` is valid, it just behaves as though the `else`
is empty, which will pass the params through as results.
* When validating function signatures, we need to also check block
declaration signatures.
* Split `ResolveFuncType` into two functions:
`ResolveFuncTypeWithEmptySignature` and
`ResolveImplicitlyDefinedFunctionType`.
* When resolving implicitly defined function types, we only create an
implicit function type when the type is not inlinable; i.e. only for
block/loop/if with 0 or 1 result values and no params.
* Change `update-spec-tests` to …
> Fix some multi-value bugs; run spec tests

- CMakeLists.txt
- src/binary-reader-interp.cc
- src/config.h.in
- src/interp.cc
- src/opcode-code-table.c
- src/opcode-code-table.h
- src/opcode.cc
- src/opcode.h
- test/interp/basic-logging.txt
- test/interp/basic-tracing.txt
- test/interp/logging-all-opcodes.txt
- test/interp/tracing-all-opcodes.txt
`Opcode::FromCode` calculated the opcode given a prefix/code pair by
using lower_bound over the list of all `OpcodeInfo`s. This was happening
for every instruction, which is incredibly slow.
Since the interpreter's format is internal only, we can use any encoding
we want, so it's simpler and faster to use the `Opcode::Enum` directly
without calling `Opcode::FromCode`.
`Opcode::FromCode` is also used when reading a binary file, so it should
be optimized anyway. Instead of using the `infos_` table, which is
indexed by the opcode's `enum_` value, we create a new
statically-defined table that maps from prefix-code pair to its enum
value.
Unfortunately, this can't be done easily in C++ because it does not
currently support designated array initializers, so this table is
created in a C file …
> Optimize interpreter and `Opcode::FromCode`

- src/tools/wasm-interp.cc
- test/interp/run-non-func-export.txt
The `--run-all-exports` flag assumed that all exports are functions.
> [wasm-interp] Fix assert with non-func exports

- .appveyor.yml
- CMakeLists.txt
`wabt-unittests` used to be installed, but it really shouldn't be.
Also use `cmake_parse_arguments` to make the `wabt_executable` function
a little more powerful.
> Don't install wabt-unittests; refactor CMakeLists

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-reader.cc
- src/binary-writer.cc
- src/generate-names.cc
- src/ir.cc
- src/ir.h
- src/resolve-names.cc
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
- test/desugar/basic.txt
- test/dump/bulk-memory.txt
- test/parse/expr/bulk-memory-disabled.txt
- test/parse/expr/bulk-memory-named.txt
- test/roundtrip/apply-global-names.txt
- test/roundtrip/bulk-memory.txt
- test/roundtrip/fold-bulk-memory.txt
- test/roundtrip/fold-call.txt
- test/roundtrip/generate-bulk-memory-names.txt
- test/roundtrip/generate-func-names.txt
- test/roundtrip/generate-func-type-names.txt
- test/roundtrip/generate-some-names.txt
- test/roundtrip/inline-export-table.txt
- test/typecheck/bad-bulk-memory-invalid-segment.txt
- test/typecheck/bad-bulk-memory-no-memory.txt
- test/typecheck/bad-bulk-memory-no-table.txt
- test/typecheck/bad-bulk-memory-type-mismatch.txt
* Allow for names in data/elem segments:
```
(data $foo (i32.const 0) "abcdef")
```
* These names can be referenced by the memory/table instructions that
operate on segments:
```
memory.drop $foo
```
* Fix running wasm-objdump with bulk-memory instructions
* Check for valid data/elem segments in validation
* Check that bulk-memory is enabled when parsing text
Partial fix for #928; still needs interpreter checks too.
> Add more bulk memory tests; use vars for segments  

- CMakeLists.txt
- src/binary-reader.cc
- src/error.h
- src/leb128.cc
- src/leb128.h
- src/opcode.cc
- src/opcode.h
- src/test-binary-reader.cc
- test/binary/bad-opcode-prefix.txt
- test/binary/bad-opcode.txt
- test/spec/data.txt
- test/spec/elem.txt
- test/spec/func_ptrs.txt
- test/spec/globals.txt
It's easy to forget to add a check for unexpected opcodes, and it's
tedious to have to write additional tests in `test/binary/*`.
This way we can test all potentially disabled instructions at once.
> Add test for disabled opcodes in binary reader

- src/validator.cc
- test/regress/regress-22.txt
The `call_indirect` instruction can take a type use, but can also take
an explicit signature:
```
call_indirect (type $foo)               ;; type use
call_indirect (param i32)               ;; explicit signature
call_indirect (type $bar) (result f32)  ;; both
```
These type signatures must match, or the wat file is considered
malformed. This was properly checked in the spec tests, because it
was performed in a separate function `wabt::ValidateFuncSignatures`.
This wasn't validated in `wat2wasm`, because it performs the full module
validation via `wabt::ValidateModule`, which doesn't share code with
`ValidateFuncSignatures`.
It might be a good idea to share the code between these two, but for now
it's enough to fix this bug by performing the same check in the module
validation path.
Fixes …
> Check type use vs. explicit sig. in call_indirect

- src/wast-parser.cc
- test/regress/regress-23.txt
Without this fix, some validation errors will not display the location
properly.
> Set `end_loc` in folded `if` expressions

- README.md
Apparently some systems have trouble building using the `Makefile`, but can build using CMake directly (see #951, #822, and others). This will at least give some clues about how to work around the bug.
> Add note about building using Makefile

- src/binary-reader-objdump.cc
- test/dump/simd-basic.txt
- test/dump/simd-binary.txt
- test/dump/simd-bitselect.txt
- test/dump/simd-compare.txt
- test/dump/simd-lane.txt
- test/dump/simd-load-store.txt
- test/dump/simd-shift.txt
- test/dump/simd-splat.txt
- test/dump/simd-unary.txt
Tests shamelessly borrowed with light editing from test/interp.
> Support for SIMD instructions in wasm-objdump

- src/binary-reader.cc
- test/binary/bad-function-count-missing-code-section.txt
- test/binary/missing-code-section-empty-function-section.txt
- test/binary/missing-function-section-empty-code-section.txt
- test/regress/regress-7.txt
If the function section is present, and has a non-zero count, then if
the code section is absent the module should not validate.
If either section is missing, but the count is zero it is OK.
> Handle mismatch in function/code section

- src/binary-reader-objdump.cc
This is way I should have implement it the first time around
> wasm-objdump: Cleanup hanlding of global names from #960

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-writer.cc
- src/c-writer.cc
- src/generate-names.cc
- src/ir.cc
- src/ir.h
- src/resolve-names.cc
- src/wast-parser.cc
- src/wast-parser.h
- src/wat-writer.cc
- test/parse/func/bad-local-redefinition.txt
- test/roundtrip/generate-local-names.txt
- test/roundtrip/generate-some-names.txt
The `BindingHash` object is used to map from a name to an Index, and to
detect multiply-defined names. Since the locals and params use the same
Index space and namespace, they should always have been using the same
`BindingHash`.
> Combine param_binding and local_binding in IR

- man/wasm-interp.1
- man/wasm-objdump.1
- man/wasm2c.1
- man/wasm2wat.1
- man/wat-desugar.1
- man/wat2wasm.1
Before: wasm-objdump [options] filename
After: wasm-objdump [options] file ...
Also document '-h' in wasm-objdump.1
> Fix SYNOPSIS in manpages

- CMakeLists.txt
We shouldn't compile with `-Werror` or `-WX` by default, it is useful
for wabt developers but hostile to users.
Fixes issue #980.
> Add WERROR option to CMake build

- CMakeLists.txt
Some systems don't have python installed, and if they don't build tests,
they won't ever need it.
> Only look for python when building tests

- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- test/binary/dylink-section.txt
- test/binary/ignore-custom-section-error-objdump.txt
- test/binary/ignore-custom-section-error-wasm2wat.txt
- test/binary/linking-section.txt
- test/binary/relocs.txt
Also make explicit when are showing log2 alignment.
We could instead display actual byte alignment (1 << p2align)?
> Update linking metadata version

- src/tools/spectest-interp.cc
- test/spectest-interp-error-count.txt
`spectest-interp` used to return 0 (success) when tests failed, and
non-zero only if the source could not be parsed. It's more useful to
return non-zero if the tests fail too.
Fixes issue #1002.
> Return failed tests count from spectest-interp

- src/config.cc
#992 
[ 49%] Linking CXX static library libwabt.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libwabt.a(config.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libwabt.a(config.cc.o) has no symbols
There's some environmental issues which is not clear with Mac OS X ranlib and empty symbol sources.
If we add a dummy function to config.cc for clang, the ranlib error can be avoided easily with no harm.
> avoid Mac OS X ranlib error

- wasm2c/wasm-rt-impl.c
Addresses:
gcc -I/tmp/wabt/wasm2c -O3 /tmp/wabt/wasm2c/wasm-rt-impl.c -o wasm-rt-impl.o
/tmp/wabt/wasm2c/wasm-rt-impl.c: In function ‘wasm_rt_grow_memory’:
/tmp/wabt/wasm2c/wasm-rt-impl.c:111:3: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
memset(memory->data + old_pages * PAGE_SIZE, 0, delta * PAGE_SIZE);
^~~~~~
/tmp/wabt/wasm2c/wasm-rt-impl.c:111:3: warning: incompatible implicit declaration of built-in function ‘memset’
/tmp/wabt/wasm2c/wasm-rt-impl.c:111:3: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
with gcc (Debian 6.3.0-18+deb9u1).
> Add missing string.h include to wasm-rt-impl.c

- src/binary-reader.cc
- src/binary-writer.cc
- src/binary.h
- test/binary/bad-event-after-export.txt
- test/binary/bad-event-before-global.txt
- test/dump/except.txt
- test/dump/rethrow.txt
- test/dump/throw.txt
- test/gen-wasm.py
The exception section is now a known section with code 13, and is known
as the "Event" section.
The structure of the section has changed too, but I'll fix that in
another PR.
> Add `Event` known section; remove `exception`

- src/binary-reader-objdump.cc
- test/dump/global.txt
The `PrintInitExpr` function falsely treated f64 as a float instead of a double.
The test case `global.txt` also contained the wrong output, namely `0x0p+0` instead of `0x1p+2` for `(f64.const 4)`.
> wasm-objdump: fix f64 init expressions

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
Use `ObjdumpNames` struct to share similar code for mapping indexes to
names.
> Refactor objdump name handling a little

- src/wast-parser.cc
- src/wat-writer.cc
- test/dump/simd-lane.txt
- test/interp/logging-all-opcodes.txt
- test/interp/simd-lane.txt
- test/interp/tracing-all-opcodes.txt
- test/parse/expr/bad-simd-shuffle-lane-index-overflow.txt
- test/parse/expr/bad-simd-shuffle-lane-index-overflow2.txt
- test/parse/expr/bad-simd-shuffle-nat-expected.txt
- test/parse/expr/bad-simd-shuffle-not-enough-indices.txt
- test/parse/expr/simd.txt
The textual (WAT) representation of the vector shuffle immediate argument was
underspecified. Recently, WebAssembly/simd#67 specified
it to be i8x16.shuffle i5 i5 ... i5 (16 times i5), which is what all other
implementations were doing. WABT was reading the shuffle argument as 4 32-bit
hex integers that specified a v128, that is, i8x16.shuffle 0x0 0x0 0x0 0x0.
This PR updates WABT to conform to the updated draft of the SIMD extension.
> Update textual encoding of SIMD vector shuffle to conform to the latest SIMD draft

- src/literal.cc
- src/test-literal.cc
* `ParseHexdigit` allowed `g` as a hex character
* Overflow checking can't just check `old_value > new_value`, that fails
for many cases.
> Fix bugs in integer parsing

- src/tools/spectest-interp.cc
- test/run-spec-wasm2c.py
- test/spec/linking.txt
- test/wasm2c/spec/linking.txt
- test/wasm2c/spec/start.txt
When a module is instantiated, and the start function traps, the
contents of the memory and the table may have been modified. This case
is handled by the `assert_uninstantiable` check in a wast test.
In spectest-interp, assert_uninstantiable would instantiate the module,
but was incorrectly resetting the environment. In run-spec-wasm2c, the
`assert_uninstantiable` tests weren't being run at all. Now the module's
`init` function is run, and it is expected to trap.
> Update testsuite; fix linking spec test

- src/binary-reader-objdump.cc
- test/dump/mutable-global.txt
These currently can only come from the export of a global.
> Add names to locally declared globals.

- src/common.h
Since the purpose of these strings is to display them to the user,
an "error string" is a more useful default than an assert, which
would require all callers to consistently check for the range
of valid values (which they didn't).
Tools like wasm-objdump should preferably be able to continue
outputting even in the face of illegal values.
> Made common string lookups more robust.

- src/binary-reader-objdump.cc
- test/dump/debug-names.txt
These names were already displayed on the function section, and when
disassembling a function.
> Print function names on code details too

- src/feature.def
- src/token.def
- src/wast-lexer.cc
- src/wast-parser.cc
- test/help/spectest-interp.txt
- test/help/wasm-interp.txt
- test/help/wasm-validate.txt
- test/help/wasm2wat.txt
- test/help/wast2json.txt
- test/help/wat-desugar.txt
- test/help/wat2wasm.txt
- test/parse/annotations.txt
- test/parse/bad-annotations.txt
Lex custom annotations, but discard them in the parser. In the future we
should be able to parse some of them, but this is simple and
spec-compliant for now.
(Annotations proposal: https://github.com/WebAssembly/annotations)
> Initial custom annotation support

- src/type-checker.cc
- test/dump/reference-types.txt
- test/parse/expr/reference-types-named.txt
- test/parse/expr/reference-types.txt
- test/parse/expr/table-grow.txt
I think the previous order was implemented in Firefox at some point but
it looks like it's since been updated so reversing the order of
operands in `table.grow` matches what the proposed spec text currently
says.
> Update typechecking for `table.grow`

- README.md
The `install` command in the `CMakeLists.txt` file already includes a `bin` destination (see https://github.com/WebAssembly/wabt/blob/master/CMakeLists.txt#L439), so the current readme instructions left me with the binaries in a `.\bin\bin` directory. Updating the README here to remove the unnecessary `bin`.
Also updated the readme to note that CMake (and Ninja) are in the box now with VS (and thus don't need to be installed as a separate dependencies).
Note: VS 2015 is a couple releases old now, so happy to update those instructions to 2019 too if you like :wink:
> Fix INSTALL_PREFIX in README

- src/interp/binary-reader-interp.cc
- test/regress/regress-26.txt
- test/regress/regress-27.txt
- test/regress/regress-28.txt
* i32 init expression in data/elem segments
* Instructions after the last "end" instruction of the function (the
function label has been popped)
Fixes #1089, #1090, #1091
> Fix wasm-interp assertions

- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/tools/wasm-strip.cc
This way you can see the contents of just one custom section by using:
```
wasm-objdump -j section_name -x
```
Where `section_name` is the name of the custom section.
> Match custom section names in wasm-objdump

- src/binary-writer-spec.cc
- src/tools/spectest-interp.cc
The wast file definition for assert_exhaustion looks like:
```wasm
(assert_exhaustion
(invoke "function" (i32.const 132))
"error message")
```
This commit adds the "error message" part to the output.
> Write assert_exhaustion text to JSON file

- src/interp/interp.cc
- src/interp/interp.h
- src/tools/wasm-interp.cc
- test/help/wasm-interp.txt
- test/interp/call-dummy-import.txt
You can now pass `--dummy-import-func` to `wasm-interp`, which will
provide a function that logs the call and returns zero.
> [interp] Add flag to provide dummy import funcs

- src/interp/binary-reader-interp.cc
- test/regress/regress-29.txt
The previous implementation was not properly dropping values on the
stack when performing a return_call or return_call_indirect.
In particular, the "keep count" (i.e. the number of values to keep that
are on the top of the stack) was set properly, but the "drop count" (the
number of values to drop below the keep count), was not.
This fixes issue #1108.
> Fix value dropping bug in return_call

- .appveyor.yml
- src/config.cc
MSVC uses 53-bit precision for the x87 registers by default. In this
mode, it's not possible to properly round a large unsigned 64-bit
integer to a 32-bit float.
As a work-around, we can change the x87 floating-point precision, just
for these functions, and then reset it to the original precision.
A better solution may be to change the floating-point precision for the
entire program, though it's not clear what other effects that may have
on the generated code.
This change also re-enables the Appveyor 32-bit MSVC build.
Fixes issue #1113.
> Fix floating point conversions on MSVC 32-bit

- src/wast-lexer.cc
- test/regress/regress-30.txt
If `char` is signed, then conversion to `int` will keep the sign.
`IsCharClass()` uses this value as an index, so the value must be
unsigned.
Fixes issue #1117.
> Fix assertion in WastLexer::IsCharClass()

- src/config.h.in
Using __builtin_unreachable instead will basically produce undefined
behavior if it is ever reached, which makes it very difficult to debug.
This is perhaps desired for an optimized build, but certainly not for a
debug build.
For now, we'll always convert these to abort().
> Change WABT_UNREACHABLE to call abort()

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/interp/binary-reader-interp.cc
- src/validator.cc
- test/parse/module/global.txt
As per the reference-types spec, ref.null is a constant expression.
I did try to add support for ref.func at the same time, but I didn't really understand the strategy of wabt and reference types; there seems to be strong intertwingliness between func.ref and the element section, whereas it does seem possible for a func.ref to be global.  Oh well, I didn't need it :)
> Add support for ref.null in global initializers

- src/test-wast-parser.cc
- src/tools/spectest-interp.cc
- src/wast-parser.cc
- src/wast-parser.h
- test/regress/regress-34.txt
* Never allow a null options pointer to `ParseWatModule` or
`ParseWastScript`
* Allow a token of type Int or Nat when parsing a simd float const
> Fix some bugs w/ wast2json and SIMD

- src/binary-reader.cc
- src/common.h
- src/type-checker.cc
- test/parse/expr/bad-try-sig-multi.txt
- test/parse/expr/try-multi.txt
- test/typecheck/bad-br_on_exn-mismatch.txt
- test/typecheck/bad-br_on_exn-result-mismatch.txt
In WebAssembly/exception-handling#79 we agreed to rename except_ref
type to exnref.
> Rename except_ref type to exnref

- src/expr-visitor.cc
- test/typecheck/bad-empty-catch.txt
The current visitor does not visit `catch` itself when its body is
empty. So even if the attached test with an empty `catch` body is
supposed to be a validation failure (because an `exnref` value is left
on the stack in the `catch` body), it passed the validator.
In more detail, in the current code,
Input: (should be a validation failure)
```
try
catch   ;; this pushes an exnref value onto the stack
end
```
Output: (wrong, `catch` is missing)
```
try
end
```
Now we correctly visit `catch` even when its body is empty, this test
correctly causes a validation failure.
> Visit catch even when its body is empty

- .flake8
- scripts/travis-build.sh
- src/wasm2c_tmpl.py
- test/gen-spec-js.py
- test/gen-wasm.py
- test/run-roundtrip.py
- test/run-spec-wasm2c.py
- test/run-tests.py
- test/update-spec-tests.py
Seems like flake8 was only run on the scripts directory.
> Run flake8 on the whole repository

- .flake8
- scripts/gen-emscripten-exported-json.py
- scripts/sha256sum.py
- src/wasm2c_tmpl.py
- test/find_exe.py
- test/gen-spec-js.py
- test/gen-wasm.py
- test/run-roundtrip.py
- test/run-spec-wasm2c.py
- test/run-tests.py
- test/update-spec-tests.py
- test/utils.py
pep8 specifies 4 space indentation.  The use of 2 spaces is, I believe,
a historical anomaly where certain large organizations such as google
chose 2 over 4 and have yet to make the switch.
For a project like wabt with little python code I think the cost of
switching is small enough to justify the churn.
> Switch python indentation from 2-space to 4-space

- src/decompiler.cc
Basically copy-pasted from loops, but this is simplest at the moment. I imagine we can extract a "bracketed expression list" pattern, and use that for ifs/loops/etc.
> Decompiler: Recurse into block exprs

- src/decompiler.cc
- src/ir-util.cc
- src/ir-util.h
- src/stream.cc
- src/stream.h
This really de-tangles the code, as in-line assignments are
hard to read.
To make this possible, I had to track the current stack depth, take
into account unreachable paths and a few other support features.
Also added debug output upon assert.
> wasm-decompile: Output Tee as Set+Get instead if possible.

- Makefile
This PR is an attempt to locate Emscripten automatically if it is in path, like when using emsdk, instead of having to set `EMSCRIPTEN_DIR` manually in order to run `make emscripten-release`. Not super important, just stumbled over this while trying to compile libwabt.js in a docker container.
> Attempt to locate Emscripten if EMSCRIPTEN_DIR is not set

- CMakeLists.txt
Without this, running `make test` will fail.
Fixes issue #1149.
> Add wabt-unittests as dependency of run-tests

- src/binary-reader-objdump.cc
- test/dump/func-result-multi.txt
Previously only the first result type was printed, even for multiple results.
This change prints multiple result types in parenthesized form whereas single result types are printed as before.
The `func-result-multi.txt` test case is modified to cover the Type section as well.
> wasm-objdump: Fix type signature for multi-value result types

- CMakeLists.txt
- src/config.h.in
- src/option-parser.cc
- src/option-parser.h
- src/tools/spectest-interp.cc
- src/tools/wasm-decompile.cc
- src/tools/wasm-interp.cc
- src/tools/wasm-objdump.cc
- src/tools/wasm-opcodecnt.cc
- src/tools/wasm-strip.cc
- src/tools/wasm-validate.cc
- src/tools/wasm2c.cc
- src/tools/wasm2wat.cc
- src/tools/wast2json.cc
- src/tools/wat-desugar.cc
- src/tools/wat2wasm.cc
- test/help/spectest-interp.txt
- test/help/wasm-interp.txt
- test/help/wasm-objdump.txt
- test/help/wasm-opcodecnt.txt
- test/help/wasm-validate.txt
- test/help/wasm2wat.txt
- test/help/wast2json.txt
- test/help/wat-desugar.txt
- test/help/wat2wasm.txt
Closes: #1106
Ported versioning system from [Binaryen CMakeLists.txt](https://github.com/WebAssembly/binaryen/blob/dc31b460fef47dfb3415b4ae6276fff4919a03e2/CMakeLists.txt#L10-L23)
```
bin/wasm2c --version
1.0.11-44-g71f883ad
```
Applied to (all) tools in `src/tools/`.
> Add `--version` to wabt tools

- src/binary-reader-objdump.cc
- test/dump/brtable-empty.txt
- test/dump/brtable.txt
Print missing `br_table` immediates
> wasm-objdump: Print `br_table` immediates

- CMakeLists.txt
- src/decompiler-ast.inl
- src/decompiler.cc
- src/ir-util.cc
- src/ir-util.h
This will pave the way for a better multi-pass analysis that
can collect information for the final output pass.
> wasm-decompile: Refactored code to first build an AST.

- src/binary-reader-objdump.cc
- test/dump/import.txt
Adjusts the output of table imports to the output of table declarations and other elements:
- `type` instead of `elem_type`
- limits: `initial` instead of `init`, check `has_max`
> wasm-objdump: Consistent output of table types

- src/interp/binary-reader-interp.cc
- src/interp/interp.h
This change also makes it easier to add an alternative import
resolver that is needed for implementing the C API.
> Remove some used classes/members from the interpreter

- src/binary-reader-objdump.cc
- test/dump/reference-types.txt
> wasm-objdump: Fix output for passive data elem segments

- src/decompiler-ast.inl
- src/decompiler.cc
- test/decompile/basic.txt
- test/decompile/stack-flush.txt
For example: multi-value, and void exps while there are non-void
exps on the stack.
It now uses temp variables instead of pseudo push/pop, as the latter
weren't particularly readable and had an ordering problem that was
hard to make intuitive.
The new system covers all possible situations, generates as few
variables as possible, has clearer comments, and tests.
> wasm-decompile: reworked how "stacky" code gets decompiled.

- src/interp/binary-reader-interp.cc
- src/interp/interp.cc
- src/interp/interp.h
This is needed as part of implementing the C API on top of the
interpreter.
Also remove the trailing `_` to match other struct members in this
file.
Also remove unneeded forward decls.
> interpreter: Move `env` member up to Module base class.

- src/interp/binary-reader-interp.cc
- src/interp/interp.cc
- src/interp/interp.h
- test/interp/reference-types.txt
This requires the type of a global to be distinct from its current
TypedValue contents.
> Allow anyref globals to store ref subtypes

- src/generate-names.cc
- src/generate-names.h
- src/tools/wasm-decompile.cc
- test/decompile/basic.txt
In particular, LLD may stick entire C++ signatures in names, that
WABT then uses with wasm2wat, but are not appropriate for wasm-decompile
function names.
> wasm-decompile: Fixed arbitrary characters appearing in function names.

- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/interp/binary-reader-interp.cc
- src/interp/interp-trace.cc
- src/interp/interp.cc
- src/interp/interp.h
- src/ir.cc
- src/ir.h
- src/tools/spectest-interp.cc
- src/wast-parser.cc
- src/wat-writer.cc
The _bits suffix is used the floating point types where we use types
that differ from the native C types.  For v128 we have a native struct
type that we store and manipulate directly.
Also remove the unneeded bitcast operations.
> Rename v128_bits to simply vec128 since this is stored natively

- src/common.h
- src/interp/binary-reader-interp.cc
- src/interp/interp.cc
- src/interp/interp.h
- src/type-checker.cc
- test/interp/reference-types.txt
Add Hostref type which is an internal subtype of anyref used to
refer to host objects.
Since anyref is an abstract base type it should be be stored directly
on the value stack.  The value stack instead must contain elements of
the concrete RefType enumeration (currently Null, Func, or Foreign).
These changes are needed for the implementation of the C API but are
separately useful for improving conformance with the reftype proposal.
Implement subtyping rules for paramaters and results when using
CallFunction in the interpreter.
> reference-types: Improve reftype support

- src/type-checker.cc
- test/spec/select.txt
- test/typecheck/bad-select-cond.txt
- test/typecheck/bad-select-value0.txt
- test/typecheck/bad-select-value1.txt
The i32 condition variable should be the right-most type in the
error report.
Update bad-select-cond.txt to distinguish the difference and
prevent regression.
> Fix expected stack layout when typechecking select instruction

- src/interp/binary-reader-interp.cc
- src/type-checker.cc
- src/type-checker.h
- src/validator.cc
Tests will follow in the form of the spec tests from the reference-types
repo.
See: #1223
> reference-types: implement type checking for table.get/table.set

- src/tools/wasm-interp.cc
- test/interp/start-failure.txt
We were printing the error message but returning success.
> wasm-interp: Correctly report failure of start function

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/binary.h
- src/common.h
- src/interp/binary-reader-interp.cc
- src/ir.h
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
- test/dump/callindirect.txt
- test/dump/invalid-elem-segment-no-table.txt
- test/dump/invalid-elem-segment-offset.txt
- test/dump/no-canonicalize.txt
- test/dump/reference-types.txt
- test/dump/table-multi.txt
- test/dump/table.txt
- test/interp/logging-all-opcodes.txt
This is in preparation for updating to latest version reference-types
proposal where there is an additional flag and they can be combined.
See: https://github.com/WebAssembly/bulk-memory-operations/issues/98
> Switch to treating segment flags as a bitfield. NFC

- src/interp/interp.cc
I'm not sure how/why I allowed that change to land without the i686
tests passing.
> Fix i686 string formatting issues from #1236

- test/README.md
- test/spec/memory_grow.txt
On windows debug builds these seems to be taking a long time.  Seems
to have gotten worse since #1236 landed.
> Make memory_grow test as slow.

- test/find_exe.py
- test/gen-spec-js.py
- test/run-tests.py
relpath here was failing with on windows when TMPDIR is on a different
drive.  This is because `new_module_filename` lives in the TMPDIR
where and json_dir might be on different drive.
These paths don't get embedded in the final JS anyway because we
embed them directly binary strings so its not important that they are
relative.
> Avoid os.path.relpath in gen-spec-js.py

- CMakeLists.txt
Under windows binaries end with `.exe` and live a the `Debug` or
`Release` subdirectory so we need to use $<TARGET_FILE> to get the
full executable name.
> Fix run-tests target on windows

- .github/workflows/build.yml
- CMakeLists.txt
This adds a basic workflow that builds and tests wabt on all three
desktop platforms.
The plan is to extend this to completely replace travis and appveyor
in the future.
Fixes: #1168
> Initial support for github actions

- src/decompiler.cc
- test/decompile/basic.txt
- test/decompile/stack-flush.txt
- test/run-tests.py
This now outputs memories, globals, tables, and import/export of
these (and functions).
Changed the syntax to be more consistent and refactored how it is
checked.
> wasm-decompile: Output of other sections + import/export.

- .github/workflows/build.yml
- CMakeLists.txt
- Makefile
New `check` target now runs them both.  This allows for github actions to
show unittests and system tests as separate steps.
Also a couple of CMakeLists.txt cleanups:
- Don't use add_definition to add `-fno-exceptions`, this is a C++-only
flag.
- Lowercase the name of the `sanitizer` function.
- Remove opcode.def from list of library input file.  On windows when
building a DLL .def files are assumed to be windows DLL .def files,
which this is not.
This change is split out from #1250
> Split run-unittests out as seperate target

- CMakeLists.txt
- src/common.h
- src/decompiler-ast.h
- src/decompiler-ls.h
- src/decompiler.cc
- src/interp/interp.cc
- test/decompile/loadstore.txt
This tries to make code more readable by summarizing patterns of
load/store ops into "struct" declarations.
Initial version, can probably be improved, but has all essentials
of the idea in place.
> wasm-decompile: Load/Store tracking for struct output.

- src/wast-parser.cc
- test/spec/binary-leb128.txt
- test/spec/bulk-memory-operations/data.txt
- test/spec/bulk-memory-operations/elem.txt
- test/spec/bulk-memory-operations/imports.txt
- test/spec/multi-value/binary.txt
- test/update-spec-tests.py
- test/wasm2c/spec/binary-leb128.txt
This found one bug in the parsing of active elem segments with
uncref style elements.
> Run update-spec-tests.py and add resulting missing tests

- src/interp/binary-reader-interp.cc
- src/type-checker.cc
- src/type-checker.h
- src/validator.cc
- test/spec/reference-types/br_table.txt
- test/spec/reference-types/unreached-invalid.txt
This requires some slighly different validation rules for MVP vs
interface-types.
There is a test in unreachable-invalid.wast that was removed in the
reference-types repo:
type-br_table-label-num-vs-label-num-after-unreachable
This test depends on the old validation rules and still exists in the
master testsuite so we need to continue to support both sets of rules
for now.
> reference-types: add final test: br_table

- src/decompiler.cc
- src/decompiler.h
- src/string-view.h
- src/tools/wasm-decompile.cc
- test/decompile/basic.txt
The code had 3 ways of doing string composition:
- Using + and += on string/string_view
- ostringstream
- wabt::Stream
Of these, the first was by far the most widely used, simply
because decompilation is a hierarchical process, which requires
storing intermediate strings before knowing what surrounds them
(thus unsuitable for streams).
To make the code more uniform, everything was converted to use
the first approach. To not get further performance degradations,
some more efficient concatenation methods were added, that also
work with wabt::string_view.
> wabt-decompile: cleaned up string composition.

- CMakeLists.txt
- src/decompiler-naming.h
- src/decompiler.cc
- src/decompiler.h
- src/generate-names.cc
- src/generate-names.h
- src/tools/wasm-decompile.cc
- test/decompile/basic.txt
The previous implementation was too simplistic, as it didn't do the
renaming at the correct location (such that it can catch all
occurrences), and was also very ineffective in cutting down gigantic
STL signatures to something managable. This version creates more
usable identifiers in almost all cases.
> wasm-decompile: overhauled name filtering.

- src/decompiler.cc
- test/decompile/basic.txt
This outputs some more WABT IR node types with special purpose
syntax, rather than the default catch-all of a function call.
Still incomplete (especially for >MVP), more later.
Reworking br_table will be a seperate PR.
> wasm-decompile: supporting some more node types specifically.

- src/decompiler.cc
- test/decompile/basic.txt
What was before: `block L { STATS }`
is now `{ STATS; label L: }`
or when possible just: `STATS; label L:`
The latter having no indentation at all, and thus automatically
flattening all `br_table` nestings and other common patterns.
It was initially attempted to create a proper switch out of `br_table`,
but the typical LLVM output is so intertwined (with br/br_if jumping
in and out of the br_table targets etc) that a switch could have only
cleanly applied applied to a small subset of cases. The current
simple label flattening works with all wasm code equally, but is a
a bit more low level.
Also rename `break` into `goto`, reflecting what it is really doing.
Though here, `goto` only ever jumps downwards, backwards jumps to the
`loop` construct are still called `continue`.
> wasm-decompile: blocks now represented as labels

- src/test-hexfloat.cc
A `float` cant fit all the values of a `uint32_t` with full precision, since they are the same size. But a `double` has a 52-bit mantissa so it can represent a `uint32_t` with full precision. This fixes the compiler warning in test-hexfloat.cc.
Fixes #1200.
> Fix warning in test-hexfloat.cc

- src/binary-writer.cc
- test/regress/regress-35.txt
TypeIndexLEB relocations (used by call_indirect) doesn't seem to be
supported.
> [wat2wasm] Don't crash on unsupported reloc type

- src/tools/wast2json.cc
- test/help/wast2json.txt
Without this the default was to write the wasm files but not the json.
This matches the behaviour of wat2wasm.
> Add default output name for wast2json

- src/tools/spectest-interp.cc
- test/spectest-interp-invalid-literal.txt
These were being silently ignored previously.
> Report invalid literals when parsing spectest JSON files

- src/decompiler.cc
- test/decompile/basic.txt
- test/decompile/loadstore.txt
- Now has an index that is relative to the type.
- Now detects the common case where the index is shifted to
produce a new base address.
> wasm-decompile: friendlier general load/store ops.

- src/wast-parser.cc
- src/wast-parser.h
- test/parse/expr/bad-brtable-no-vars.txt
- test/parse/module/bad-table-elem.txt
- test/parse/module/table-elem-expr.txt
- test/parse/module/table-elem-var.txt
See #1291. There are two issues:
1. The `(table funcref (elem ...))` syntax did not support elem exprs
2. There was no error produced when the elem var list couldn't be parsed
I also fixed a similar issue with var lists (e.g. `br_table`). There's
another bug with text lists (i.e. list of strings), but it's more
involved so I left TODOs instead of doing it here.
> Fix parse error with table and elem exprs

- test/run-tests.py
Otherwise the new default behavior (as of #1287) is to write the CWD
which we don't want when running tests.
Writing to CWD rather than alongside the input file is deliberate and
desirable and matches the behavior of other compilers such as clang
gcc and wat2wasm.
> Add explicit -o flag to wast2json tests

- README.md
- docs/decompiler.md
- man/wasm-decompile.1
Added a language description, a man page, and some links in the
general readme.
> wasm-decompile: documentation.

- src/decompiler-ls.h
- src/decompiler.cc
- test/decompile/loadstore.txt
If deriving a "struct" from load/store ops fails, the next
best thing is a typed pointer, if all accesses are to the
same type.
Also fixed some precedence related issues.
> wasm-decompile: support for pointers to single types.

- src/binary-reader.cc
- test/binary/bad-data-drop-no-data-count.txt
- test/binary/bad-memory-init-no-data-count.txt
- test/gen-wasm.py
- test/spec/bulk-memory-operations/binary.txt
See #1176. This was working in the spec interpreter because of the way
the segment indexes are handled, but it's better to handle it earlier in
the binary reader.
> Error on memory.init|data.drop without DataCount

- CMakeLists.txt
This allows code completion tools such as clangd to work.  I'm not sure
if there is any downside to enabling this in all cases?
> Add CMAKE_EXPORT_COMPILE_COMMANDS to CMakeLists.txt

- src/decompiler-ls.h
- src/decompiler.cc
- test/decompile/basic.txt
- test/decompile/loadstore.txt
This makes them easier to look up than the large integer
constants LLVM output is full of.
> wasm-decompile: absolute accesses refer to data segments

- src/binary-writer.cc
- src/stream.cc
- src/stream.h
- test/dump/data-count-section-removed.txt
- test/dump/data-count-section.txt
- test/dump/elem-mvp-compat.txt
- test/dump/reference-types.txt
- test/dump/table-multi.txt
- test/spec/bulk-memory-operations/data.txt
- test/spec/bulk-memory-operations/memory_copy.txt
- test/spec/bulk-memory-operations/memory_fill.txt
- test/spec/bulk-memory-operations/memory_init.txt
- test/spec/bulk-memory-operations/table_init.txt
- test/spec/reference-types/br_table.txt
- test/spec/reference-types/data.txt
- test/spec/reference-types/globals.txt
- test/spec/reference-types/memory_copy.txt
- test/spec/reference-types/memory_fill.txt
- test/spec/reference-types/memory_grow.txt
- test/spec/reference-types/memory_init.txt
- test/spec/reference-types/select.txt
- test/spec/reference-types/table_fill.txt
- test/spec/reference-types/table_get.txt
- test/spec/reference-types/table_grow.txt
- test/spec/reference-types/table_init.txt
- test/spec/reference-types/table_set.txt
- test/spec/reference-types/table_size.txt
- test/spec/reference-types/unreached-invalid.txt
See #1189 and #1311. Even if bulk memory is enabled, it can be
convenient to omit the DataCount section for MVP compatibility.
This change only includes the DataCount section when an instruction
requires it; either `data.drop` or `memory.init`. It is also omitted if
there are no data segments.
Rather than doing a second pass on the instructions, this implementation
unconditionally writes the DataCount section, but removes it when it is
not needed. This required adding a function to truncate a stream
(Stream::Truncate).
> Omit the DataCount section unless it is required

- src/binary-reader-objdump.cc
- src/common.cc
- test/README.md
- test/dump/bad-directory.txt
- test/parse/stdin.txt
- test/run-tests.py
This allows tools that read input files to use the special `-` filename
to read from stdin.
Also, improve the error reported in general in ReadFile.
See: #386
> Support reading from stdin in ReadFile

- src/decompiler-naming.h
- test/decompile/basic.txt
- test/decompile/loadstore.txt
This is a fun way to give somewhat meaningful names to sections
containing strings. In the case of pure binary sections this likely
generates random characters, but that's not any worse than the
current generated names.
> wasm-decompile: name data sections with their content

- CMakeLists.txt
- src/config.h.in
- src/option-parser.cc
Add VERSION to project command, which in turn required a cmake
version bump to 3.0.0.
Fixes: #1314
> Remove build-time dependency on git

- docs/decompiler.md
- src/binary-reader-ir.cc
- src/decompiler-ast.h
- src/decompiler-naming.h
- src/decompiler.cc
- src/generate-names.cc
- src/generate-names.h
- src/tools/wasm-decompile.cc
- src/tools/wasm2wat.cc
- test/README.md
- test/decompile/names.txt
- test/run-tests.py
This allows wasm .o files to have more readable names, or even final
linked modules if the linking information is preserved (with e.g.
--emit-relocs in LLD).
This is implemented as part of the WABT IR representation, so
benefits wasm2wat as well.
Named obtained this way are only set for functions if the function
doesn't also have a name in the name section, but is preferred over
the export name if there is one.
> wasm-decompile: use symbols from linking section for names.

- src/decompiler-ast.h
- src/decompiler-naming.h
- src/decompiler.cc
- test/decompile/basic.txt
The decompiler assumes it can define a variable where it is first
assigned to, which works for almost all cases, but occasionally there
is a use of a variable outside of the scope where it was defined.
This detects that case, and makes sure that variable is pre-declared.
> wasm-decompile: escape hatch for variables used outside scope.

- src/option-parser.cc
- src/test-option-parser.cc
- test/too-many-arguments.txt
Don't print the full help message unless we actually ask for it,
but instead suggest `--help` as an option.
Also, print the program name before the error string.
Both these things seem match the GNU utilities I'm used to and I kind
like not seeing and entire screen of help text when I forget an
argument.
> Improve help/usage message on invalid arguments

- .github/workflows/build.yml
This adds some more nuanced triggering for github actions.
> actions: Avoid triggering both branch and pr builds

- CMakeLists.txt
- src/binary-reader-objdump.cc
- src/decompiler.cc
Build fixes to run wabt tools on Cygwin64. I haven't tested it much, but at least it runs DOOM https://github.com/okuoku/freestandoom/issues/2 with the interpreter + WASM C-API :)
- CMakeLists.txt -- Cygwin's libc(newlib) doesn't export POSIX API `fileno` under `-std=c++11`; use `-std=gnu++11` instead.
- binary-reader-objdump.cc: Use proper format string. Using `%lu` here would take some garbage, as argument is `uint32_t`. I guess it can be `PRIu32` but followed other occurrences there.
- (not Cygwin specific) decompiler.cc: Use unsigned `1U`
> Cygwin build fixes

- CMakeLists.txt
- src/binary-reader-objdump.cc
- src/config.h.in
- src/test-hexfloat.cc
Following up #1332 . Enforce standard C++11 in more sane way.
- `binary-reader-objdump.cc` -- it lacked `<strings.h>` to import `strcasecmp` which is not part of standard C++
- Adjust CMake variables to use `std=c++11` everywhere. `CMAKE_CXX_EXTENSIONS OFF` is required to teach CMake 3.1+ not to inject `std=gnu++11` reliably. `_POSIX` on MinGW is no longer required with `_POSIX_C_SOURCE`.
> Use standard C++11 on GNU/Clang compilers

- src/emscripten-exported.json
- src/emscripten-helpers.cc
- src/tools/spectest-interp.cc
- src/tools/wast2json.cc
- src/tools/wat2wasm.cc
- src/wast-parser.cc
Resolving names (i.e. remapping variable names to indexes) is meant to
be part of the parsing process. The spec even considers an unmapped
variable name to be "malformed" text.
This PR moves in that direction, by always running ResolveNames after
parsing text. The next step would be to integrate this more closely with
the parser itself.
> Always run ResolveNames after parsing .wast/.wat

- src/tools/spectest-interp.cc
- src/wast-parser.cc
- test/parse/func/bad-sig-result-type-mismatch.txt
- test/parse/func/bad-sig-result-type-not-void.txt
- test/regress/regress-30.txt
Validating function signatures (i.e. making sure a named function type
matches its explicit signature) really should be parse of text parsing.
Example:
(type $F (func (param i32) (result i32)))
...
(call_indirect (type $F) (param f32) (result i32)  ;; ERROR!
This change doesn't quite get us there, but it's closer. The next step
will be to remove `ValidateFuncSignatures` entirely and perform those
checks in the parser itself.
> Move ValidateFuncSignatures after ParseModuleWat

- src/validator.cc
- src/validator.h
- src/wast-parser.cc
- test/parse/module/reference-types-disabled.txt
The previous PR called the validator function to do this, but now the
code is moved entirely into the parser. This is preferable, since a
mismatching function signature is considered malformed text, not a
validation error.
> Move validation of func signatures into the parser

- CMakeLists.txt
- src/common.h
- src/type.h
This is a good start to cleaning up common.h.
> Move the Type enum to its own file

- CMakeLists.txt
- src/interp/binary-reader-interp.cc
- src/shared-validator.cc
- src/shared-validator.h
- src/type-checker.cc
- src/validator.cc
- src/validator.h
- src/wast-parser.cc
- test/parse/func/bad-result-multi.txt
- test/regress/regress-26.txt
- test/regress/regress-27.txt
- test/spec/bulk-memory-operations/imports.txt
- test/spec/bulk-memory-operations/memory_init.txt
- test/spec/bulk-memory-operations/table_init.txt
- test/spec/call_indirect.txt
- test/spec/globals.txt
- test/spec/imports.txt
- test/spec/local_get.txt
- test/spec/local_set.txt
- test/spec/local_tee.txt
- test/spec/memory.txt
- test/spec/multi-value/call_indirect.txt
- test/spec/mutable-global/globals.txt
- test/spec/reference-types/globals.txt
- test/spec/reference-types/imports.txt
- test/spec/reference-types/memory_init.txt
- test/spec/reference-types/ref_func.txt
- test/spec/reference-types/table_init.txt
- test/spec/reference-types/unreached-invalid.txt
- test/spec/unreached-invalid.txt
The TypeChecker was already shared, but the rest of the other validation
logic was duplicated. This change creates a SharedValidator which is
used by both the Validator and the BinaryReaderInterp classes.
The validator is structured similarly to TypeChecker as a collection of
functions. It's assumed that the functions will be called in the same
order as sections occur in the binary format. The IR valiator does this
too, even though it's possible to validate components out-of-order in
that case.
This change also splits Module validation and Script validation into two
different classes. It should have been written this way in the first
place, and it's nice to do as part of this change since the module
validator logic is mostly moved into the SharedValidator anyway.
Next steps:
* Remove all …
> Share validator between IR + binary-reader-interp

- src/binary-reader-ir.cc
- src/binary-writer.cc
- src/c-writer.cc
- src/decompiler-naming.h
- src/generate-names.cc
- src/ir.cc
- src/ir.h
- src/resolve-names.cc
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
The type section currently only has one form: functions. With the GC
proposal, at least two more forms are added: struct and array. To
facilitate this:
* Rename FuncTypeModuleField -> TypeModuleField
* Rename Module::func_types -> Module::types
* Rename func_type_bindings -> type_bindings
* TypeEntry is added as a base class of FuncType
* TypeModuleField stores a unique_ptr to a TypeEntry
> Add TypeEntry, base class for type section entries

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/interp/binary-reader-interp.cc
- src/ir.cc
- src/resolve-names.cc
- src/shared-validator.cc
- src/shared-validator.h
- src/validator.cc
- src/wast-parser.cc
- test/spec/bulk-memory-operations/table_init.txt
- test/spec/reference-types/table-sub.txt
- test/spec/reference-types/table_init.txt
- test/typecheck/bad-bulk-memory-no-table.txt
The new table-sub test, checks whether the subtyping is handled
properly w/ table.init and table.copy instructions.
The BeginElemSegment callback can't pass the element type anymore, since
it's not known yet. The callback also can't be deferred, since the
BeginElemSegmentInitExpr callback has to happen after the
BeginElemSegment callback, but the reference type is not always known
until after the initializer expression is read. To work around this, I
added a new OnElemSegmentElemType callback.
Other element segment changes:
* The element type must be tracked in the SharedValidator
* A subtle fix: when writing out the segment flags, we need to take into
account whether the element type of the segment is not funcref, even
if there are no element expressions. In that case, we have to use …
> Update testsuite (w/ reference-types changes)

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-objdump.cc
- src/binary-reader-opcnt.cc
- src/binary-reader.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/interp/interp-inl.h
- src/interp/interp-wasm-c-api.cc
- src/interp/interp.cc
- src/shared-validator.cc
- src/token.cc
- src/type-checker.cc
- src/type.h
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
This is similar to the way Opcode is structured, which allows us to hang
member functions off of the enumeration.
The primary motivator for this change is the GC proposal (and the
function-references proposal) where a Type can be parameterized:
(type $T (struct ...))
(func
(local (ref $T)
...
)
In this case the type is ref, with a parameter of the type index. Making
Type a class will make it easier to store this additional information.
> Convert Type from an enum into a class

- CMakeLists.txt
> Set -D_POSIX_C_SOURCE for MINGW only

- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/c-writer.cc
- src/common.h
- src/decompiler.cc
- src/ir.cc
- src/ir.h
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
Const previously stored each value as a union of bit patterns (uint32_t,
uint64_t, v128, etc). It was then extended to support cases where NaN
value (either arithmetic or canonical) was expected.
bool is_expected_nan;
union {
uint32_t u32;
uint32_t f32_bits;
...
ExpectedNan expected;
}
With the SIMD proposal, it's possible for each lane of a f32x4 or f64x2
to be a float or an expected NaN, so this doesn't work anymore. It's
possible to move ExpectedNan out of the union, but it's a bit clumsy to
use properly:
bool is_expected_nan[4];
ExpectedNan expected[4];
union { ... }
Instead, I took this as an opportunity to clean up the class a bit.
First, ExpectedNan is extended to handle the case where it is not a NaN
(i.e. not a not a number), which allows us to remove the bool. Then I
store the …
> Refactor Const struct's internal storage

- src/interp/interp-inl.h
- src/interp/interp.cc
- src/interp/interp.h
- src/test-interp.cc
The interpreter has a garbage colletor (Store::Collect), that *almost*
worked.
In particular, the free list had no fast way to determine whether an
object was used or not. This is necessary when iterating over objects to
actually delete them. This commit adds an `is_free_` vector for this
purpose.
The `Store::Collect` method was also not correct; it was calling
`Store::Mark(Ref)` on each of the GC roots, but that only marks the ref
itself, it doesn't iterate over the Object's references. This commit
updates Collect to iterate over all marked objects iteratively until
steady-state is reached. It's potentially quadratic in the number of
objects as currently written, so there's definitely room for
improvement.
> Fix interpreter garbage collector

- src/binary-reader-logging.cc
- src/binary-reader-objdump.cc
- src/c-writer.cc
- src/common.h
- src/interp/interp-util.cc
- src/interp/interp.cc
- src/interp/istream.cc
- src/ir.h
- src/literal.cc
- src/test-literal.cc
- src/wat-writer.cc
* Add lane getters: u{8,16,32,64}, f{32,64}_bits
* Add lane setters: set_u{8,16,32,64}, set_f{32,64}_bits
* Add set_zero, is_zero
* Add To<Type>() and From<Type>()
These changes will make it easier to build v128 values in the
spectest-interp (which needs to be updated to support SIMD spec tests)
> Move more functionality into the v128 type

- src/binary-writer.cc
- test/dump/elem-mvp-compat.txt
- test/dump/table-multi.txt
- test/spec/bulk-memory-operations/memory_init.txt
- test/spec/reference-types/memory_init.txt
The bulk-memory spec requires that a DataCount section is always
present if a memory.init or data.drop instruction is present in
the following code section. This requirement remains even if the
number of datas is 0, so remove that condition.
Fixes #1368
> Always generate DataCount section, even if number of datas is 0

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/interp/interp-util.cc
- src/ir.h
- src/lexer-keywords.txt
- src/prebuilt/lexer-keywords.cc
- src/shared-validator.cc
- src/shared-validator.h
- src/token.def
- src/type.h
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
- test/dump/array.txt
- test/parse/module/array-mut-field.txt
- test/parse/module/array.txt
- test/parse/module/bad-array-no-fields.txt
- test/parse/module/bad-array-too-many-fields.txt
The following formats are supported:
* (type (array i32))
* (type (array (field i32)))
* (type (array (field (mut i32))))
This PR adds support for reading/writing binary and text, but no
interpreter support yet.
> Parse ArrayTypes

- src/binary-writer.cc
- src/binary.h
- test/binary/bad-event-after-global.txt
- test/binary/bad-event-before-memory.txt
We decided move the event section before the global section in
WebAssembly/exception-handling#98.
> Move event section before global section

- README.md
- docs/wast2json.md
This primarily is documentation for the JSON format produced.
> Add documentation for wast2json

- src/binary-reader.cc
- src/feature.cc
- src/lexer-keywords.txt
- src/prebuilt/lexer-keywords.cc
- src/wast-parser.cc
- test/dump/br_on_exn.txt
- test/dump/rethrow.txt
- test/dump/throw.txt
- test/dump/try-multi.txt
- test/dump/try.txt
- test/parse/func/local-exnref.txt
- test/parse/func/param-exnref.txt
- test/parse/func/result-exnref.txt
- test/parse/module/global-exnref.txt
The exnref type was already supported in the type checker, and other
parts of the code, but there was no way to name the type in the text
format.
This PR also fixes makes binary-reader.cc check for just the
exceptions_enabled flag to enable exnref. The exception-handling
proposal depends on the reference types proposal, but that is now
handled at a higher level, in the `UpdateDependencies` function.
Fixes issue #1388.
> Add exnref value type to parser

- CMakeLists.txt
https://github.com/WebAssembly/wabt/issues/1385
In this PR, I have made python optional in CMakeLists.txt . I have tested locally by bumping the required version to 3.8 which is not existing on my Mac.
I have noticed that the below tests are run from python file - test/run-c-api-examples.py. 
-  c_api_example(callback)
-   c_api_example(finalize)
-   c_api_example(global)
-   c_api_example(hello)
-   c_api_example(hostref)
-   c_api_example(multi)
-   c_api_example(memory)
-   c_api_example(reflect)
-   c_api_example(serialize)
-   c_api_example(start)
-   c_api_example(table)
-   c_api_example(trap)
Do we need to port run-c-api-examples.py to gtest file or cpp file?
> Improve error message when python 3 not available - Fix for  #1385

- src/c-writer.cc
- test/wasm2c/address-overflow.txt
This only occurs when the immediate offset is small (`int` sized). The
stack offset is `u32` and the immediate is an `int`, so the usual
arithmetic conversions converts the result to a `u32`, which wraps the
address before checking for overflow.
There are already spec tests for overflow, but these use an offset of
`4294967295`, which is `long` (at least on LP64 systems). This means
that the sum's type is `u32 + long` which is `long`. This is why the
tests pass. I've added additional tests for these cases here:
https://github.com/WebAssembly/spec/pull/1188
This fixes issue #1400.
> Fix address overflow bug in wasm2c

- src/interp/interp-wasm-c-api.cc
- src/interp/interp.cc
- src/interp/interp.h
- src/test-interp.cc
- src/tools/spectest-interp.cc
- src/tools/wasm-interp.cc
The for experimental WASI implementation I'm working on the WASI
callbacks (implemented as HostFuncs) need to know which module a call is
coming from.  This is because the implicitly operate on the memory of
the calling instance.
This approach seems the match the current convention of passing in the
Thread in `Func::DoCall`.
The purpose here is to allow the HostCall callback to determine from
which instance it is being called.  An alternative approach that I
considered was created different set of WASI HostCall object for
each instance so that instance and its memory we bound to the WASI
functions.
> Pass current Thread to host function callbacks

- src/binary-reader.cc
- test/binary/bad-brtable-too-big.txt
The binary reader tries to allocate a vector for all of the branch
targets, but wasn't checking whether the length was excessively long.
There's already a function to do this: `ReadCount`, which errors out if
the count is longer than the section (this assumes each element requires
at least one byte).
Fixes issue #1386.
> Prevent large allocation in br_table instruction

- src/binary-reader-ir.cc
- test/binary/bad-callindirect-invalid-sig.txt
- test/binary/bad-returncallindirect-invalid-sig.txt
These assertions check to see whether the `sig_index` (i.e. the function
type) are in bounds. But this is the responsibility of the validator,
not the binary reader.
Fixes issues #1413 and #1414.
> Remove range assertions in BinaryReader

- .github/workflows/build.yml
- scripts/travis-before-install.sh
- scripts/travis-build.sh
Also, pin to a specific version.   We were broken today by the flake8 upgrade to 3.8.0.
> Move flake8 CI from travis to github actions

- .gitmodules
- CMakeLists.txt
- src/interp/interp-wasi.cc
- src/interp/interp-wasi.h
- src/interp/interp.cc
- src/interp/interp.h
- src/tools/wasm-interp.cc
- test/help/wasm-interp.txt
- test/run-tests.py
- test/wasi/empty.txt
- test/wasi/exit.txt
- test/wasi/oob_trap.txt
- test/wasi/write_stdout.txt
This is proof of concept that only implements the `proc_exit` API.
Extending this to the full WASI API will to follow assuming this
approach seems reasonable.
Fixes #1409
> Add initial MVP of WASI API support to wasm-interp

- src/interp/interp-wasi.cc
- src/interp/interp-wasi.h
- src/tools/wasm-interp.cc
- test/binary/bad-data-size.txt
- test/interp/start-failure.txt
- test/wasi/oob_trap.txt
We should probably send traving to stderr too but thats a bigger
change.
> Use stderr for reporting errors in wasm-interp

- src/wat-writer.cc
- test/roundtrip/named-locals.txt
- test/roundtrip/named-params.txt
A named parameter (or local) must always be in its own `param` block, so
this syntax is not allowed:
`(param i32 $b i32)`
And must instead be converted to:
`(param i32) (param $b i32)`
> Fix bug when writing grouped named parameters

- src/c-writer.cc
This replaces the explicit list of names to avoid with a simple prefixing
scheme. This is safer as it handles more cases, however, it does make
the code slightly less fun to read. Perhaps there's a nicer prefixing?
Fixes #1426 and with this I can compile a "hello world" program with
`emcc => wasm2c => clang` and it all works :tada:
> Mangle wasm2c names in a simpler way

- .github/workflows/build.yml
This image the the latest one published, and used llvm upstream rather than
fastcomp.
> Update and pin emscripten image used in CI

- src/wat-writer.cc
- test/roundtrip/elem-nonzero-table.txt
- test/roundtrip/generate-bulk-memory-names.txt
- test/roundtrip/table-copy-index.txt
- test/roundtrip/table-init-index.txt
See #1445 and #1443. This writes non-zero table indexes for `table.init`, `table.copy`, and for element segments.
> [wat2wasm] Write table indexes in text format

- src/binary-reader-ir.cc
- src/wat-writer.cc
- test/roundtrip/elem-declare.txt
- test/roundtrip/table-import-externref.txt
* The `declare` keyword should be printed when using element expressions
or element indexes (i.e. flags == 3 or flags == 7).
* An imported table was not properly setting the element type in the IR
Fixes #1448 and #1449.
> [wasm2wat] Fix a few more roundtripping issues

- src/wast-parser.cc
- test/desugar/locals.txt
When a function is specified like this:
(func (type $t) ...)
the type can have any sequence of params and results, but it is not
known what that signature is until it is resolved. However, locals that
are parsed will be given a binding index under the assumption that the
signature is empty, e.g.
(func (type $t)
(local $v0 i32)
(local $v1 i32)
...
)
So `$v0` will have index 0, and `$v1` will have index 1. If it turns out
later that type `$t` has any parameters, then these indexes need to be
updated.
> Update local bindings on function with type use

- CMakeLists.txt
This is a minor change to avoid some misleading output when wabt is used as a subproject via add_subdirectory(); in particular, when used as a depdency via CMake's `FetchContent` command. It's not uncommon for clients in this case to make a shallow git clone, but in these cases, the call to `git describe` code will report a "fatal error". (This is reported as a warning but is nevertheless disconcerting.)
The PR detects whether wabt is the main project or not, and if not, suppresses and warnings about this, on the assumption that the actual main project presumably knows the specific version it has included.
(It might also make sense to change the defaults of BUILD_TESTS and BUILD_TOOLS to off in this case, on the assumption that the main project just wants the library targets, but that's a …
> Improve CMakeLists.txt for when used via add_subdirectory()

- CMakeLists.txt
TL;DR: this makes it simpler and safer for projects including WABT via FetchContent to configure options via the CMAKE_ARGS argument.
Importing projects may want to set (e.g.) BUILD_TESTS to "no". However, this doesn't work without creating an identical option() in the importing in the importing project. Enabling CMP0077 in supported versions of CMake allows importing projects to set default values for the variables without touching the cache.
> Enable CMake policy CMP0077

- src/config.h.in
This is designed to exactly mimic the definition that LLVM uses under MSVC; this allows use of both WABT and LLVM headers in the same codebase without having to work around compilation errors.
> Tweak definition of ssize_t for MSVC compilation

- src/interp/interp-wasi.cc
_Static_assert and _Alignof aren't defined everywhere. Also use PRIu64 format specifier where needed.
> Fix some portability issues in interp-wasi.cc

- src/type-checker.cc
- test/spec/reference-types/br_table.txt
- test/spec/reference-types/unreached-invalid.txt
The reference types proposal originally modified the `br_table` behavior
to only check arity, not the specific types. This was to remove a
subtyping check, but now that subtyping has been removed, we can revert
back to the original (MVP) br_table behavior.
> Revert br_table in reference types proposal

- src/ir-util.cc
- test/roundtrip/fold-reference-types.txt
- test/roundtrip/fold-simd.txt
Also remove default case from `ir-util.cc` so we get compile warnings in
the future.
> Fix folding for *.load_splat and table.fill

- src/ir-util.cc
All enumeration values are handled in the switch, but it's still
possible to produce an invalid value, which would not return.
> Fix gcc warning in GetExprArity

- src/type.h
- cassert for assert
- confing.h for WABT_UNREACHABLE
I think it was working because type.h was only included in common.h,
both cassert and config.h was included prior to including type.h.
> Add missing includes to type.h

- wasm2c/wasm-rt.h
The previous change prevented `WASM_RT_MEMCHECK_SIGNAL_HANDLER_POSIX`
from being defined, but `WASM_RT_MEMCHECK_SIGNAL_HANDLER` was still
defined, which would prevent the memory bounds check.
> Completely disable signal handler on 32-bit

- src/wast-parser.cc
- test/desugar/locals.txt
This was originally landed in 6bff9f0, but was incorrect (the test
didn't even do the right thing!)
The problem was that the local index was correctly being updated, but it
happened _after_ the names had already been resolved. To fix it,
`ResolveFuncTypes` and `ResolveNamesModule` needed be called in that
order. There was an erroneous assertion that fired as a result ("This
should only be run after resolving names"), but that's incorrect -- the
code works properly before resolving names too, since
`Module::GetFuncType` can properly look up function types by name.
Thanks to @alexcrichton for pointing this out.
> Fix resolving local names w/ empty func signatures

- src/decompiler-ast.h
- src/decompiler.cc
- src/tools/wasm-decompile.cc
- test/decompile/basic.txt
It would previously assume the blocktype is "simple" (at most a single result value), but now also supports function signatures.
Also fixed it ignoring the validator result.
> [decompiler] fixed blocks with params.

- src/ir.cc
- test/binary/bad-func-with-struct-type.txt
- test/gen-wasm.py
Function types and struct types share an index space, but a function can
only be defined using a function type.
Since `Module::GetFuncType` already returns `nullptr` for an OOB index,
it makes sense to return `nullptr` for an invalid type too.
> Fix assert when function has struct type

- src/binary-reader.cc
- test/binary/bad-import-kind.txt
Detected by fuzzing against [Fizzy](https://github.com/wasmx/fizzy).
Spectests submission: https://github.com/WebAssembly/spec/pull/1233
> Detect malformed import kind in binary reader

- src/binary-reader.cc
- test/binary/bad-section-code-leb128.txt
The section code is just a single byte, not a LEB128-encoded value.
With this fix the section code is now read correctly with ReadU8().
The issue has been found by fuzzing wabt wasm validation against [Fizzy](https://github.com/wasmx/fizzy).
The wasm spectests reproducing the issue have been submitted to https://github.com/WebAssembly/spec/pull/1230.
> Fix reading of section code

- src/tools/wast2json.cc
`wast2json` ignores some file errors and returns an exit code of `0` even if an error has occurred.
For example:
```
$ wast2json binary.wast -o /nonexistent/binary.json` 
stream.cc:139: unable to open /nonexistent/binary.json for writing
stream.cc:139: unable to open /nonexistent/binary.0.wasm for writing
...
```
reports many errors, but returns with an exit code of `0`.
The reason is that the result values ​​of the `WriteToFile` calls for `json_stream` and `module_streams` are ignored.
> wast2json does not check all file errors

- src/binary-reader-logging.cc
- src/interp/interp-inl.h
- src/interp/interp.cc
- src/interp/interp.h
- src/shared-validator.cc
- src/tools/spectest-interp.cc
- src/wat-writer.cc
Adds a type field to `Value` to verify the right union member is being read.
A Wasm module that has been validated shouldn't need this, but any code reading the wrong value would trigger UB, but still often work (like a uint32_t read from a uint64_t on little endian machine), and mask bugs.
Turning this on found bugs in the PR I just landed (as I suspected) but also in older code.
> Made the interpreter "type-safe" in debug mode

- README.md
Some proposals are enabled by default now, so the README should reflect that. Also, the flag was flipped to disable (rather than enable), so change that here too.
See issue #1513.
> Update README.md to include default-on proposals

- CMakeLists.txt
- src/decompiler-ast.h
- src/interp/interp.cc
I guess maybe we don't do CI with `-Werror` enabled?  We probably
should.
> Fix warnings generated in my system clang (9.0.1-12)

- src/binary-writer.cc
This commit refactors the representations of symbols in the binary writer.  It will allow us to fix #1534 in a followup.
> [NFC] Refactor symbol table creation in binary writer

- src/binary-writer.cc
- test/dump/relocations-block-types.txt
- test/dump/relocations.txt
- test/dump/symbol-tables.txt
Based on #1535.
Instead of adding entries to the symbol table as they are referenced, when writing relocatable binaries, we're going to make symbols for all functions.  This allows exported functions and globals to be written with the proper exported / no_strip flags, so that resulting files will link with wasm-ld.
The current state is that I've only updated the tests in the repo.  However the real difference can be seen if we make a simple wasm file from LLVM:
```
$ cat a.c
void b(void);
__attribute__((export_name("a"))) void a(void) { b(); }
$ clang -Oz --target=wasm32 -nostdlib -c -o a.o a.c
$ wasm2wat -o a.wat a.o
```
The resulting file looks like:
```wat
(module
(type (;0;) (func))
(import "env" "__linear_memory" (memory (;0;) 0))
(import "env" "__indirect_function_table" (table …
```
> Eager symbol tables

- test/dump/relocations-long-func-bodies.txt
- test/dump/relocations-long-func-section.txt
- test/dump/relocations-section-target.txt
PRs #1527 and #1539 needed their test expectations updated after #1537
was merged; this patch does that.  It also renames a test for
consistency.
> Fix up reloc-related tests after #1537

- src/binary-reader.cc
- test/binary/bad-data-invalid-memidx.txt
- test/binary/bad-segment-no-memory.txt
If bulk memory extension is disabled, do not allow memory index in the
data segment other than zero.
> Disallow non-zero memidx when bulk memory disabled

- src/binary-reader.cc
- test/binary/bad-memory-limits-flag-is64.txt
- test/binary/bad-table-limits-flag-is64.txt
- test/interp/load64.txt
- test/interp/store64.txt
- test/parse/expr/atomic64.txt
- test/parse/expr/bulk-memory-named64.txt
- test/parse/expr/load64.txt
- test/parse/expr/store64.txt
- test/roundtrip/bulk-memory64.txt
- test/roundtrip/memory-index64.txt
Fixes regressions in binary reader introduced by the implementation of
the memory64 extension: https://github.com/WebAssembly/wabt/pull/1500.
> Disallow "64-bit" flag if memory64 is disabled

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/common.cc
- src/common.h
- test/dump/relocations-all-features.txt
- test/dump/symbol-tables-all-features.txt
This patch adds a table symbol type and plumbs it through everywhere.
To do:
- The answer here is a bit more straightforward: the initial patch wasn't emitting symtab entries for anonymous definitions.  The test case under consideration did in fact define the table.  The updated patch will emit relocs for all table number references, unless the reference is invalid/broken (the user must have passed --no-check).
Cc @pmatos and @sbc100
> Add --relocatable support for tables

- CMakeLists.txt
I try to compile wabt on Ubuntu 18.04 aarch64 with gcc 7.5.0 and cmake 3.10.2, failed with the error below:
the wabt source code is downloaded from release page v1.0.19 tar package which without the .git dir.
I made a tiny modify to fix this
> Fix compile failed on Ubuntu 18.04 aarch64 cmake3.10.2

- src/binary-reader.cc
- src/interp/interp.cc
- src/interp/istream.cc
- src/lexer-keywords.txt
- src/opcode.cc
- src/opcode.def
- src/prebuilt/lexer-keywords.cc
- test/dump/atomic.txt
- test/parse/expr/atomic-disabled.txt
- test/roundtrip/fold-atomic.txt
- test/typecheck/bad-atomic-type-mismatch.txt
atomic.notify   -> memory.atomic.notify
i32.atomic.wait -> memory.atomic.wait32
i64.atomic.wait -> memory.atomic.wait64
These were renamed upstream a while ago, but the new names were not
added to wabt.
> Rename atomic.notify, *.atomic.wait

- src/wast-parser.cc
- test/parse/expr/bulk-memory-disabled.txt
- test/parse/module/bad-table-no-offset.txt
Text parsing was allowing element segments without an offset expression
even when the bulk memory flag was disabled.
Fixes #1566.
> Element offset expr is required when bulk disabled

- src/wast-parser.cc
- test/spec/func.txt
Fix spec test failure in func.wast
The wasm text format allows the use of a function type to be specified
one of three ways:
```
;; 1. As an explicit type index or symbol
(type 0)
;; 2. As params and results
(param i32) (result i64)
;; 3. Both; an explicit type index, params and results
(type 0) (param i32) (result i64)
```
Options 2 and 3 are text format sugar, since the binary format always
encodes these as an explicit type index.
Option 3 needs to check that the type at that index matches the
explicitly given params and results. Normally checking whether an index
is in bounds is a validation step, not a syntax checking step. However,
in this case if the index is out of bounds, then the types cannot be
checked, so it must be a syntax error.
> Fix func.wast spec test

- CMakeLists.txt
Reference: [Issue#1571](https://github.com/WebAssembly/wabt/issues/1571)
Problem: 
It used to add the debug info in the binary even if below command was used.
```
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ cmake --build .
```
Solution :
Let the cmake add `-g` flag when it is needed.
Test 1: run below command 
```
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ cmake --build .
```
It will generate binary without debug info
Test 2: 
```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
$ cmake --build .
```
It will generate binary with debug info
> Let cmake add "-g" flag when it is needed

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader.cc
- src/binary-reader.h
- src/interp/binary-reader-interp.cc
- src/shared-validator.cc
- src/shared-validator.h
- src/type-checker.cc
- src/type-checker.h
- src/validator.cc
- test/parse/expr/bad-select-multi.txt
- test/spec/reference-types/select.txt
The reference-types proposal adds a select instruction with a type
vector, but any number greater than 1 is invalid.
Fixes #1577.
> Select instr. with multiple results is invalid

- src/binary-reader-objdump.cc
- src/binary-writer.cc
- test/dump/bulk-memory.txt
- test/dump/extended-names.txt
Also fix ordering of data names and table segment names.
> wasm-objdump: Report data segment names

- .gitmodules
uvwasi was transferred into the Node.js GitHub org.
This commit updates the project's source repo.
> update uvwasi repo

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/interp/interp.cc
- src/interp/istream.cc
- src/opcode-code-table.c
- src/opcode.def
- src/opcode.h
- src/type-checker.cc
- src/wat-writer.cc
- test/binary/bad-multiple-catch-all.txt
- test/dump/try-catch-all.txt
- test/gen-wasm.py
- test/typecheck/bad-rethrow-depth.txt
- test/typecheck/rethrow.txt
This PR updates exception handling support to match the most recent spec explainer (see https://github.com/WebAssembly/exception-handling/pull/137). In particular, it fixes the handling of `rethrow`'s depth argument and changes the `catch_all` opcode. Tests are also expanded (with test cases taken from spec issue examples).
> Update rethrow depth handling and catch_all opcode

- src/type-checker.cc
- test/typecheck/bad-delegate-target.txt
- test/typecheck/delegate.txt
This PR fixes an issue with the validation of the `delegate` exception instruction: it was failing to check that the delegate target block was a valid kind of block. It should now follow the clarified behavior of `delegate` from this issue: https://github.com/WebAssembly/exception-handling/issues/146
> Fix checking of delegate target block kind.

- src/wat-writer.cc
- test/roundtrip/fold-block-labels.txt
This PR makes label printing for blocks in folded form more consistent with non-folded forms.
For example, given the following input wat file:
```
(module
(func
block
br 0
end
block
br 0
end))
```
If you do a roundtrip with `wat2wasm` and `wasm2wat` currently, you get different labels depending on if you supplied `--fold-exprs` or not:
Non-folded:
```
(module
(type (;0;) (func))
(func (;0;) (type 0)
block  ;; label = @1
br 0 (;@1;)
end
block  ;; label = @1
br 0 (;@1;)
end))
```
Folded:
```
(module
(type (;0;) (func))
(func (;0;) (type 0)
(block  ;; label = @1
(br 0 (;@1;)))
(block  ;; label = @2    <<---- this is different
(br 0 (;@2;)))))
```
This PR should make both use the same label depths.
> Adjust label printing for blocks in folded form

- src/binary-reader.cc
- test/spec/binary.txt
- test/spec/data.txt
This is an incremental bump of testsuite, the TOT has SIMD tests which won't work yet.
The main fix is for a test added to the spec repo that has an invalid
functype in the type section. Based on the spec, the functype should be
a single byte 0x60. The leb encoding only comes into effect with the GC
proposal.
> Bump testsuite version and fix tests

- src/binary-reader.cc
- src/config.h.in
- src/interp/interp.cc
- src/interp/istream.cc
- src/lexer-keywords.txt
- src/opcode.def
- src/prebuilt/lexer-keywords.cc
- test/spec/simd/simd_i8x16_arith2.txt
We can unskip and rebase simd_i8x16_arith2.txt with i8x16.popcnt implemented.
> [simd] Implement i8x16.popcnt

- test/spec/simd/simd_const.txt
- test/spec/simd/simd_load16_lane.txt
- test/spec/simd/simd_load32_lane.txt
- test/spec/simd/simd_store64_lane.txt
Missed unskipping these in prior implementations. With this, all simd
tests are now running.
> [simd] Unskip more tests

- src/emscripten-exported.json
_free is used in src/wabt.post.js.
> Add _free to list of exports

- Makefile
- README.md
I'm tempted to followup by removing the "Unix Makefile" support
completely from the top level Makefile (users who really prefer that can
still run cmake directly of course).
> Use ninja cmake generator by default

- src/c-writer.cc
Note that all SIMD expressions are untested in wasm2c, since it doesn't support any feature flags yet. I followed existing implementation for other SIMD expressions, like LoadSplat.
> Implement wasm2c for SIMD expressions

- src/binary-reader-ir.cc
- test/roundtrip/debug-names.txt
I noticed we lacked support here while debugging #1651.
> Add more support to extended names section.

- README.md
Add submodule init before CMake commands. gtest and others will fail when running cmake without this.
> Add submodule init to README

- src/resolve-names.cc
- test/dump/try-delegate.txt
- test/parse/bad-delegate-label.txt
This PR has two commits for fixing bugs related to try-delegate labels.
One fixes the printing in certain cases (similar to #1609).
The other fixes the label resolution code. Example from the spec (https://github.com/WebAssembly/exception-handling/blob/master/proposals/exception-handling/Exceptions.md):
```
try $l1
try
call $foo
delegate $l1  ;; (= delegate 0)
catch
...
catch_all
...
end
```
The label `$l1` should resolve to `0` in the delegate target, which is 1 less than how typical block constructs work. The current code mis-resolves this to `1`. It should also error in cases like the following:
```
try $l1
nop
delegate $l1
```
Because it's not possible to represent the label `$l1` in the binary format, as a `try-delegate` cannot target itself.
> Fix resolution of delegate labels

- src/wat-writer.cc
- test/roundtrip/try-delegate.txt
This is similar to a previous bug (#1609) for other kinds of block labels.
The tests check that 2+ adjacent try-delegate blocks will have labels that print correctly.
(split from #1675)
> Fix printing of try-delegate labels

- src/binary-reader.cc
- src/binary-writer.cc
This changes the encoding of the `attribute` field, which currently only
contains the value `0` denoting this tag is for an exception, from
`varuint32` to `uint8`. This field is effectively unused at the moment
and reserved for future use, and it is not likely to need `varuint32`
even in future.
See https://github.com/WebAssembly/exception-handling/pull/162.
This does not change any encoded binaries because `0` is encoded in the
same way both in `varuint32` and `uint8`.
> [EH] Make tag attribute's encoding uint8

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- src/tools/wasm-objdump.cc
- test/dump/section-offsets.txt
- test/help/wasm-objdump.txt
This is useful for working with debug info, which uses section offsets
> Add objdump flag to print section offsets instead of file offsets

- src/interp/interp.cc
The use of `.v` is incorrect, we should simply use array subscript
operator on the Simd type, which takes care of BE systems.
For #1670. (Not using fix as I don't have a BE system to verify.)
> [simd] Fix load/store lanes on BE systems

- src/binary-reader-ir.cc
- test/regress/regress-1674.txt
The alignment value in binary format is log2, so we need to shift it in
binary-reader-ir before it is validated (since validation requires that
it is shifted to be the number of bytes). We correctly did that for some
Simd instructions (like load splat) but did not do it for load/store
lane.
Fixes #1674.
> [simd] Shift alignment_log2 before validation

- src/interp/interp.cc
- src/interp/interp.h
Also remove an unused transform, we are applying the unop f in the for
loop directly after it.
> [simd] Remove unused template params

- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader.cc
- src/binary-reader.h
We have the more specific OnFunctionSymbol, OnGlobalSymbol family
of callbacks that is used by objdump.
> Remove ununsed onSymbol callback. NFC

- src/binary-reader.cc
- src/binary.h
- src/common.h
- test/binary/dylink0-section.txt
- test/gen-wasm.py
This section is now based on sub-sections making it more
extensible.
See also:
llvm change: https://reviews.llvm.org/D109595
binaryen change: https://github.com/WebAssembly/binaryen/pull/4141
> Support new dylink.0 custom section format

- test/update-spec-tests.py
This was removed as part of #1712 but I think it still needs to be here
until simd is actually merge into the main spec repo and no longer
exists as proposal in the testsuite repo.
> Re-enable simd in update-spec-tests.py

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader-opcnt.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/interp/binary-reader-interp.cc
- test/binary/bad-extra-end.txt
- test/binary/bad-op-after-end.txt
- test/interp/basic-logging.txt
- test/regress/regress-28.txt
We already have EndFunctionBody, and this extra distinction
doesn't seem like it is needed.
> Remove separate OnEndFunc vs OnEndExpr.

- src/binary-reader-objdump.cc
This makes thinks a little more precise and is part of
paving the way for extended const/init expressions.
> Refactor init expressions handling in binary-reader-objdump.cc. NFC

- src/interp/binary-reader-interp.cc
- src/interp/interp-inl.h
- src/interp/interp.cc
- src/interp/interp.h
- src/interp/istream.cc
- src/interp/istream.h
- src/opcode.def
- src/shared-validator.h
- src/type-checker.cc
- src/type-checker.h
- test/interp/rethrow-and-br.txt
- test/interp/rethrow.txt
- test/interp/throw-across-frame.txt
- test/interp/try-delegate.txt
- test/interp/try.txt
This PR adds interpreter support for the exception handling proposal.
Details about the implementation approach:
* Try blocks generate metadata tracking the instruction ranges for the handlers and which exception tags are handled (or if a `catch_all` is present). The metadata is stored in a function's `FuncDesc`, and is transferred into the `Frame` when a function call is executed.
* The stack is unwound when a `throw` is executed. This unwinding also handles tag dispatch to the appropriate catch. The metadata to find the matching handler is looked up in the call `Frame` stack.
* If a `try-delegate` is present, it is used in the stack unwinding process to skip over to the relevant handler.
* A separate `exceptions_` stack in call frames tracks caught exceptions that can be accessed via a …
> Add interpreter support for the exception handling proposal

- src/binary-reader-ir.cc
- src/binary-reader-nop.h
- src/binary-reader.h
- src/interp/binary-reader-interp.cc
- src/type-checker.cc
- src/type-checker.h
The name of this argument was recently changed from `func_index`
to `type_index` as part of #1695, but I think that might have been incorrect.
The immediate that read in the binary reader is (IIRC) a function
index:
```
case Opcode::RefFunc: {
Index func;
CHECK_RESULT(ReadIndex(&func, "func index"));
CALLBACK(OnRefFuncExpr, func);
CALLBACK(OnOpcodeUint32, func);
break;
}
```
and not a type index.   Indeed the interpreter seems to treat it
as a function index too:
```
Result BinaryReaderInterp::OnRefFuncExpr(Index func_index) {
CHECK_RESULT(validator_.OnRefFunc(loc, Var(func_index)));
istream_.Emit(Opcode::RefFunc, func_index);
return Result::Ok;
}
```
> OnRefFuncExpr takes a func index. NFC

- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- src/interp/binary-reader-interp.cc
- src/interp/interp.h
- test/opcodecnt/basic.txt
- test/spec/binary-leb128.txt
- test/spec/binary.txt
- test/spec/data.txt
- test/spec/elem.txt
- test/spec/func_ptrs.txt
- test/spec/global.txt
- test/spec/memory64/binary-leb128.txt
- test/spec/multi-memory/binary.txt
- test/spec/multi-memory/data.txt
Rather than spocial casing them in the reader we now use the same
instruction callbacks for instruction that appear in init expressions as
instructions that appear in normal functions.
The result of this change is the validation of init expresions is pushed
further up the stack.  For example, objdump will now quite happily dump
modules that use arbitrary instructions in thier init expressions even
though they are not valid.  To me, this makes sense since objdump does
not do instruction validation elsewhere.
The change is pre-cursor to allowing a wider variety of instruction
to be present in init expressions.
See https://github.com/WebAssembly/extended-const
> Perform init expression validation outside of the binary reader. NFC

- src/binary-reader-ir.cc
- src/interp/binary-reader-interp.cc
- src/interp/interp.h
In #1770 I introduced these (duplicate) checks but it turns
out neither were necessary in the final version of the patch.
> Remove unused checks from #1770. NFC

- src/binary-writer-spec.cc
- src/interp/interp.cc
- src/ir.h
- src/lexer-keywords.txt
- src/prebuilt/lexer-keywords.cc
- src/resolve-names.cc
- src/token.def
- src/tools/spectest-interp.cc
- src/validator.cc
- src/wast-parser.cc
- src/wast-parser.h
- test/gen-spec-wast.py
- test/parse/assert/assertexception.txt
- test/parse/assert/bad-assertexception.txt
- test/spec/exception-handling/binary.txt
- test/spec/exception-handling/exports.txt
- test/spec/exception-handling/imports.txt
- test/spec/exception-handling/rethrow.txt
- test/spec/exception-handling/tag.txt
- test/spec/exception-handling/throw.txt
- test/spec/exception-handling/try_catch.txt
- test/spec/exception-handling/try_delegate.txt
- test/typecheck/bad-assertexception-type-mismatch.txt
- test/update-spec-tests.py
This PR imports the spec tests from the Wasm testsuite repo and adds infrastructure to run them correctly.
* Adds test expectations for exception handling proposal spec tests.
* Adds missing tag signature matching code for import tests.
* Adds support for the `assert_exception` command used in new tests.
* Fix filename normalization for the spec test runner.
> Add specification tests for exception handling proposal

- src/binary-reader-ir.cc
- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-writer.cc
- src/binary.cc
- src/binary.h
- test/dump/extended-names.txt
Tag names are not officially part of the extended-name-section proposal
(because it only deals with naming things that are in the spec already).
However, I think its reasonable (and useful) to include these names
under a speculative subsection on the basis that tags can only exist
when exceptions are enabled and that engines should ignore unknown name
types.
> Show tag names in objdump disassembly

- test/binary/bad-function-missing-end.txt
I guess the spec tests don't include such a test.
> Add test for function lacking END marker. NFC

- src/binary-reader-objdump.cc
- src/binary-reader.cc
- test/dump/select.txt
Use `LogOpcodeType` rather than` LogOpcodeBare` when the select
instruction has a type.
> wasm-objdump: Fix disassembly output of selectT instruction

- src/shared-validator.cc
- src/shared-validator.h
The SharedValidator was assuming it could keep a pointer to the incoming
location of each expression longer than the scope of the function.
This assumption holds true for one of the users of SharedValidator
(src/validator.cc) but I'm working on change that adds better location
tracking to the other one in (src/interp/binary-reader-interp.cc) and in
that case its easier to pass temporary locations into the
SharedValidator that don't outlive the call.
> Make copies of incoming expression locations in SharedValidator. NFC

- src/shared-validator.cc
- src/type-checker.cc
- src/type-checker.h
In #1768, I renamed the parameter to `OnFuncRefExpr` without realizing
that there are two distinct methods in the codebase with this name.  On
is the `BinaryReader` callback which takes a function index and one is
the `TypeChecker` callback which takes a function *type* (a type index).
> Fix param naming for `OnFuncRefExpr` (See #1768). NFC

- src/base-types.h
- src/common.h
- src/string-format.h
- src/type.h
This allows them to be used in headers such as `src/type.h`
which, because they are needed in common.h, cannot themselves
include `common.h`
This allows, for example, `StringPrintf` to be used in type.h
which is something I'm planning to do as a followup.
> Split base-types.h and string-format.h out of common.h

- test/typecheck/bad-assertreturn-invoke-type-mismatch.txt
- test/typecheck/bad-assertreturn-type-mismatch.txt
This test seems to be intended to test the type checking behavior, but due to a syntax error in an export statement was just testing the parsing behavior instead. This PR fixes the syntax and adjusts the test expectations.
> Fix syntax for assert_return typecheck test

- src/binary-reader-logging.cc
- src/binary-reader-objdump.cc
- src/binary-reader-opcnt.cc
- src/binary-reader.cc
- src/binary-writer-spec.cc
- src/binary-writer.cc
- src/interp/interp-wasm-c-api.cc
- src/interp/interp.cc
- src/interp/interp.h
- src/shared-validator.cc
- src/tools/spectest-interp.cc
- src/type.h
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
- test/dump/typed_func_refs_params.txt
- test/dump/typed_func_refs_results.txt
- test/roundtrip/fold-function-references.txt
- test/typecheck/bad-callref-wrong-signature.txt
This requires `Type::GetName` to return to be dynamicllay created and
return `std::string` rather then a `const char*`
As this diff shows this type name is only used in textual output and
error messages so should this change should not have a effect of binary
parse time or the interpreter.
> Fix type names for function references

- src/binary-reader-objdump.cc
This check should only not be done during disassembly, only
when displaying details.
Fixes: #1790
> Fix erroneous reporting of "Data reloctions outside of segments"

- src/shared-validator.cc
Resolves https://github.com/WebAssembly/wabt/issues/1796
To test locally:
1. Make a WAT file containing a function which returns multiple values. Example:
```
(module
(func $mult (export "mult")
(result f64 f64)
f64.const 1
f64.const 2
)
)
```
2. Use `wat2wasm` to compile, disabling multi-value. For example:
```
sudo bin/wat2wasm --disable-multi-value examples/multi.wat -o examples/multi.wasm
```
An error should be returned by the compiler. The wording of the error should be `multiple result values are not supported without multi-value enabled.`
> Updated multi-value message

- .github/workflows/build_release.yml
- .github/workflows/build_source_release.yml
It seems that the action we were using is not longer working:
https://github.com/actions/upload-release-asset
See https://github.com/WebAssembly/binaryen/pull/4148
> Update github action used to publish releases. NFC

- src/wast-parser.cc
- test/parse/module/import-func.txt
This simplifies the code for parsing imported functions
and makes it match more closely the code for parsing
non-imported functions.
Fixes: #1806
> Fix wat parsing of function imports with type name + inline type

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- test/dump/debug-names.txt
- test/dump/localget-param.txt
- test/dump/localset-param.txt
Currently, objdump -d will start at index 0 when printing local declarations e.g. `local[0] type=i64`, regardless of whether the function has any params. To me, it feels like starting the index at the param count to match the index used in opcodes and elsewhere would be less confusing.
> objdump: Consider params when printing local decl index

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- test/dump/extended-names.txt
Fixes #1815. Some example output:
```
module.wasm:	file format wasm 0x1
Code Disassembly:
000027 func[0] <FIRST>:
000028: 01 7f                      | local[0] type=i32
00002a: 20 01                      | local.get 1 <local0>
00002c: 20 00                      | local.get 0 <arg0>
00002e: 1a                         | drop
00002f: 1a                         | drop
000030: 0b                         | end
```
I haven't written a test for this yet, but I wanted to check that my approach was correct, not least because it's been a while since I've written any C++.
(Unfortunately, this doesn't actually fully solve my use case since I think wasm-ld doesn't preserve local names when linking? I haven't had a chance to investigate this yet, but mention it in case anyone knows off the top of their …
> wasm-objdump: Print local names during disassembly

- src/interp/interp-inl.h
- src/interp/interp.cc
- src/interp/interp.h
- src/test-interp.cc
Improves memory consumption since thread instances are freed without running garbage collector.
> Change Thread in interpreter to a normal object

- src/interp/interp.cc
- test/binary/bad-data-size.txt
When data of element segment init fails we were reporting the size, but
we were unconditionally calling `Drop` for active segments which meant
they always get reported as zero sized in the error message.
This mismatch was only showing up with bulk memory enabled (since
without this we do a two phase initialization).  The only test we have
for this error message was using `--disable-bulk-memory`, but not for
any good reason (most likely because of this very bug).
Also restore the comment about why we sometimes need to do a two phase
initialization for element and data segments.  This comment was lost in
PR #1330 but seem important since I don't think we have any tests for
this older behaviour.
> Fix size of segment in initialization error reporting

- README.md
- src/feature.def
- src/interp/binary-reader-interp.cc
- src/interp/interp.cc
- src/interp/interp.h
- src/shared-validator.cc
- src/shared-validator.h
- src/test-interp.cc
- test/help/spectest-interp.txt
- test/help/wasm-interp.txt
- test/help/wasm-opcodecnt.txt
- test/help/wasm-validate.txt
- test/help/wasm2wat.txt
- test/help/wast2json.txt
- test/help/wat-desugar.txt
- test/help/wat2wasm.txt
- test/spec/extended-const/data.txt
- test/spec/extended-const/elem.txt
- test/spec/extended-const/global.txt
- test/update-spec-tests.py
The primary changes here are to the interpreter and how it handles
initializer expressions.  With this change we model these are normal
function that we run during module initialization.
I imagine we could optimize this further by creating one long function
and encoding the `global.set`/`memory.init`/`table.init` into the
function itself, but this change seems like a good first step to make
the current tests pass.
> Initial implementation of extended-const proposal.

- src/tools/wasm2c.cc
- test/run-spec-wasm2c.py
- test/wasm2c/spec/multi-memory/binary.txt
- test/wasm2c/spec/multi-memory/data.txt
- test/wasm2c/spec/multi-memory/memory.txt
- test/wasm2c/spec/multi-memory/memory_grow.txt
- test/wasm2c/spec/multi-memory/memory_size.txt
~~This PR is sequenced behind #1810 and #1829.~~
PR #1751 added support for multi-memory and ran the multi-memory tests with `run-interp-spec`. This PR also runs (some of) the multi-memory tests under wasm2c, with `run-spec-wasm2c`. Only 5 of the 9 multi-memory tests are supported by wasm2c right now; the others require reference types, multi-table, or bulk memory.
> wasm2c: run multi-memory tests

- src/interp/interp.cc
- src/interp/interp.h
- src/test-interp.cc
The algorithm is made partially recursive, and requires only a single pointer in the Store object.
> Improve Garbage Collection algorithm

- .github/workflows/build.yml
- scripts/clang-format-diff.sh
Because clang-format-diff is designed to check only the diff, this effectively only checks the relevant commit instead of the whole repo. So it should be fine to accept PRs that don't pass lint - the lint job will fail for that commit, but following pushes should pass.
Granted this isn't so relevant for the main repo where everyone goes through PRs, but for forks/etc it makes a difference. An alternative would be to just skip clang-format-diff on push (with something like `if: github.event_name != 'push'` instead of `env: ...`) but, again: forks/etc.
> Fix lint CI on push

- src/interp/interp-inl.h
- src/interp/interp.h
Create a memory optimized free list for Refs in the interpreter.
This patch is based on a comment in the original Free List. The highest bit cannot be set for valid Ref indices, so it can be used to represent free items. If the patch is accepted, I will specialize the original free list for objects, where the lowest bit will represent unused slots.
> Implement a separate free list for Refs

- src/c-writer.cc
- test/run-spec-wasm2c.py
On windows these functions assert when passed nagative numbers.
This change is the first step in getting wasm2c running on windows.  It is
enough for wasm2c itself to run successfully on windows but the generated
code is not yet msvc compatible.
Also, update run-spec-wasm2c.py so that it run on windows, although we
are still skipping all the wasm2c tests by default on windows (for now).
Also, honor the --no-compile options which is how I managed to test
this change locally.
Precursor to #1366
> Avoid passing signed char to islpha family of function on windows

- docs/demo/wat2wasm/index.html
[Multi value](https://github.com/WebAssembly/multi-value) was merged into the spec almost a year ago, and all browsers support it. I think it is time to check the multi value checkbox by default.
Reference types were merged recently but support among browsers is limited at the moment, so I don't think it is time to check it by default yet.
Node stable does not support multi value, but this is a web based tool.
> Enable multi value by default

- .github/workflows/build.yml
- CMakeLists.txt
The wrong name here was causing a cmake warning because
it was finding `config.h.in` instead and this behaviour is
deprecated.
> Fix location in config.h in source list

- src/interp/interp.cc
- src/interp/interp.h
I have realized the Thread has not been removed and Exception has not been added to the ObjectKind as string list. This patch makes the maintenance automated. It seems this macro is used for debugging so I am not sure how to test this.
> Improve the maintenace of ObjectKind types.

- test/run-tests.py
Split out from #1843
This also avoids adding `-DWABT_BIG_ENDIAN=0` pointlessly to all build commands on little endian machines.
> run-tests.py: Use sys.byteorder to make code more readable. NFC

- src/interp/interp.h
When a new store object is assigned to a value, its FreeList is copied without duplicating the referenced objects, so these objects are destroyed twice.
> Fix Store object assignment.

- src/binary-reader-objdump.cc
- test/dump/extended-const.txt
As an example of what this looks like in practice I have a modified version of llvm
that uses extended const expressions and it produces segments that look like this
when output by objdump:
```
- segment[2] <.bss> memory=0 size=1720 - init (global.get 1 <__memory_base>, i32.const 720, i32.add)
```
Its not the most elegent, and has to be read in reverse polish notation style, but for the current set
of mostly trivial const expressions I think it suffices.
I we much more complex expressions we may need to revisit.
> wasm-objdump: support extended const expressions

- src/binary-reader-objdump.cc
- src/binary-reader-objdump.h
- test/dump/callindirect.txt
- test/dump/extended-names.txt
- test/dump/no-canonicalize.txt
- test/dump/relocations-all-features.txt
- test/dump/relocations.txt
- test/dump/symbol-tables-all-features.txt
- test/dump/symbol-tables.txt
Use the text format convention of putting the table before the
type.  Also track type names so they can be reported along with
the table name, if available.
Fixes: #1865
> wasm-objdump: Improve disassembly of call_indirect

- src/binary-reader-objdump.cc
- src/binary-reader.cc
- src/binary-reader.h
- test/binary/bad-opcode-prefix.txt
- test/binary/bad-opcode.txt
This is purely a performance optimization for wasm-objdump since it
doesn't always need to decode function bodies.
For a very large wasm file that I was testing this takes the time taken
for `wasm-objdump -h` from 8.6s to 1.5s.
> Allow binary reader to skip function bodies. NFC

- README.md
Edited a word in line 311 from "undefine" to "undefined"
This resolves #1879
> Corrected a misspelled word in README.md file

- src/shared-validator.cc
- test/spec/ref_func.txt
The validation was overly strict for ref.func index uses. In the spec, the ref index just needs to appear in
> the set of function indices occurring in the module, except in its functions or start function.
(https://webassembly.github.io/spec/core/valid/modules.html#valid-module)
which includes uses in the global and export sections. There were some test failures in the spec tests that were fixed by this, so the PR also changes test expectations.
Fixes issue #1893
> Fix checking of ref.func index declarations

- src/c-writer.cc
- test/run-spec-wasm2c.py
- test/spec-wasm2c-prefix.c
- wasm2c/README.md
- wasm2c/examples/fac/fac.c
- wasm2c/examples/fac/fac.h
- wasm2c/examples/fac/main.c
- wasm2c/examples/rot13/main.c
This effectively means that we no longer support imports that are
overloaded by signature only, which is not something that we need to
support in order to support the core wasm spec.
This feature is available in the JS embedding but there is no good
reason (AFAICT) to support it in wasm2c, and this simplifies the
generated code.
Fixes #1858
> Remove signature mangling from wasm2c output

- docs/demo/wat2wasm/demo.js
- docs/demo/wat2wasm/index.html
A new button is added for base64 encoding of the wasm binary. This allows getting the binary without downloading it.
> Add base64 encoding support to wat2wasm demo

- wasm2c/wasm-rt-impl.h
- wasm2c/wasm-rt.h
Multiline javadoc/doxygen comments start and end
with an empty line.
> Fix javadoc-style comment formatting. NFC

- src/wast-lexer.cc
- src/wast-parser.cc
- test/parse/bad-string-unicode-escape-large.txt
- test/parse/bad-string-unicode-escape-short.txt
- test/parse/bad-string-unicode-escape-unallowed.txt
- test/parse/bad-string-unicode-escape-unexpected.txt
- test/parse/bad-string-unicode-escape-unterminated.txt
- test/parse/bad-string-unicode-escape.txt
- test/roundtrip/string-unicode-escape.txt
Support \u{hex} escape sequences for string literals. These literals are converted to UTF-8 characters.
> Implement \u{hex} escape parsing

- src/binary-writer-spec.cc
- src/ir.cc
- src/ir.h
- src/resolve-names.cc
- src/tools/spectest-interp.cc
- src/validator.cc
- src/wast-parser.cc
- test/wast2json/module-binary.txt
Previously any top-level module defined in a .wast file would be parsed
and converted to a `Module` and stored in a `ModuleCommand`, since it
may be used later by the script (e.g. via an `invoke` command). This
means that when it was written out later it may have been changed, which
is undesirable for binary and quoted modules.
This change adds a new `ScriptModuleCommand`, which stores both a
`Module` and a `ScriptModule`. The `Module` contains the parsed
information, and the `ScriptModule` contains the original contents of
the binary or quoted data.
This fixes issue #1927.
> wast2json: write binary modules verbatim

- README.md
- docs/doc/wat2wasm.1.html
- man/wat2wasm.1
- src/tools/wat2wasm.cc
- test/help/wat2wasm.txt
Fixes #1941 
I wonder if the PR would be better by changing the example of calling with the `-o` flag directly below it in many of the changed files should be changed to speciffy a non-default-named file. That would make it clear that no `-o` flag indicates default name, while `-o` allows you to explicitly set it. Something like
```bash
$ bin/wat2wasm test.wat -o module.wasm
```
Signed-off-by: Mark Irish <markdirish@gmail.com>
> Change description of calling wat2wasm without -o flag

- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-impl.h
And use the `wasm_rt_` prefix for the one non-static global.
While reviewing #1930 I noticed these globals could/should be static.
> wasm2c: Use `static` for wasm-rt globals. NFC

- src/c-writer.cc
- wasm2c/README.md
- wasm2c/wasm-rt.h
wasm2c's README omitted the symbols that the runtime must implement to support wasm2c output (when wasm2c is run with exceptions support enabled). Closes #1949.
> wasm2c/README.md: document runtime symbols needed for exceptions

- src/c-writer.cc
Previously, the wasm2c generated code used an array to store the tag for each index, and looked up tags by index in the array at runtime. This PR changes the handling of tags to match everything else (one named symbol per tag). This is a stepping-stone on the way to #1814.
> wasm2c: simplify handling of exception tags

- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader-logging.h
- src/binary-reader-nop.h
- src/binary-reader-objdump.cc
- src/binary-reader-opcnt.cc
- src/binary-reader-opcnt.h
- src/binary-reader.cc
- src/binary-reader.h
- src/binary-writer.cc
- src/interp/binary-reader-interp.cc
- src/ir.h
- src/resolve-names.cc
- src/shared-validator.cc
- src/shared-validator.h
- src/validator.cc
- src/wast-parser.cc
- src/wast-parser.h
- src/wat-writer.cc
Previously, wabt could parse multi-memory SIMD loads/stores but not write them. (The testsuite for the multi-memory proposal doesn't currently test writing or execution of multi-memory SIMD ops, so this is untested. However, it does appear to roundtrip its own output on the "memory-multi" test.)
Closes #1958.
> Support multi-memory in all memory ops and in apply/resolve-names

- README.md
The name of the target is `emscripten-release`, for example.
> Change emcc -> emscripten

- src/wast-parser.cc
- src/wast-parser.h
- test/roundtrip/code-metadata.txt
This PR adds support for arbitrary hex strings in code metadata annotations. Previously, the decoded strings would be checked as utf-8 strings. However, this prohibits something like `(@metadata.code.trace_inst "\FF\FF")` since 0xffff is not a valid utf-8 string.
Also modified existing roundtrip test to have a string that includes a non-utf8 character
> Allow Code Metadata Annotations to have arbitrary hex strings

- .github/workflows/build.yml
The `trzeci/emscripten` images are now described as deprecated (https://hub.docker.com/r/trzeci/emscripten/). emsdk:latest is pretty fast moving which is a bit of a risk, but in principle not that different from the depenency on ubuntu-latest and windows-latest (and previously macos-latest).
> CI: Move emscripten build to official Docker image (emsdk:latest)

- src/c-writer.cc
- wasm2c/examples/fac/fac.c
This change avoids some confusing/redundant bracketing and makes
the output a little easier to easy and more like regular C usage.
Old:
```
wasm_rt_memory_t (*Z_test_hello_worldZ_memory);
...
Z_test_hello_worldZ_memory = (&w2c_memory);
Z_test_hello_worldZ__start = (&w2c__start)
```
New:
```
wasm_rt_memory_t* Z_test_hello_worldZ_memory;
...
Z_test_hello_worldZ_memory = &w2c_memory;
Z_test_hello_worldZ__start = &w2c__start;
```
> Simplify export declarations in wasm2c output. NFC

- wasm2c/wasm-rt-impl.c
This matches how they are declared in the header file.
> Update declaration of wasm_rt_get/set_unwind_target. NFC

- .github/workflows/build.yml
- CMakeLists.txt
The stated minimum, 3.1, was released on Dec 17, 2014 and did not support a value of 17 for `CMAKE_CXX_STANDARD`. The first version to do so was 3.8. In fact, attempting to build with CMake 3.7 fails with errors like:
```
CMake Error in CMakeLists.txt:
Target "wasm-strip" requires the language dialect "CXX17" , but CMake does
not know the compile flags to use to enable it.
```
So we might as well take this chance to raise the minimum to something more recent. I propose 3.16 here because of the following features:
* CMP0077 (v3.13) makes the lives of `FetchContent` users easier by allowing `option()` to be overridden.
* CMP0082 (v3.14) corrects the semantics of `install()` rules, which is relevant for `FetchContent` users.
* CMake 3.12 allows the namelink of a shared library on Linux to be …
> Raise minimum CMake version to 3.16

- CMakeLists.txt
This PR consists of two tightly related changes. It depends on #1968
`find_package(Threads)` was called redundantly and a bad check was used to disable a pthreads-specific test. Rather than checking `WIN32`, one should check `CMAKE_USE_PTHREADS_INIT`.
Rather than disable tests with a warning when Python cannot be found, require it when tests are enabled. Avoid the search altogether when tests are disabled.
This check additionally causes issues with FetchContent users that use the newer FindPython(3) module.
Fixes #1385
> Fix test dependencies

- CMakeLists.txt
- cmake/README.md
This PR makes two important fixes for FetchContent users.
This option is enabled by default when WABT is the top-level project and disabled by default when it is not. It is used (and should continue to be used) to guard uses of the install() command.
This fixes an issue where FetchContent users were forced to install parts of WABT. This most notably included the wasm-rt-impl library and its associated headers.
By default, CMake assigns every install() rule to an "Unspecified" component. By adding COMPONENT annotations, users become empowered to install only the parts of WABT that they need. WABT now provides three components:
1. `wabt-runtime` - the executables in WABT_EXECUTABLES
2. `wabt-development` - the wasm-rt static library and headers
3. `wabt-documentation` - the man pages, on …
> Build fixes for FetchContent users

- CMakeLists.txt
- src/config.h.in
- src/option-parser.cc
Before this commit, the attempt to add the output of `git describe` to the version string printed by `$wasm-tool --version` was bugged. It would always print the three-part version number (like 1.0.29).
After this commit, the output of `git describe --tags` is used to append a description to the version number in the form of: `ver (git~desc)`. For example:
$ ./wasm2c --version
1.0.29 (git~1.0.29-27-gf63184ef)
If this command returns a tag equal in name to the current version, nothing is appended.
If this command fails, a NOTICE (rather than a WARNING) is printed (only if the project is top-level), and only the bare version number is used. If the source code is not living in the git repository then, again, only the bare number is used, but no warning is printed.
Fixes #1977
Fixes #1978
> Fix git describe behavior

- .github/workflows/build.yml
- CMakeLists.txt
- scripts/wabt-config.cmake.in
Allows users to install wabt to a local directory and use `find_package` to load the `wabt` and `wasm-rt-impl` libraries into their build. These users, as well as FetchContent users, may link to these libraries using, for example:
find_package(wabt REQUIRED)
target_link_libraries(myApp PRIVATE wabt::wabt)
Note the `wabt::` namespace. The installed package requires only CMake 3.8 (on account of C++17).
> Make wabt find_package compatible

- src/decompiler-ast.h
- src/decompiler-naming.h
- src/interp/binary-reader-interp.cc
- test/binary/bad-interp-returncallindirect-invalid-sig.txt
- test/binary/bad-returncall-invalid-func.txt
- test/regress/regress-1922.txt
- test/regress/regress-1924.txt
Fixes https://github.com/WebAssembly/wabt/issues/1922
Fixes https://github.com/WebAssembly/wabt/issues/1924
Fixes https://github.com/WebAssembly/wabt/issues/1929
> Fix several issues found by fuzzing

- src/tools/spectest-interp.cc
- test/regress/regress-37.txt
The GetLane methods were looping over a "lane" variable, masking the parameter of the same name. This led to the last lane being returned in all cases, so tests would ignore the other lanes.
> [spectest-interp] Fix SIMD lane extraction bug

- src/c-writer.cc
- wasm2c/examples/fac/fac.c
Split off from https://github.com/WebAssembly/wabt/pull/1877#discussion_r974984930
Also:
- cleanup handling of newlines
- "init_memory"/"init_table" -> "init_memories"/"init_tables"
> wasm2c: eliminate unused initialization functions in output

- help2man.lua
- man/spectest-interp.1
- man/wasm-decompile.1
- man/wasm-interp.1
- man/wasm-objdump.1
- man/wasm-opcodecnt.1
- man/wasm-strip.1
- man/wasm-validate.1
- man/wasm2c.1
- man/wasm2wat.1
- man/wast2json.1
- man/wat-desugar.1
- man/wat2wasm.1
- scripts/help2man.lua
update the man pages based on the output of `--help` of the individual commands
> Updated man pages

- CMakeLists.txt
- src/config.h.in
- test/run-tests.py
This PR consists of two tightly related changes. It depends on #1968 
`TARGET_ARCH` was only used to determine whether to add gcc-specific SSE math flags (`-msse2 -mfpmath=sse`). The new approach simply assumes gcc compatibility with its `__i386__` and `__SSE2_MATH__` symbols, which are defined precisely when we are targeting x86-32 with SSE2 math enabled. If those macros are defined, then we conclude all is well. Otherwise, we
add the flags if we know the compiler is gcc or clang (and will thus accept them) and issue a warning if the compiler is unknown.
Fixes #1709
Fixes #1688
CMake prior to v3.20 provides a module TestBigEndian which we can use to set the `WABT_BIG_ENDIAN` define. As of 3.20, the `CMAKE_<LANG>_BYTE_ORDER` variable should be preferred. Leaving this as a note for the …
> Fix architecture checks

- src/template/wasm2c.declarations.c
Simplify wasm2c table_copy to use memmove (per https://github.com/WebAssembly/wabt/pull/1887#discussion_r985115310).
> wasm2c templated code: simplify table_copy to use memmove

- include/wabt/wast-lexer.h
- src/wast-lexer.cc
- test/spec/tokens.txt
- test/wasm2c/spec/tokens.txt
The testsuite was already updated in https://github.com/WebAssembly/wabt/pull/2003, so this just runs `update-spec-tests.py` to bring in the new `tokens.wast` test. The Wast lexer changes are necessary because of https://github.com/WebAssembly/spec/pull/1499 . There may be a more elegant way to make this change, though...
> Finish updating testsuite

- CMakeLists.txt
> wasm2c: Don't create a separate library for cwriter-template. NFC

- wasm2c/examples/fac/main.c
- wasm2c/examples/rot13/main.c
Ensure wasm2c examples print something useful when you run them
> Fix wasm2c examples to print helpful prompts

- include/wabt/opcode.h
- include/wabt/type-checker.h
- src/type-checker.cc
Simplify `CheckOpcode1` by avoiding using it for memory.fill.
Simplify and move GetMemoryParam.
> Simplify part of type-checker. NFC

- include/wabt/type-checker.h
- src/shared-validator.cc
- src/type-checker.cc
- test/parse/expr/bad-memory-copy-differing-type.txt
- test/parse/expr/memory-copy-differing-type.txt
When both the `multi-memory` and `memory64` features are enabled it's possible for `memory.copy` to copy between two memories of different types. In this case, the `memory64` proposal specifies that the `src` and `dst` arguments should correspond to the types of the memory they are accessing, and the `size` argument should correspond to the "minimum" of the two memory types [1]. That is, the `size` should be an `i32` if either of the memories has type `i32` and it should be `i64` if both of the memories have type `i64`.
This existing code just expects all three arguments to match the type of the source memory which works whenever the source and destination memories have the same type. This change adjusts that logic to agree with the `memory64` proposal in the cases where the two memories …
> Align `memory.copy` arg types with `memory64` proposal

- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt.h
The Firefox use case of sandboxing untrusted libraries with Wasm is incompatible with use of signal handlers in wasm2c. This is because Firefox has its own signal handler, with a crash report, stack walking, telemetry handling etc. However, for speed, we still need to use the guard page (8gb model) to trap OOB linear memory accesses from sandboxed libraries (versus memory bounds/range checks). Given that Firefox also does not attempt to recover from any linear memory OOB, the easiest option is to give a macro that disables the install and use of signal handlers.
> Allow use of guard pages without requiring a signal handler

- CMakeLists.txt
This allows programs linking with `libwabt` to use `CWriter`. (Currently, `c-writer.cc` and the source templates are only linked into the `wasm2c` executable.)
> Include CWriter in libwabt

- src/binary-reader-ir.cc
- test/regress/regress-2039.txt
- test/run-spec-wasm2c.py
Fixes #2039.
Split out from #2035.
> BinaryReaderIR: fix mis-binding of tags with debug name

- src/c-writer.cc
Require all resolution of GlobalNames to happen in one place (Write(GlobalName)). Also eliminate AddressOf, Deref, GlobalVar.
This is a step towards fixing #2034 (split out from #2035).
> c-writer.cc: Eliminate GetGlobalName (NFC)

- src/template/wasm2c.declarations.c
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-impl.h
- wasm2c/wasm-rt.h
Correct handling of Wasm's 8gb model on Windows
- Uses the Windows ExceptionHandler to track access violations (segfaults)
- Fix Windows memory to reserve, but not commit memory up front
- Correct handling of return values in os_mmap functions
- Decouple stack depth handling and heap bounds checking
> wasm2c: Fix 8gb model, signals, memory reserve/commits, stack depth on windows

- wasm2c/README.md
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt.h
In production use cases, unwinding the stack before reporting an error throws away valuable information such as the stack trace. This hook allows the host to implement an alternate error recovery/reporting mechanism
> wasm2c: add hook to allow a custom trap handler

- src/c-writer.cc
Use `const auto&` in for loops where applicable.
Remove usages of `module_->imports` outside of BeginInstance
Replace `if (vec.size())` with `if (!vec.empty())`
> Some minor code cleanups in c-writer.cc

- test/run-spec-wasm2c.py
I've been having some issues with the recent version of gcc on my system and being able to run `CC=/usr/bin/clang ./test/run-tests.py` has proved useful.
> Honor CC environment variable in test/run-spec-wasm2c.py

- src/c-writer.cc
I could do the same for FuncRef above.. but that would turn `isNull` on FuncRef from a one 1-word check to a 3-word check.  Maybe not worth it?
> wasm2c: Use GetReferenceNullValue() helper. NFC

- include/wabt/interp/interp.h
- src/interp/interp.cc
All of these checks represent cases where a validation error would prevent the type mismatch.
When debugging #2054 this check actually worked against since it was resulting a false-positive "out-of-bound" error reports when really it was an internal type inconsistency (a bug).
> Convert type checks to assertions in the interpreter. NFC

- CMakeLists.txt
Toolchains using wasm2c depend on the wasm-rt files to build the generated programs. Using a packaged binary wasm-rt library is not enough for toolchains that do e.g. cross-compilation, and they need to copy and use the source files instead. Therefore, package the required wasm-rt source files as data for toolchains to use.
Even though some files are already installed in `include`, I deliberately chose to install all the required headers and source files in the data dir, to ensure it's clear these belong together as data for toolchains. I believe it is unusual and confusing that a toolchain should copy some data from the platform's `include` dir and assume it is platform-independent, as this dir should only contain platform-specific headers used for compiling software for the host …
> Install wasm2c source files as data

- src/c-writer.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
Here's one approach to keep externref initializers agnostic to the type of externref while keeping MSVC happy about only using constant expressions in the initializers. (We use `wasm_rt_externref_t` typedef'd to a non-pointer type, so `NULL` doesn't typecheck in that setting.)
An alternative could be to change `wasm_rt_externref_null_value` to a `#define` (instead of a `static const`) but this seems maybe preferable...?
> wasm2c: allow externref initialization when externref type is not void*

- include/wabt/base-types.h
- include/wabt/binary.h
- include/wabt/circular-array.h
- include/wabt/common.h
- include/wabt/interp/interp.h
- include/wabt/interp/istream.h
- include/wabt/ir.h
- include/wabt/opcode.h
- include/wabt/wast-lexer.h
- src/binary-writer.cc
- src/test-hexfloat.cc
IIUC this is prefered in modern C++ and expresses indent better.
> Prefer `constexpr` over `static const`. NFC

- include/wabt/base-types.h
- include/wabt/binary-reader-opcnt.h
- include/wabt/binary-writer-spec.h
- include/wabt/binding-hash.h
- include/wabt/circular-array.h
- include/wabt/intrusive-list.h
- include/wabt/ir.h
- include/wabt/option-parser.h
- include/wabt/range.h
- include/wabt/type-checker.h
- include/wabt/wast-parser.h
- src/binary-writer.cc
- src/c-writer.cc
- src/emscripten-helpers.cc
- src/interp/interp-wasi.cc
- src/literal.cc
- src/test-intrusive-list.cc
- src/tools/spectest-interp.cc
- src/tools/wasm-opcodecnt.cc
- src/wast-parser.cc
This is more modern and (IMHO) easier to read than that old C typedef syntax.
> Switch from `typedef` to using `using` in C++ code. NFC

- CMakeLists.txt
- include/wabt/interp/interp.h
- src/config.h.in
Value's `type` field was compiled conditionally on the `NDEBUG` define. This causes problems with programs compiling against libwabt that don't define this macro, as the Value layout no longer matches.
Removing the condition entirely, assuming the performance impact of this is limited (especially if assertions are disabled).
Fixes #2069
> interp: Remove condition for performing type checks on `Value`

- CMakeLists.txt
The wasm2c runtime should now be supported on Windows per 6a89e3f74560eb8f0396c24ce625de0023cb46b2
> Package wasm-rt-impl source files on Windows

- .github/workflows/build.yml
Move the GitHub CI tests for "asan" and "ubsan" over to using clang as the wasm2c compiler (in addition to using clang to compile wasm2c and the rest of WABT itself). Prerequisite for #2077.
This could probably be done in a more principled way (by modifying the Makefile for "clang-xxx-asan" and "clang-xxx-ubsan") but this matches the current practice in setting WASM2C_CFLAGS explicitly in the GitHub workflow (and is easier).
> wasm2c CI: run asan and ubsan tests on clang 14

- .github/workflows/build.yml
- test/run-spec-wasm2c.py
This is intended to improve GCC's long compile times for some of the extremely long SIMD tests that will come soon (#2021).
On my laptop running Ubuntu 22.04, this change reduces the time for the simd_f32x4_pmin_pmax.wast test from 16 minutes to about 70 seconds.
> run-spec-wasm2c.py: split `run_spec_tests` function if it's too long

- include/wabt/type.h
- src/c-writer.cc
- test/regress/regress-2034.txt
This change allows wasm2c to handle duplicate names across different module fields (e.g. an elem segment and tag both named "$e0"), by tracking the field type explicitly at each definition and then reference to a GlobalName.
There may be a less intensive way to do this... am not wedded to the approach, but this does seem to fix it.
~~Also fixes an issue in the BinaryReaderIR where tag names were being bound in a different bindings hash, which was leading to a segfault in wasm2c when a named tag was exported (because it couldn't find the tag by name).~~
Adds a regression test.
Fixes #2034.
> wasm2c: handle duplicate names across module fields

- CMakeLists.txt
GitHub is starting to phase in ubuntu-22.04 runners for "ubuntu-latest" workflows, and these use GCC 11 which has some new warnings that break WABT's build of gtest and uvwasi, so we are starting to get nondeterministic failures in the CI. This silences the warnings just for gtest and uvwasi.
~~I left the CI workflow as "ubuntu-latest" so this might be tested with GCC 9 (ubuntu-22.04) or GCC 11 (ubuntu-22.04) depending on the luck of the draw. We could hardcode it as ubuntu-22.04 in build.yml if we want to get rid of the nondeterminism.~~ (Edit: based on https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/, it looks like the period of nondeterminism/cutover is basically over.)
> Silence gtest and uvwasi warnings on GCC 11

- include/wabt/common.h
- include/wabt/error.h
- src/config.h.in
I'm not sure this was ever needed.  `__inline` and `inline` are identical under msvc:
https://learn.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=msvc-170 "The __inline keyword is equivalent to inline"
> Use inline keyword over WABT_INLINE. NFC

- src/wast-parser.cc
- test/dump/tag.txt
- test/regress/regress-2110.txt
- test/regress/regress-38.txt
Fixes a bug first noticed at #1906.
> wast-parser.cc: disallow exception tag unless exceptions enabled

- src/c-writer.cc
Prevent clang-format from automatically changing manually formatted regions of code. The file has some existing annotations, but is missing some. Checked on clang-format 10
> wasm2c: mark manually formatted code in c-writer

- README.md
The instruction was removed from the Relaxed SIMD spec, so this implementation is now up to date.
> Remove note on bfloat16 dot product instruction

- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-impl.h
- wasm2c/wasm-rt.h
Use of powerful primitives like longjmp is of some security concern for the Firefox context. While the Firefox use case would leave all setjmp/longjmp use cases as dead code, there is still some concerns. This PR makes the wasm2c generated code more defensive when using `longjmp`. The code now checks that `jmp_buf` is initialized by `setjmp` before use with `longjmp`.
**Costs**: The costs here are minor: (1) a variable initialization during wasm_rt_try, and (2) a conditional check during exceptions or traps (which are usually not the critical path in programs).
> wasm2c: harden set/longjmp to check for uninit jmp_buf

- test/spec-wasm2c-prefix.c
The spectest_make_externref() in [test/spec-wasm2c-prefix.c:203](https://github.com/WebAssembly/wabt/blob/main/test/spec-wasm2c-prefix.c#L203) assumes that `u64` (`uint64_t`) can be converted to `wasm_rt_externref_t` (`void *`). This is not the case on 32-bit platforms.
```
- test/regress/regress-2039.txt
expected error code 0, got 1.
STDERR MISMATCH:
--- expected
+++ actual
@@ -0,0 +1,19 @@
+out/test/regress/regress-2039/regress-2039-main.c: In function ‘spectest_make_externref’:
+out/test/regress/regress-2039/regress-2039-main.c:205:10: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
+  205 |   return (wasm_rt_externref_t)(x + 1);  // externref(0) is not null
+      |          ^
```
The same error occurs with all wasm2c tests.
This fixes #2099.
> fix wasm2c tests on 32-bit

- src/c-writer.cc
- wasm2c/README.md
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt.h
This lets exception tags be pre-assigned at compile-time (link-time?), instead of making the runtime keep an incrementing counter. 
Since every declared tag is unique (unlike with function types which are only unique if the types differ), this is pretty feasible to do in advance -- the tag value just becomes a pointer to a static dummy variable that belongs to the module. We can count on the OS not to load two modules in the same address of virtual memory!
Another step towards reducing the need for the runtime to keep global state.
If we merge #2120 and this one, we'll end up eliminating everything that [modname]_init_module does -- that function could go away as the modules wouldn't need any runtime initialization.
> wasm2c: eliminate wasm_rt_register_tag()

- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-impl.h
- wasm2c/wasm-rt.h
This PR marks the temporary storage used to handle traps, exceptions, and the call-stack limit as thread-local (when the runtime is compiled as C11 or later so `thread_local` is available).
Other than this, I _think_ the only remaining sources of "MT-unsafety" in the runtime are:
- the function type registry (removed in #2120)
- the use of sigaltstack to handle segfaults. I think we will need to refactor the runtime API for this because sigaltstack needs to be called on a per-thread basis (and the alt-stack may need to be malloc'ed and freed on a per-thread basis if we can't make it a static thread-local array).
(Also, it would be nice to have a multithreaded test of the runtime to make sure it really does work re-entrantly.)
> wasm2c rt: mark temp storage for traps/exceptions as thread_local

- wasm2c/wasm-rt.h
Fixup from #2126. MSVC in C11 mode sets `__STDC_VERSION__` >= 201112L but doesn't support `_Thread_local`. It does appear to support `__declspec(thread)`.
> wasm-rt.h: MSVC doesn't support _Thread_local, even in C11 mode

- wasm2c/README.md
- wasm2c/examples/fac/fac.c
- wasm2c/examples/rot13/main.c
- wasm2c/wasm-rt.h
The rot13 example was failing to build after the addition of memory64 support to the wasm2c runtime API.
> Update wasm2c examples to reflect new wasm_rt_allocate_memory() param

- test/run-spec-wasm2c.py
- test/utils.py
This allows CMake to override flags like -O2 by appending -O0 from the env var.
This is helpful for allowing a "debug" test of wasm2c output, since this way we
can disable optimization by adding `-O0` to the environment variable (as used in #2081).
Split out from #2081 per request.
Once we reach convergence on #2080/#2081/#2134, I think we're ready to merge #2119 (SIMD).
> run-spec-wasm2c.py: move WASM2C_CFLAGS to end of compiler command line

- .github/workflows/build.yml
- src/c-writer.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- wasm2c/examples/fac/fac.c
We had been running the GitHub UBSAN wasm2c tests with -fsanitize=undefined but without -fno-sanitize-recover, meaning some of the spec tests were printing UBSAN error messages but still returning 0, so we weren't seeing the test failures.
The two issues that UBSAN was flagging were:
- fabs and fabsf left-shifting signed literals by 31 or 63 (switched to making them unsigned)
- calling memcpy with a zero length but NULL src (switched to adding an explicit `check_only` parameter to `memory_init` and `LOAD_DATA` that makes them skip the actual memcpy but still enforce the bounds-check, which is required)
Once we reach convergence on #2080/#2081/#2134, I think we're ready to merge #2119 (SIMD).
> Make wasm2c output UBSAN-clean (and run w2c CI w/ UBSAN)

- src/tools/wasm-strip.cc
- test/strip/keep_section.txt
This PR proposes the addition of the `-k/--keep-section <SECTION NAME>` flag, that can be specified multiple times to prevent sections with a specific name from getting stripped.
Below you’ll find some context why I think this is useful. WDYT?
This PR is motivated by my desire to strip everything _but_ the `name` section. I have found that for example Rust embeds a lot of other custom sections, which makes module size analysis quite noisy. Here, for example, the percentages become almost meaningless due to the size of the custom sections:
```
$ twiggy top bindgen.wasm -n 20
Shallow Bytes │ Shallow % │ Item
───────────────┼───────────┼────────────────────────────────────────────────────────────────────────────
652300 ┊    36.33% ┊ custom section '.debug_str'
404594 ┊    22.53% ┊ custom …
```
> wasm-strip: Add `-k/--keep-section` flag to prevent sections with specific names from getting stripped

- src/c-writer.cc
- src/template/wasm2c.bottom.h
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
This will hopefully make things a bit easier for us going forward -- I think we have been expending effort to try to make every "section" of the wasm2c output start with exactly one blank line, which means some bookkeeping to make sure the newline isn't printed unless the "section" is also going to print a non-blank line, etc. (And in some cases we were printing double blank lines despite our best efforts.)
This PR makes the writer compress consecutive Newlines so that extra newlines become (even more) harmless; it caps the number of completely blank lines in a row at 1 and cleans up the output slightly.
> wasm2c: tweak newline handling to cap blank lines between sections (NFC)

- src/c-writer.cc
I saw this when looking at some of test output from the `imports.wast` test. The `dummy_member` was being added to the module instance structure unnecessarily in the case of a module that imports functions but has no other elements.
> c-writer.cc: omit dummy_member in one case where it was unnecessary (NFC)

- src/wast-lexer.cc
- test/regress/bad-annotation.txt
`wat2wasm` had been crashing on some invalid annotations, even with annotations disabled (as found by oss-fuzz in issue 53935).
I missed this in #2001 when updating the parser to match the updated spec (WebAssembly/spec#1499). This PR fixes the lexer and adds a regression test.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53935
N.B. With annotations enabled, `wat2wasm` seems to go into an infinite loop on this same input; will require further investigation.
> Improve lexing of invalid annotations (fixes fuzz failure)

- include/wabt/wat-writer.h
- src/tools/wasm2wat.cc
- src/tools/wat-desugar.cc
- src/wast-parser.cc
- src/wat-writer.cc
- test/roundtrip/fold-function-references.txt
- test/roundtrip/inline-export-func.txt
- test/run-roundtrip.py
Even when the result is to be printed rather than compared byte for byte
with the first version its still good to process the resulting wat
output file so that we know we can parse what we generate.
Case in point, this changed caused me to fix two latent bugs:
1. We were not correctly parsing events with inline import/export.
2. We were output element segment names even when bulk memory
was not enabled (See #1651)
The fix for (2) is a little more involved that we might like since for
the first time the wat writer needs to know what features are enabled.
Fixes: #1651
> Always do a full roundtrip in run-roundtrip.py

- src/tools/wasm2c.cc
Makes it possible to wasm2c --disable-sign-extension
(Yes, this typo is our fault... sorry!)
> Fix longstanding typo

- CMakeLists.txt
I don't think there is any need to use `WASM=0` these days.  If anybody really cares about node performance and this turns out still to be faster they can always add this back in.
> Remove some old emcc link flags

- .github/workflows/wabt-cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where WABT already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
> CI: add CIFuzz action

- .gitattributes
- include/wabt/wast-lexer.h
- src/wast-lexer.cc
- src/wast-parser.cc
- test/regress/bad-annotation.txt
- test/regress/bad-annotation2.txt
- test/regress/unterminated-annotation.txt
- test/regress/unterminated-annotation2.txt
This adds a bounds-check to WastLexer::GetText to handle the case when the offset is earlier than token_start (e.g. because GetStringToken found a newline in the string and reset token_start to point to it).
Also revises GetIdToken -> GetIdChars to stop skipping the initial char in an annotation delimiter, which is an idchar+ but not an id token.
Also fixes the WastParser to handle EOF when reading for the end of an annotation, both for code metadata annotation and other kinds. Previously this produced an infinite loop (but only when --enable-annotations was provided).
Fixes #2165 and adds some more regression tests.
This is sort of deja vu after #2150, sigh.
> Improve lexing and parsing of invalid annotations (again)

- src/c-writer.cc
- test/wasm2c/add.txt
- test/wasm2c/hello.txt
- wasm2c/README.md
- wasm2c/examples/fac/fac.c
This adds `kLocalSymbolPrefix` which is used for names of params, locals and stack vars. This allows c-writer to not assign `global_syms_` to `local_syms_` for writing each individual function, since local names can't duplicate global names.
This speeds up the execution of `wasm2c` on large inputs. `clang.wasm` is a 75M WASM module. Before this PR, `wasm2c` on `clang.wasm` would take ~63 minutes.
```
time ./build/wasm2c clang.wasm -o clang.c --enable-multi-memory
real    63m42.780s
user    63m15.818s
sys     0m24.107s
```
After this PR, it takes ~2 minutes.
```
time ./build/wasm2c clang.wasm -o clang.c --enable-multi-memory
real    2m12.889s
user    2m8.853s
sys     0m3.983s
```
> c-writer.cc: Add local symbol prefix.

- src/binary-reader.cc
- test/binary/bad-too-many-locals.txt
- test/spec/binary.txt
- test/spec/exception-handling/binary.txt
- test/spec/memory64/binary.txt
- test/spec/multi-memory/binary.txt
On the tour of cleaning up what look like relatively easy old issues. (The error message was missing one '0'.)
Fixes #1593
> binary-reader.cc: expand max local count and fix error message

- src/tools/wasm-interp.cc
- test/help/wasm-interp.txt
- test/interp/call-with-argument.txt
- test/interp/run-export-as-global.txt
- test/interp/run-export-with-argument.txt
Reference: https://github.com/WebAssembly/wabt/pull/1167 cc @keithw 
Closes: https://github.com/WebAssembly/wabt/issues/198
Allows `wasm-interp` to be execute specific exported wasm functions by name.
Quick example:
```lisp
(module (func (export "func_sum") (param i32) (param i32) (result i32)
local.get 0
local.get 1
i32.add
return))
```
```bash
$ ./wasm-interp sum.wasm -r func_sum -a "i32:8" -a "i32:5" 
func_sum(i32:8, i32:5) => i32:13
```
with `--trace`
```bash
$ ./wasm-interp sum.wasm -r func_sum -a "i32:8" -a "i32:5" --trace
>>> running export "func_sum":
#0.    0: V:2  | local.get $2
#0.    8: V:3  | local.get $2
#0.   16: V:4  | i32.add 8, 5
#0.   20: V:3  | drop_keep $2 $1
#0.   32: V:1  | return
func_sum(i32:8, i32:5) => i32:13
```
Supported types: i32, i64, f32, f64
```bash …
```
> implementation of --run-export and --argument

- src/c-writer.cc
- src/tools/spectest-interp.cc
- src/type-checker.cc
- src/wat-writer.cc
These changes allow the build to succeed with `-DWERROR=ON` on GCC 12.
Fixes #2020
> Silence warnings on GCC 12

- src/tools/wasm2c.cc
This simplifies the wasm2c main-ish function to use CHECK_RESULT everywhere it can. This lets the function be written in a less nested/indented way and now validates the module before running GenerateNames.
Fixes #2180
> wasm2c: use CHECK_RESULT throughout workhorse function (NFC)

- .github/workflows/build.yml
- CMakeLists.txt
- scripts/check_clean.py
- scripts/gen-wasm2c-templates.cmake
- src/prebuilt/wasm2c_header_bottom.cc
- src/prebuilt/wasm2c_header_top.cc
- src/prebuilt/wasm2c_source_declarations.cc
- src/prebuilt/wasm2c_source_includes.cc
In anticipation of Firefox moving to use upstream wasm2c, I am trying to simplify the build process for wasm2c.  
Wasm2c uses CMake generates source code during the build to transform source templates into strings in order to make development easy. However, generating source code on the fly with CMake requires us to jump though hoops in the Firefox build (also Firefox does not use CMake, so baking in a reliance on CMake to build causes added inconvenience).
This PR moves us to a model which hopefully give us the best of both worlds. The template files are still built by CMake, but are done in the src/prebuilt folder and checked in as part of source. This should allow us to continue using the template model during development, but also keep this easy to use in Firefox which can use the …
> wasm2c: Generate and checkin prebuilt source code in source folder

- .github/workflows/build.yml
- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- wasm2c/examples/fac/fac.c
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-impl.h
- wasm2c/wasm-rt.h
(Edited for the latest push)
The wasm2c runtime implementation today blends a couple of concepts together that make it hard to use in 32-bit environment. These are the
1. The memory allocation/growth strategy - **mmap** (memories supporting in-place growth) vs **malloc** (memories that may be moved to grow)
2. The OOB prevention strategy - **Guardpages** (which requires **mmap** memory, 64-bit platforms and WasmMemory32) vs **Boundschecks**. I am planing to add other strategies in the future. 
When using wasm2c in Firefox with RLBox, we want the following configurations
1. **mmap** always as RLBox does not support moveable memories
2. **Guardpages** on 64-bit and **BoundsChecks** on 32-bit (as guard pages are not supported in 32-bit)
Since wasm2c blends this concepts together these …
> wasm2c: Separate the macros for allocation and bounds checks strategies

- wasm2c/README.md
- wasm2c/wasm-rt-impl.c
Memory growth failures (when `wasm_rt_grow_memory` returns -1) cause the libc used by wasm toolchains to return a 0 during malloc. This is usually ignored by most applications, and they continue execution resulting in corrupted internal state.
For the use in Firefox, we need a hook to be notified of memory growth failures, so we can annotate subsequent crash reports with this information.
> wasm2c: Add optional WASM_RT_GROW_FAILED_HANDLER to be notified of memory growth failures

- wasm2c/wasm-rt-impl.c
> wasm-rt-impl.c: wasm_rt_free() should reset g_signal_handler_installed

- src/c-writer.cc
The memory initial and max sizes were being printed as uint32_t because it was using the `Write(Index)` overload.
Additionally, reflect the default value of max pages for i64-indexed memories.
(Wondering if we need a test for this... seems a bit painful if we have to actually allocate >4GiB of memory in the testsuite.)
> c-writer.cc: Fix memory64 allocation when limits are >2^32

- src/prebuilt/wasm2c_source_includes.cc
- src/template/wasm2c.includes.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
per http://man.openbsd.org/alloca.3
totally untested in wabt itself, but fixes mozilla-central build for me.
> alloca() lives in <stdlib.h> on OpenBSD too (fixes #2216)

- src/tools/spectest-interp.cc
- src/validator.cc
Right now we're running the spec tests against the BinaryReaderInterp, and the BinaryReaderIR and Validator are sometimes only tested in the wasm2c tests (which don't run the `assert_malformed`, `assert_invalid`, or `assert_unlinkable` tests yet).
This PR makes spectest-interp compare both readers/validators and bombs out when they disagree about module validity. This caught one issue where the Validator was mistakenly accepting some malformed modules from the (post bulk-memory) spec tests.
Fixes #2220
> Make sure Validator and BinaryReaderInterp agree re: validity

- wasm2c/wasm-rt-impl.c
Per suggestion of @sbc100 in https://github.com/WebAssembly/wabt/pull/2222#discussion_r1181155780, reducing the size of maximum exceptions
> wasm2c: reduce the max exceptions size

- CMakeLists.txt
- include/wabt/c-writer.h
- src/c-writer.cc
- src/prebuilt/wasm2c_header_top.cc
- src/template/wasm2c.top.h
- src/tools/wasm2c.cc
- test/run-spec-wasm2c.py
- test/spec-wasm2c-prefix.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- wasm2c/README.md
- wasm2c/examples/callback/Makefile
- wasm2c/examples/fac/Makefile
- wasm2c/examples/fac/fac.c
- wasm2c/examples/fac/fac.h
- wasm2c/examples/rot13/Makefile
- wasm2c/wasm-rt-exceptions-impl.c
- wasm2c/wasm-rt-exceptions.h
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-impl.h
- wasm2c/wasm-rt.h
Ensure exceptions and simd are enabled according the feature flags exposed in the command line of wasm2c
@sbc100 Would this be close to what you were suggesting in https://github.com/WebAssembly/wabt/pull/2221#issuecomment-1527752792
Happy to bikeshed some more
>  wasm2c: Enable exceptions and simd according to command line flags

- src/binary-reader-ir.cc
- src/binary-reader.cc
- test/regress/bad-missing-end.txt
- test/spec/binary.txt
- test/spec/exception-handling/binary.txt
- test/spec/multi-memory/binary.txt
Fixes #2199. (Possibly related to #1771)
This adds some safety checks in BinaryReader & BinaryReaderIR to prevent crashing on some "missing end marker" situations.
1. Add a check in BinaryReader that init expressions end with an "end" opcode (matching the pre-existing check for function bodies).
2. Add checks in BinaryReaderIR that the label stack is empty at the end of an init expression or function body. (This isn't enforced in validation or typechecking because the end markers don't make it into the IR.)
3. The test (regress/bad-missing-end.txt) triggers the same assertion failure as #2199 before applying this PR.
> BinaryReader/BinaryReaderIR: add safety checks for missing end markers in init expressions

- README.md
- test/wasm2c/spec/simd_f32x4.txt
- test/wasm2c/spec/simd_f32x4_rounding.txt
- test/wasm2c/spec/simd_f64x2.txt
- test/wasm2c/spec/simd_f64x2_rounding.txt
- test/wasm2c/spec/simd_i16x8_q15mulr_sat_s.txt
This completes support for the SIMD proposal that was mostly done in #2021 / #2119.
Will check first three boxes in #2224.
> wasm2c: update simde submodule to 0.7.4-rc4 and add remaining tests

- src/color.cc
We don't need windows.h if color printing is disabled i.e., HAVE_WIN32_VT100 is not defined
@keithw @sbc100 Unfortunately a blocking bug for use in Firefox as we temporarily need to build wasm2c without relying on windows.h
> Don't include windows.h for color printing if !HAVE_WIN32_VT100

- README.md
The footnote was removed in https://github.com/WebAssembly/wabt/commit/463b54d39fdc86f41875d185a450173cf236f1f9
> fix relaxed-simd link

- include/wabt/c-writer.h
- include/wabt/ir.h
- src/binary-reader-ir.cc
- src/c-writer.cc
- src/tools/wasm2c.cc
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
This is tasks 4 and 5 from #2224.
> Track use of SIMD and exceptions in IR, and CWriter includes support only if used

- src/c-writer.cc
- test/regress/wasm2c-try-br.txt
~Sequenced behind #2207.~ Fixes #2205. wasm2c was making a LabelDecl with the raw Wasm name instead of the safe/unique C name. Because the label's C name is generated in `BeginTry` but the LabelDecl doesn't come until later, it's probably easiest just to re-retrieve the C name at that point. Or we could have `BeginTry` actually return the generated C name (along with the mark)...
The exception-handling proposal could benefit from better test coverage here (https://github.com/WebAssembly/exception-handling/issues/210) but this is definitely our bug!
> c-writer.cc: Correctly handle label names when branching out of try block

- src/color.cc
@sbc100 Addressing the comment https://github.com/WebAssembly/wabt/pull/2228/files/9ede8fe37999d10ecda449afe43312d04133718d#r1187855033 from https://github.com/WebAssembly/wabt/pull/2228
**Edit:** Unfortunately, i think we can't make this change as HAVE_WIN32_VT100 is defined only in win32 platforms
https://github.com/WebAssembly/wabt/blob/main/CMakeLists.txt#L121
If you prefer I can change the CMAKE to define it always, or we could leave the nested _WIN32 and HAVE_WIN32_VT100 in place. Happy to go either way
> Cleanup use of HAVE_WIN32_VT100 in color.cc

- CMakeLists.txt
This reverts commit 0e6861f0480dfbb6461121463e0963391cc38ccf.
I just discovered to my chagrin that GitHub allows rule-violating pushes (but not force-pushes) to our main branch if typoed from the command-line. :-( I do want us to release 1.0.33 (once #2236 lands) but didn't intend to do it accidentally.
This PR reverts the accidental push. Alternately we could leave it there and just merge #2236 afterwards and then tag, whatever you want.
Edit: disabled this in the GitHub settings for the future...
> Revert "Version 1.0.33"

- CMakeLists.txt
I think we're ready to tag 1.0.33 now.
> Version 1.0.33

- CMakeLists.txt
- include/wabt/ir.h
- src/binary-reader-ir.cc
- src/c-writer.cc
- src/prebuilt/wasm2c_atomicops_source_declarations.cc
- src/template/wasm2c_atomicops.declarations.c
- src/tools/wasm2c.cc
- test/run-spec-wasm2c.py
- test/wasm2c/bad-enable-feature.txt
- test/wasm2c/spec/threads/atomic.txt
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt.h
This PR starts the work for support for the threads proposal. In this initial PR, I am only starting with support for the  Atomic memory operations part of the spec https://github.com/WebAssembly/threads/blob/cc01bf0d17ba3fb1dc59fb7c5c725838aff18b50/proposals/threads/Overview.md?plain=1#L228
Since there is a large amount of support needed, it seemed sensible to land this in chunks.
Broadly, there are three types of operations
1. atomics (load, store, add, sub, cmp_xchg)
2. fence
3. conditional variables (wait, notify)
This PR focuses on implementing operations 1 and 2 and relies on atomic builtins provided by gcc, clang and icc https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html
and the MSVC equivalents 
https://learn.microsoft.com/en-us/cpp/intrinsics/intrinsics-available-on …
> wasm2c: partial support for atomic memory ops

- include/wabt/wast-parser.h
- src/wast-parser.cc
- test/parse/empty-file.txt
- test/regress/regress-30.txt
Fixes #2246. Downgrading the error introduced in #264 to a warning.
> WastParser: allow empty modules/scripts with warning

- src/binary-reader.cc
- test/binary/bad-extra-end.txt
- test/binary/bad-function-body-size.txt
- test/binary/bad-op-after-end.txt
- test/regress/regress-28.txt
This PR lets the BinaryReader detect malformed modules in the binary format that:
- are missing END opcodes at the end of functions
- have too many END opcodes at the end of functions
- have DELEGATE opcodes outside a TRY
- have ELSE opcodes outside an IF
Previously we were only catching some of these situations later in validation. This is a prelude for a future PR that will make the spectest interpreter require that `assert_malformed` fail to parse the module (currently `assert_malformed` is treated the same as `assert_invalid`, i.e. the command passes as long as validation fails).
> binary-reader.cc: detect more malformed modules

- src/tools/wasm-interp.cc
- test/interp/run-export-with-invalid-arguments-size.txt
Closes #2242 
**text.wat**
```lisp
(module
(func (export "id") (param i32) (result i32) (local.get 0))
)
```
Example:
```bash
$ wasm-interp test.wasm --run-export=id --argument=i32:7 --argument=i32:8
Exported function 'id' expects 1 arguments, but 2 were provided
```
> Add error when parameter size does not match on wasm-interp run-export

- src/tools/spectest-interp.cc
- test/spec/binary.txt
- test/spec/exception-handling/binary.txt
- test/spec/memory64/binary.txt
- test/spec/multi-memory/binary.txt
In the spectest interpreter, currently `assert_malformed` is treated the same as `assert_invalid`. This PR requires that `assert_malformed` modules must fail in the reader (not later in validation).
This also fixes an issue where `assert_invalid` wasn't validating text modules, so spectest-interp wasn't working properly for something like `(assert_invalid (module quote "...") "")`. There aren't a lot of tests like this because usually there's no need for `(module quote)` unless it's going to be in an `(assert_malformed)`, but the memory64 tests [have one](https://github.com/WebAssembly/memory64/blob/main/test/core/address.wast#L213-L219) because overlarge offsets are moving from a malformed failure to a validation failure. So this is a prerequisite for #2253.
~~This is logically dependent …
> spectest-interp: assert_malformed must error in reader alone

- .github/actions/release-archive/action.yml
I realized branch name can have arbitrary characters problematic for filenames, especially `/`.
Fixes https://github.com/WebAssembly/wabt/pull/2254#issuecomment-1586600199
> Use tag or sha for tarball name

- include/wabt/shared-validator.h
- src/binary-reader.cc
- src/interp/binary-reader-interp.cc
- src/shared-validator.cc
- src/validator.cc
- src/wast-parser.cc
- test/binary/bad-data-without-memory.txt
- test/spec/memory.txt
- test/spec/memory64/address.txt
- test/spec/memory64/binary-leb128.txt
- test/spec/memory64/memory.txt
- test/spec/memory64/memory64.txt
- test/spec/multi-memory/memory.txt
Before memory64, the "offset" in a load/store expression was a u32, and we enforced this in the WastParser and BinaryReader. After memory64, the "offset" becomes a u64 syntactically, and the validator checks that it's <= UINT32_MAX for i32 memories.
We hadn't been correctly allowing these very large offsets in the text format (even when memory64 was enabled and the memory was i64).
(This change also eliminates the "memories" member in the BinaryReader. The BinaryReader no longer needs to keep track of the memories and their types to check well-formedness.)
~~This PR is logically dependent on #2252 (I don't think the tests will pass until #2252 is merged).~~
All of this is a long prelude to eventually fixing #2192 with a good regression test!
> memory64: when enabled, check offset range at validation-time

- src/binary-reader.cc
- src/binary-writer.cc
- test/regress/huge-offset.txt
- test/spec/memory64/binary-leb128.txt
Previously we weren't able to write a LoadStoreExpr with an offset > 2^32.
~~This depends on #2253 (the tests won't pass until it's merged).~~
> BinaryReader/Writer: roundtrip large memory64 offsets

- include/wabt/binary-reader-objdump.h
- src/binary-reader-objdump.cc
- test/dump/debug-names.txt
- test/dump/local-indices.txt
Previously, in BinaryReaderObjdumpDisassemble::BeginFunctionBody, we had:
local_index_ = objdump_state_->function_param_counts[index];
where index is the index of the function i.e. we treat the keys of function_param_counts as function indices.
However, function_param_counts is populated in OnFuncType with:
objdump_state_->function_param_counts[index] = param_count;
where index is the index of the type i.e. we treat the keys of function_param_counts as type indices.
This discrepancy would cause the locals to be incorrectly numbered in the "Code Disassembly" section.
This fixes the discrepancy by adding a new field, function_types, which maps from function indices to type indices, and is populated in BinaryReaderObjdump::OnFunction. This field is used in …
> wasm-objdump: Fix local numbering in disassembly

- .github/workflows/build.yml
- CMakeLists.txt
GitHub recently upgraded the cmake version on its Ubuntu runners, which broke our CI build with some new warnings (errors for us).
One of them is fixable (related to a deprecated Python package), but one of them is in libuv (which is a dependency of the uvwasi submodule) so less easy to fix. I added `-Wno-deprecated` to the cmake command line on GitHub actions to silence the warning for now.
> Fix CI from upgraded cmake version on GitHub Ubuntu runner

- src/prebuilt/wasm2c_atomicops_source_declarations.cc
- src/prebuilt/wasm2c_simd_source_declarations.cc
- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- src/template/wasm2c_atomicops.declarations.c
- src/template/wasm2c_simd.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- wasm2c/examples/fac/fac.c
This is a clean slate attempt to fix #2266. To fix this i looked into how clang and gcc handle floating point constraints across a host of platforms.
Godbolt link: https://godbolt.org/z/ddeWc6ees
Results are in table below.
Given this, it seems the simplest course of action that maintains functionality as is today, but fix the mips platform is to special case this. We can separately file a bug upstream (but best case scenario is that will likely get fixed only for future clang versions, so I'm not sure we can rely on just that).
Fyi, @glandium
gcc
---
x86 - both
x86-64 - both
aarch32 - only "r"
aarch64 - only "r"
mips - only "r"
mips64 - both
riscv32 - both
riscv64 -  both
sparc - both
sparc64 - both
powerpc - both
powerpc64 - both
clang
-----
x86 - both
x64 - both
aarch32 - only "r" …
> wasm2c: ensure force read constraints compile for clang on mips

- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- wasm2c/examples/fac/fac.c
Add link tracking clang bug on mips floating point constraints on inline asm
> wasm2c: add link to clang bug on mips force read constraint

- src/decompiler.cc
- test/decompile/passive-data.txt
Passive data segments do not have offsets, thus the offset ExprList is empty:
https://github.com/WebAssembly/wabt/blob/main/src/binary-reader.cc#L2812
This causes wasm-decompile to fail when trying to decompile wasm files containing passive data segments, as it tries to call InitExp on the empty offset, causing an assertion in InitExpr to fail:
https://github.com/WebAssembly/wabt/blob/main/src/decompiler.cc#L773
https://github.com/WebAssembly/wabt/blob/main/src/decompiler.cc#L688
The fix is to skip printing of the non-existent offset for passive data segments.
Fixes #2164
> decompiler.cc: passive data segments do not have offsets

- src/c-writer.cc
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
This PR has a bunch of miscellaneous cleanups in c-writer.cc, in preparation for the tail-call PR.
- ~~eliminate redundant import_syms_ SymbolSet~~ (split out to #2275)
- eliminate ResultType struct
- replace ExternalPtr (only used for tags) with TagPtr
- refer to functions with bare name (no need for * or &)
- don't use "return" for functions returning void (fixes warning on MSVC)
- add missing "static" on ExportName
- fix spacing around init_instance_import
> c-writer.cc: cleanup handling of functions & tags (NFC)

- src/wat-writer.cc
- test/desugar/call_indirect.txt
> wat-writer.cc: resolve missing type index in call_indirect

- src/tools/wasm-strip.cc
- test/strip/remove_section.txt
This adds an option to the `wasm-strip` tool. When using it, I had cases where I'd want to only cut out a specific section, like `__wasm_bindgen_unstable` while still keeping other information, like DWARF sections.
This change is just a suggestion, but I believe it would be nice to have at least as an option for the `wasm-strip` interface.
> wasm-strip: add `-R/--remove-section` option

- src/validator.cc
- test/parse/expr/bad-select-multi.txt
- test/typecheck/bad-select-value0.txt
- test/typecheck/bad-select-value1.txt
Fixes #2283
Previously, the OnSelectExpr delegate would terminate validation if the SharedValidator found an error in the expression, or if the Validator had previously found an error at any point in validating the module. This commit normalizes the behavior to match how the Validator handles other expression types.
I'd be more comfortable with this if I had been able to replicate the bug that's hinted at by the TODO we're removing (https://github.com/WebAssembly/wabt/blob/main/src/validator.cc#L527-L532), but I haven't been able to. :-( @binji any ideas? (cc: @majaha)
> Validator: normalize handling of Select in ExprVisitor Delegate

- test/run-spec-wasm2c.py
We are seeing some (spurious?) warning from gcc 12.2.
I've been seeing them locally, but they started to show up in CI as part of #2292.
> [wasm2c] Add '-Wno-array-bounds' when building wasm2c output

- include/wabt/binary-reader-logging.h
- include/wabt/binary-reader-nop.h
- include/wabt/binary-reader.h
- include/wabt/ir.h
- include/wabt/shared-validator.h
- include/wabt/type-checker.h
- src/apply-names.cc
- src/binary-reader-ir.cc
- src/binary-reader-logging.cc
- src/binary-reader.cc
- src/binary-writer.cc
- src/interp/binary-reader-interp.cc
- src/resolve-names.cc
- src/shared-validator.cc
- src/type-checker.cc
- src/validator.cc
- src/wast-parser.cc
- src/wat-writer.cc
The multi-memory proposal flipped the order of memory indexes on memory.copy (https://github.com/WebAssembly/multi-memory/pull/29). This will be necessary to update the testsuite (#2287).
> Flip order of memory indexes on memory.copy per upstream

- src/common.cc
- test/dump/bad-directory.txt
- test/pipes.txt
- test/run-tests.py
Previously, attempting to read from a pipe would result in an error: 'not a regular file', disallowing use of files like /dev/stdin or /dev/fd/3, named fifos, sockets, etc.
The tools already understand how to (try to) read from non-regular files, so this change attempts to do so when the input is not seek-able (the "regular file" capability that's in use here).
Additionally, this adds a test for the new behavior using a bash herestring and process substitution (the latter of which shows up in argv as something like `/dev/fd/NN`). Since bash isn't commonly installed on Windows, this change also introduces a new capability to filter tests to specific platforms (sorry).
> feat: treat non-seekable files as pipes

- CMakeLists.txt
Major changes since 1.0.33:
- Parse & write custom-section annotations (#2284)
- Partial wasm2c support for the threads proposal (#2233)
- wasm2c support for the tail-call proposal (#2272)
- Update multi-memory support to match upstream proposal (#2294)
- wasm-opcodecnt renamed to wasm-stats (#2298)
- wasm2c fixes for MIPS (#2274)
- Support global.get in constant expressions (#2288)
- Better spec-compliant parsing on some edge cases (#2247, #2248, #2251, #2252)
- Improved parsing and validation for memory64 (#2253, #2255, #2256)
> Version 1.0.34

- wasm2c/wasm-rt.h
This PR fixes a build issue in C++ projects that include the wasm2c output header by adding a user-provided default constructor to `wasm_rt_funcref_null_value`.
> wasm2c: initialize wasm_rt_funcref_null_value to NULL

- src/decompiler.cc
- test/decompile/basic.txt
Previously, wasm-decompile would either hit an assertion or just plain out crash (depending on how you compiled it) when decompiling wasm that has an if statement with an empty then
> decompiler.cc: fix vector oob when if has empty then

- test/harness-windows/wasm2c/floating_point.txt
- test/harness/wasm2c/floating_point.txt
- test/run-spec-wasm2c.py
Old output:
```text
out/test/harness/wasm2c/floating_point\floating_point-main.c:384: assertion failed: in w2c_floating__point__0__wasm_f32(&floating__point__0__wasm_instance, 0.f): expected 123.400002, got 0.
out/test/harness/wasm2c/floating_point\floating_point-main.c:387: assertion failed: in w2c_floating__point__0__wasm_f32(&floating__point__0__wasm_instance, 123.400002f): expected 0, got 123.400002.
out/test/harness/wasm2c/floating_point\floating_point-main.c:390: assertion failed: in w2c_floating__point__0__wasm_f64(&floating__point__0__wasm_instance, 0.0000000000000000L): expected 0, got 6.9218011802898607e-310.
out/test/harness/wasm2c/floating_point\floating_point-main.c:393: assertion failed: in w2c_floating__point__0__wasm_f64(&floating__point__0__wasm_instance, …
```
> wasm2c: Fix f64 harness

- include/wabt/binary.h
- src/binary-reader-ir.cc
- src/binary.cc
- test/dump/extended-names.txt
The tag name subsection currently has the speculative ID of 10. However, the extended-name-section proposal has now been updated to use an ID of 11 for the tag name section. This updates the NameSectionSubsection enum accordingly, as well as adding a field name section with the ID of 10.
> Update ID for tag name subsection

- wasm2c/wasm-rt-impl.c
Split out from #2332.
This makes the `g_alt_stack` variable thread-local and splits out the internal routines that handle allocation/installation. This will make it a smaller change to add the per-thread initialization API in #2332.
> wasm2c runtime: refactor handling of alternate stack (NFC)

- src/wast-parser.cc
- test/dump/br-loop-inner.txt
- test/parse/expr/bad-if-no-then.txt
- test/regress/regress-23.txt
This makes the `then` block mandatory per the spec, and parses multiple foldedinstrs in the `if` predicate (exercised by the new if.wast test -- we'll need this to update the testsuite submodule).
Closes #2347
> WastParser: tighten parsing of folded `if`

- .github/workflows/build.yml
- test/run-tests.py
- test/spec-wasm2c-prefix.c
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt.h
@wrv This closes #2339 a different way (defining `os_has_altstack_installed` even if `WASM_RT_INSTALL_SIGNAL_HANDLER` isn't set). wdyt?
> wasm2c runtime: fix mis-nesting of def'n of os_has_altstack_installed

- .github/workflows/build_release.yml
binaries built on 22.04 require glibc 2.34 and thus are incompatible with 20.04, which is still supported.
> build ubuntu release assets on ubuntu 20.04

- src/binary-reader-objdump.cc
- test/dump/noncanon-leb128-opcode.txt
`wasm-objdump --disassemble` has different treatment of locals than `--details` because it doesn't collect function types so it can properly work out how many params the function has and therefore the index number of the local.
`test/dump/noncanon-leb128-opcode.txt` demonstrates this nicely as can be seen in here. The `--details` of that test module looks like this:
```
noncanon-leb128-opcode.0.wasm:     file format wasm 0x1
Section Details:
Type[2]:
- type[0] () -> i32
- type[1] (i32) -> i32
Function[1]:
- func[0] sig=1 <main>
Table[1]:
- table[0] type=funcref initial=1 max=9
Export[1]:
- func[0] <main> -> "main"
Code[1]:
- func[0] size=37 <main>
```
so `"main"` has `sig=1`, i.e. it takes 1 parameter, `(i32) -> i32`. But because `--disassemble` mode doesn't collect function types, it …
> [wasm-objdump] set function types for correct params+locals indexing

- .github/workflows/build.yml
- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- test/wasm2c/tail-calls.txt
- wasm2c/examples/fac/fac.c
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-impl.h
- wasm2c/wasm-rt.h
This PR focuses on code cleanup for the signal handler detecting stack overflows. This PR earlier included an option to disable stack count checking, this has now been split into its own PR.
> wasm2c: Cleanup/separate code for heap and stack signal handlers

- .github/workflows/build.yml
- wasm2c/wasm-rt.h
(Continued from https://github.com/WebAssembly/wabt/pull/2354)
This PR adds an macro `WASM_RT_NONCONFORMING_STACK_UNCHECKED` to allow the embedder to unsafely remove all stack checks from wasm2c. This would mean the embedder is not conformant with the Wasm spec. This configuration is useful for embedders like RLBox which are unlikely to be affected by stack exhaustion, and don't want to pay performance penalties for this. The wasm2c build in CI that uses rlbox flags has been correspondingly updated to capture this.
> wasm2c: Add macro and tests to allow disabling stack exhaustion checks

- src/wabt.post.js
`for ([f, v] of Object.entries(FEATURES))` leads to `ReferenceError: f is not defined` in `use strict`. 
Fix it
> Fix Features of wabt.post.js can't work in strict mode

- .github/workflows/build.yml
- CMakeLists.txt
- src/c-writer.cc
- wasm2c/wasm-rt-impl.c
1. Fix wabtjs bug that missing `writeAsciiToMemory` built by new version emcc
2. Refine the code quality and CI of wabtjs
2.1: Add warning as error in emcc build
2.2 Port the test cases from https://github.com/AssemblyScript/wabt.js/tree/main/tests
> Fix emscripten build warning and add missing export

- CMakeLists.txt
- src/binary-reader-ir.cc
- src/c-writer.cc
- src/prebuilt/wasm2c_atomicops_source_declarations.cc
- src/template/wasm2c_atomicops.declarations.c
- test/run-spec-wasm2c.py
- test/wasm2c/spec/threads/atomic.txt
- wasm2c/README.md
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt-mem-impl-helper.inc
- wasm2c/wasm-rt-mem-impl.c
- wasm2c/wasm-rt.h
Implement wasm2c atomic ops and shared memory ops with C11 atomics as discussed in https://github.com/WebAssembly/wabt/pull/2268#issuecomment-1662696781
This is the first of several PRs to fully support the various primitives in the threads/shared_memory/atomics proposal.
> wasm2c: atomic and shared mem operations using c11

- wasm2c/wasm-rt.h
Minor formatting fixes for the wasm-rt.h header. Can be landed only after #2308 to avoid merge conflicts. (See only the last commit for the correct diff)
> wasm2c: Cleanup formatting of wasm-rt.h

- wasm2c/wasm-rt-impl-tableops.inc
- wasm2c/wasm-rt-impl.c
Following up on the discussion from https://github.com/WebAssembly/wabt/pull/2308#discussion_r1465921700
> wasm2c: move table ops to an include file

- src/prebuilt/wasm2c_atomicops_source_declarations.cc
- src/template/wasm2c_atomicops.declarations.c
Thanks to MEM_ADDR we don't need to think about big-endian vs little-endian for any scalar(!) operations.
> Remove unnecessary restriction

- wasm2c/wasm-rt.h
glibc was slow to implement threads, whereas pthreads are much more readily available. I'm on a platform where my glibc is old enough that it doesn't have threads.h and I'm unable to upgrade, but everything works find if I just use pthreads.
> fallback to pthreads if threads aren't available

- scripts/clang-format-diff.sh
Don't try to find upstream in detached HEAD
HEAD is detached for new branches.
- - -
This is only really relevant when creating a new branch (e.g. in a fork, before submitting a PR) but it's been bothering us *forever* so we decided to fix it.
Before: https://github.com/SoniEx2/wasm2kotlin/actions/runs/7830157694/job/21363568601
After: https://github.com/SoniEx2/wasm2kotlin/actions/runs/7830660258/job/21365229032
> clang-format-diff: fix failing CI for newly pushed branches

- src/test-interp.cc
arguably more like "implement big-endian support in rot13 test" rather than a "fix" but anyway.
> Fix rot13 test on big-endian platforms

- .github/workflows/build.yml
- scripts/TC-s390x.cmake
This adds a cross-compile workflow for s390x. Heavily based on #1971 , but runs significantly faster.
> Add s390x GHA workflow (cross-compile)

- include/wabt/common.h
- src/binary-reader-objdump.cc
- test/binary/linking-section.txt
See https://github.com/llvm/llvm-project/pull/81539
> Add support for new WASM_SEGMENT_FLAG_RETAIN segment flag

- .github/workflows/build.yml
Fix random sanitizer crashes encountered in #2400. Fix is from 
https://github.com/actions/runner/issues/3207#issuecomment-2000066889
> wasm2c: Fix periodic ASLR related crashes in sanitizer builds

- test/run-spec-wasm2c.py
Fixes #2403 
simde obviously requests loop vectorization, but we shouldn't fail for missed vectorizations as we're more focused on testing for correctness.
> Suppress pass-failed warnings/errors

- src/prebuilt/lexer-keywords.cc
- src/wast-lexer.cc
This file is auto-generated but I had manually edited it #2091.
Instead, disabled the clang fallthrough warnings when including this file.
> Revert manual changes to src/prebuilt/lexer-keywords.cc. NFC

- .github/workflows/build_release.yml
follow up to #2406, just copied the changes from the CI workflow over to the release workflow.
> Align release workflow with CI, for Apple Silicon

- include/wabt/type-checker.h
- src/type-checker.cc
I was doing some local bench marking and found a significant amount of wasm-validate's time came from copying (and then destroying) temporary vectors here. [Currently `CheckSignature()` is calling `PrintStackIfFailed()`]((https://github.com/WebAssembly/wabt/blob/65b61e0a3fde8c4fc82cee53bd5cdd0959b6ffa6/src/type-checker.cc#L257)) and passing `sig` (which is already a `TypeVector), whic creates a copy. This change eliminates the unnecessary vector copy and adds a static assertion that should prevent this from happening again.
> Avoid creating temporary vector copies when checking signature

- wasm2c/wasm-rt-mem-impl-helper.inc
- wasm2c/wasm-rt-mem-impl.c
Building wasm2c'c wasm_rt with the Android NDK results in the following error
```
third_party/wabt/wasm2c/wasm-rt-mem-impl.c:28:9: error: 'PAGE_SIZE' macro redefined [-Werror,-Wmacro-redefined]
#define PAGE_SIZE 65536
^
third_party/android/ndk/stable/toolchains/llvm/prebuilt/linux-x86_64/bin/../real-bin/../sysroot/usr/include/sys/user.h:37:9: note: previous definition is here
#define PAGE_SIZE 4096
^
1 error generated.
```
This PR fixes that.
> Fix compiling wasm2c's runtime library with Android NDK(macro definition conflicts with sysroot)

- CMakeLists.txt
With #2447 merged, Halide would like to depend on a version of WABT with this fix in place.
Would you be willing to cut a release as version 1.0.36?
Thanks!
ATTN @steven-johnson
> Bump version to 1.0.36

- src/binary-reader-ir.cc
- src/binary-reader.cc
- test/binary/bad-alignment.txt
- test/regress/undefined-shifts.txt
Chasing https://crbug.com/oss-fuzz/51561
Let's see if this breaks anything...
The issue only triggers if both conditions are true:
- Multi-memory is enabled
- Alignment (masked) is between 32 and 63
> Harden against invalid alignment

- CMakeLists.txt
Installs missing include files after split.
Fixes #2451
> Install wasm-rt-impl include files

- src/c-writer.cc
- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- test/wasm2c/tail-calls.txt
- wasm2c/examples/fac/fac.c
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt.h
For older CPUs (older than Ivybridge on Intel), the segment registers had to be set using system calls rather than userspace instructions. Update the segue implementation to fallback to system calls if userspace instructions are not supported.
> wasm2c: Segue support for CPUs without wrgsbase instructions

- src/interp/interp.cc
- src/tools/spectest-interp.cc
- test/regress/recursion-issue.txt
The interpreter could overflow the stack without trapping properly in `call_indirect` situations. While it would set the `out_trap` to the trap reason, it would return `RunResult::Ok` and the interpreter code would only check `RunResult::Ok` to decide whether or not to keep running. In other words, while the stack overflow meant the interpreter wouldn't push a frame onto the call stack, the interpreter loop would continue advancing instructions, resulting in instructions after the runaway `call_indirect` running.
If the offending `call_indirect` didn't have return values, it would be as if the call returned normally. If it did have return values, nothing would be pushed onto the value stack, yet the return types would be pushed onto the type stack. With careful manipulation of the …
> [wasm-interp] Fix memory corruption with recursive call_indirect

- .github/workflows/build.yml
- include/wabt/ir.h
- src/binary-reader-ir.cc
- src/c-writer.cc
- test/wasm2c/check-imports.txt
- test/wasm2c/hello.txt
- test/wasm2c/tail-calls.txt
Clang 17(?) tightened UBSAN checks, so that you now get this:
```
- test/wasm2c/spec/call_indirect.txt
expected error code 0, got 1.
STDERR MISMATCH:
--- expected
+++ actual
@@ -0,0 +1,3 @@
+out/test/wasm2c/spec/call_indirect/call_indirect.0.c:2144:12: runtime error: call to function w2c_call__indirect__0__wasm_f0 through pointer to incorrect function type 'unsigned int (*)(void *)'
+/home/runner/work/wabt/wabt/out/test/wasm2c/spec/call_indirect/call_indirect.0.c:1925: note: w2c_call__indirect__0__wasm_f0 defined here
+SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior out/test/wasm2c/spec/call_indirect/call_indirect.0.c:2144:12 
STDOUT MISMATCH:
--- expected
+++ actual
@@ -1 +0,0 @@
-134/134 tests passed.
```
This happens because emitted functions use a typed module instance, while …
> wasm2c: Use wrappers for function references

- src/type-checker.cc
- test/spec/ref_is_null.txt
Fixes #2453 in a bit of a silly way. (Conveniently, we already have tests for this, but nobody noticed they were broken.)
> Fix error message for ref.is_null

- src/binary-reader.cc
- test/regress/data-count-without-data-section.txt
Closes #2436
Fixes #2310
Fixes #2311
Fixes #2431
> Fix handling of data count without data section

- src/type-checker.cc
- test/typecheck/bad-callref-empty.txt
- test/typecheck/bad-callref-int32.txt
- test/typecheck/bad-callref-null.txt
Same issue as #2471 but for `call_ref`.
We don't believe there's a prior issue for this.
> Fix call_ref on empty stack

- src/interp/binary-reader-interp.cc
- test/regress/interp-ehv3-locals.txt
Fixes the value stack size of the catch handler. There were two (related) issues here:
- The previous code used `func_->locals.size()` as soon as the function was available, but it hadn't processed the function's locals yet, so it was always empty. (This might not matter in practice, as it's only used by the "function-wide catch handler", which just rethrows.)
- The previous code didn't take the function's locals into account when computing the value stack height (relative to the function frame) for a try-catch block. So, it would drop the locals when catching an exception.
Closes #2476 
(Split from #2470 )
> wasm-interp: Fix catch handlers' value stack sizes

- src/c-writer.cc
- test/regress/wasm2c-ehv3-setjmp-volatile.txt
It is UB to read local variables after a call to `setjmp` returns, if those variables have been modified between `setjmp` and `longjmp`, unless they're marked as `volatile`. This marks them as `volatile`.
Closes #2469
> wasm2c: Fix handling of locals in setjmp targets

- src/wast-parser.cc
- test/spec/i32.txt
- test/spec/i64.txt
Previously, the parser would return result::Error, but would not populate an error message.
> Raise parse error on NaN in i32 and i64 literals

- src/c-writer.cc
- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- test/wasm2c/tail-calls.txt
- wasm2c/examples/fac/fac.c
- wasm2c/wasm-rt-impl.c
- wasm2c/wasm-rt.h
The `WASM_RT_USE_SEGUE` macro was previously overloaded for two checks:
1. Check if Segue is supported by the current compiler/arch/OS combination
2. Check if the current module only uses one memory, as we do not use Segue for modules using multiple memories
Check 2 means that `WASM_RT_USE_SEGUE` is only available in the generated C file, and not in the runtime (`wasm-rt-impl.c`).
However, the runtime needs this information as it must include certain headers only if Segue is supported (Check 1 above), and thus this macro must be available in `wasm-rt.h`. We thus split this macro into two parts `WASM_RT_USE_SEGUE` and `WASM_RT_USE_SEGUE_FOR_THIS_MODULE` to address the two use cases: "check if Segue is supported" and "check if Segue should be used for the current module"
> wasm2c: Cleanup of handling of WASM_RT_USE_SEGUE macro

- include/wabt/type.h
`exnref`'s opcode is -0x17:
https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md#exnref
> [EH] Fix exnref's opcode

- src/wat-writer.cc
- test/regress/write-memuse.txt
wat-writer.cc currently prints active data segments (targeting a non-0 memory) using the Wasm 1.0 format:
```wasm
(data 𝑥:memidx_𝐼 ...)
```
... but the multi-memory feature really requires the current format:
```wasm
(data id? 𝑥:memuse_𝐼 ...)
memuse_𝐼 ::= (memory 𝑥:memidx_𝐼)
```
This PR adjusts wat-writer.cc to print data segments (that target a non-0 memory) with the post-1.0 syntax. This only affects modules that use multi-memory feature so I don't think it will break anything.
Before this PR, WABT wasn't able to roundtrip this module with debug-names enabled:
```wasm
(memory 0)
(memory $k i64 (data))
```
... because after round-tripping it would be printed like this (which is invalid because it's parsed so that the data segment itself has id $k but the memuse is memory 0 which is …
> wat-writer.cc: update text serialization of data memuse

- test/regress/write-memuse.txt
- test/run-roundtrip.py
Since #1661, run-roundtrip.py always converts wat0 -> wasm1 -> wat2 -> wasm3 and fails if any of the conversions fails. With the `--stdout` argument, it then prints the wat2 file; otherwise, it compares the wasm1 and wasm3 binaries and fails if they're different.
This PR makes the roundtrip comparison always happen (even with `--stdout`), unless an argument is given that asks wat2wasm to change the binary on purpose (in particular: `--generate-names`, which changes the name section, or `--inline-exports` which can reorder exports).
This didn't catch any bugs, but it gives some more test coverage.
(@SoniEx2)
> test/run-roundtrip.py: test roundtrip even with --stdout

- wasm2c/wasm-rt-impl.c
Define the fsgabase capability lookup to
HWCAP2_FSGSBASE as per
https://www.kernel.org/doc/html/latest/arch/x86/x86_64/fsgs.html#fsgsbase-instructions-enablement
> wasm2c: minor code cleanup for OS checks for segue

- src/wast-parser.cc
- test/regress/regress-quote.txt
- test/wast2json/test-invalid-quoted-modules.txt
`ParseWatModule` leaves the module as a nullptr on failure. The attached test could cause a segfault in `wast2json` before this PR.
> wast-parser.cc: Fix a crash from failing (module quote ...)

- include/wabt/interp/interp.h
- src/interp/binary-reader-interp.cc
- src/interp/interp.cc
- src/interp/istream.cc
- test/spec/exception-handling/throw_ref.txt
- test/spec/exception-handling/try_table.txt
> interp: Implement EHv4

- README.md
Add `Installation` section to readme to help the next person ❤️
> add installation section to README.md

- src/c-writer.cc
- src/prebuilt/wasm2c_atomicops_source_declarations.cc
- src/prebuilt/wasm2c_simd_source_declarations.cc
- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- src/template/wasm2c_atomicops.declarations.c
- src/template/wasm2c_simd.declarations.c
- test/run-spec-wasm2c.py
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- test/wasm2c/tail-calls.txt
- wasm2c/examples/fac/fac.c
- wasm2c/wasm-rt-mem-impl-helper.inc
- wasm2c/wasm-rt.h
(Sequenced behind #2506)
This PR allows "software-bounds-checked" memories and "guard-page-checked" memories to coexist in the same module. 
It creates two versions of every memory operation: an unrestricted version (that works with any memory) and a `_default32` version (for memories with default page size and i32 indexing).
The unrestricted version calls `MEMCHECK_GENERAL`, which does a 64-bit software `RANGE_CHECK` to check that the operation reads/writes within the bounds of the memory.
The `_default32` version calls `MEMCHECK_DEFAULT32`, which is the same as the old `MEMCHECK`: if the runtime declares `WASM_RT_MEMCHECK_GUARD_PAGES`, it will do nothing. Otherwise it will do a 32-bit software `RANGE_CHECK` (which seems to be one less instruction than the 64-bit `RANGE_CHECK`).
This is …
> wasm2c: parametrize memory bounds checks on a per-memory basis

- .github/workflows/build.yml
macos-12 is no longer available, this changes it to macos-13 (latest available x64 macos)
macos-14 is changed to macos-latest (arm64)
> CI: Use latest macOS images

- src/c-writer.cc
- src/prebuilt/wasm2c_atomicops_source_declarations.cc
- src/prebuilt/wasm2c_simd_source_declarations.cc
- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- src/template/wasm2c_atomicops.declarations.c
- src/template/wasm2c_simd.declarations.c
- test/run-spec-wasm2c.py
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- test/wasm2c/tail-calls.txt
- wasm2c/examples/fac/fac.c
- wasm2c/wasm-rt-mem-impl-helper.inc
- wasm2c/wasm-rt.h
The PR updates the bulk memory operations (memory.fill, memory.copy, table.fill, etc.) to support 64-bit addresses and counts, and standardizes on a 64-bit version of RANGE_CHECK everywhere.
Previously we were only taking u32's for these arguments, even with memory64 enabled. (I don't think the memory64 tests check the ability to use memory.copy or the other operations beyond the first 4 GiB of a memory -- I wonder if there would be a way to add this as an "intensive" test if people don't mind having to allocate >4 GiB to run the test.)
This is a stepping-stone to being able to mix software-bounds-checked i64 memories and "guard-page-checked" i32 memories in the same module (#2507) and supporting custom-page-sizes (#2508).
> wasm2c: update memory/table operations to use u64 + harmonize checks

- CMakeLists.txt
wabt doesn't currently build when targeting 10.13 because it uses std::optional::value which is not available on 10.13.
See: #2527
> Set CMAKE_OSX_DEPLOYMENT_TARGET to 10.14 in CMakeLists.txt

- .github/actions/release-archive/action.yml
- .github/workflows/wabt-cifuzz.yml
Since v3 is no longer usable, this changes it to v4
> CI: Update to upload-artifact v4

- .github/actions/release-archive/action.yml
apparently this is a thing https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
tho they did go back on it https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/
but it seems like a good idea to switch anyway
> CI: Use safer GITHUB_OUTPUT

- scripts/clang-format-diff.sh
git clang-format appears to now return an exit status instead of always succeeding, and the change broke the script. this fixes it.
> Fix lint task

- README.md
- src/c-writer.cc
- src/tools/wasm2c.cc
- test/run-spec-wasm2c.py
- test/spec-wasm2c-prefix.c
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/spec/custom-page-sizes/custom-page-sizes-invalid.txt
- test/wasm2c/spec/custom-page-sizes/custom-page-sizes.txt
- wasm2c/README.md
- wasm2c/examples/rot13/main.c
- wasm2c/wasm-rt-mem-impl-helper.inc
- wasm2c/wasm-rt-mem-impl.c
- wasm2c/wasm-rt.h
(Sequenced behind #2507)
This adds support for the custom-page-sizes proposal to wasm2c. It passes the custom-page-sizes tests (including the ones in https://github.com/WebAssembly/custom-page-sizes/pull/31 that haven't made it to the testsuite repo and WABT yet).
> wasm2c: support the custom-page-sizes proposal

- include/wabt/opcode.def
- src/interp/binary-reader-interp.cc
- src/interp/interp.cc
- src/interp/istream.cc
This fills in some TODOs, and cleans up some other issues, relevant for GC later on.
We tried our best to make this efficient, hence the custom wabt opcodes.
> wasm-interp: Handle refs_ correctly

- src/c-writer.cc
- src/interp/binary-reader-interp.cc
- test/spec/tail-call/return_call.txt
- test/spec/tail-call/return_call_indirect.txt
- test/wasm2c/spec/tail-call/return_call.txt
- test/wasm2c/spec/tail-call/return_call_indirect.txt
- test/wasm2c/tail-calls.txt
This PR:
- updates the testsuite, adding new tail-call tests (https://github.com/WebAssembly/spec/pull/1872) that include imported functions (https://github.com/WebAssembly/wabt/pull/2420#issuecomment-2114055646) and multi-value (https://github.com/WebAssembly/wabt/pull/2491#issuecomment-2461257731)
- changes the return_call and return_call_indirect .txt files to run the "wasm-3.0" versions of the tests (these are the ones with the changes -- the old "tail-call" proposals directory is not being updated any more)
- fixes an assertion failure in the interpreter that is triggered only when tail-calling a function in the presence of function imports (this bug was partly fixed in #1762 and I think this... further fixes it)
- fixes the wasm2c codegen in the presence of imports and multi-param …
> Fix tail-call handling in interpreter and wasm2c

- fuzzers/read_binary_interp_fuzzer.cc
- fuzzers/read_binary_ir_fuzzer.cc
- fuzzers/wasm2wat_fuzzer.cc
- fuzzers/wasm_objdump_fuzzer.cc
- fuzzers/wat2wasm_fuzzer.cc
These will not run until oss-fuzz updates to match, but this is how it should be done and how other projects (e.g. ffmpeg) do it.
> Pull fuzzers from oss-fuzz into tree

- .github/workflows/build.yml
It seems -Wno-error=deprecated doesn't work, so use -DCMAKE_ERROR_DEPRECATED=OFF.
Depends on #2578
> Enable CMake deprecation warnings

- include/wabt/type.h
- src/binary-reader.cc
- src/type-checker.cc
- test/dump/typed-func-ref-signature.txt
Code is based on the work of SoniEx2.
> Add Type comparison methods

- include/wabt/wast-parser.h
- src/test-wast-parser.cc
- src/wast-parser.cc
Enabled by default, this option implements the current behavior of WABT when it encounters "(module binary ...)" script modules. That is, it parses the binary module, reporting any errors that it sees.
When disabled, the binary module will be passed back to the WAST parser as unvalidated raw bytes. This allows for the use of WABT in places which want to provide invalid modules to module loaders (e.g. spec test runners).
Fixes https://github.com/WebAssembly/wabt/issues/2561.
> [wast-parser] Add parse_binary_modules option

- include/wabt/ir.h
- include/wabt/wast-parser.h
- src/wast-parser.cc
- test/dump/typed-func-refs-locals.txt
- test/roundtrip/typed-func-refs.txt
- test/typecheck/missing-ref.txt
This patch moves (and reworks) param_type_names / result_type_names out of IR to the parser, and fix the following issues:
Parse (ref index) form, not just (ref $name) form
Resolve references in types and locals
Display location when a named reference is not found
> Move parser related data from IR to the parser and improve reference type parsing

- src/prebuilt/wasm2c_source_declarations.cc
- src/template/wasm2c.declarations.c
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/export-names.txt
- test/wasm2c/hello.txt
- test/wasm2c/minimal.txt
- test/wasm2c/tail-calls.txt
Removing the use of inline enum definitions to (1) improve readability and (2) improve compatibility with some source analysis tools we are playing with.
> wasm2c: remove use of inline enum declarations

- src/c-writer.cc
- test/wasm2c/add.txt
- test/wasm2c/check-imports.txt
- test/wasm2c/hello.txt
- test/wasm2c/tail-calls.txt
Enum types in variadic functions aren't guaranteed to work. This is because enums for variadics undergo default argument promotion (promotion to int), and thus the user of `va_arg` should always get the argument as an `int`. Thus enums in varargs function would break on any compiler whose underlying representation is not an int (e.g., when using gcc's `-fshort-enums` flag)
https://stackoverflow.com/questions/73278375/do-enum-types-undergo-default-argument-promotion
https://stackoverflow.com/questions/24580503/error-when-pass-enum-in-a-function-with-variable-arguments/24580800#24580800
This pattern is used in the get_func_type function emitted as part of wasm2c modules. This PR changes this API to always use `int` for the var args.
> wasm2c: Remove enum types from variadic get_func_type API

- src/binary-reader-objdump.cc
- test/binary/bad-init-expr-callindirect.txt
Fixes the fuzzer bug in #2567
I noticed all objdump logs are guarded by `if (!in_function_body)`. The code crashes without this check.
> Add missing in_function_body check to objdump

- include/wabt/shared-validator.h
- src/shared-validator.cc
- src/validator.cc
- src/wast-parser.cc
- test/binary/bad-reference-indicies.txt
- test/gen-wasm.py
- test/parse/bad-references.txt
> Validate type references by index

- wasm2c/wasm-rt-mem-impl.c
QEmu's mprotect implementation doesn't seem to handle calls with a zero size
> wasm2c: add check to avoid mprotect on zero sizes
