WebAssembly/wabt

README.rst, test/spec.js, test/spec/select.txt, test/wasm.js
PTAL. Depends on https://codereview.chromium.org/1770383002/
=> Rename _WASMEXP_ to Wasm.

test/run-gen-wasm-interp.py, test/run-gen-wasm.py, test/run-interp.py, test/run-js.py, test/run-roundtrip.py, test/run-tests.py, test/utils.py
Implements #42 
Closes #44 ?
Added an option to run tests in series.
Added an option to pause at first error and prompts to retry the command with verbose (in series only) then prompts if should continue testing.
Prints the last command executed on failing tests in the summary to help reproduce the error.
Theses options helps to reproduced and see what is causing a test to fail
=> Tests verbosity

src/wasm-binary-reader.c, test/binary/bad-data-size.txt, test/binary/bad-export-func.txt, test/binary/bad-function-body-count.txt, test/binary/bad-function-body-size.txt, test/binary/bad-function-local-type.txt, test/binary/bad-function-names-too-many.txt, test/binary/bad-function-param-type.txt, test/binary/bad-function-result-type.txt, test/binary/bad-function-sig.txt, test/binary/bad-function-too-many-results.txt, test/binary/bad-import-sig.txt, test/binary/bad-memory-init-max-size.txt, test/binary/bad-memory-init-size.txt, test/binary/bad-memory-max-size.txt, test/binary/bad-segment-no-memory.txt, test/binary/bad-start-func.txt, test/binary/bad-type-form.txt, test/binary/bad-version.txt, test/binary/basic.txt, test/gen-wasm.py
=> fix binary tests for binary_0xc

src/wasm-binary-reader.c, src/wasm-binary-writer.c, test/dump/debug-names.txt, test/roundtrip/generate-func-names.txt, test/roundtrip/generate-func-type-names.txt, test/roundtrip/generate-if-label-names.txt, test/roundtrip/generate-import-names.txt, test/roundtrip/generate-label-names.txt, test/roundtrip/generate-some-names.txt
Also fix writing user-defined sections.
=> fix roundtrip tests for binary_0xc

README.md
=> Update Travis links for wabt

src/wasm-binary-reader.c, src/wasm-binary-writer.c, test/dump/brtable-empty.txt, test/dump/brtable.txt
=> br_table depth immediates are LEB128

src/wasm-ast-checker.c, src/wasm-binary-reader-interpreter.c, test/dump/expr-brif.txt, test/interp/expr-brif.txt, test/parse/expr/expr-brif.txt
=> br_if keeps its value on the stack

CMakeLists.txt, Makefile, scripts/travis-test.sh, src/wasm-binary-reader-opcnt.c, src/wasm-binary-reader-opcnt.h, src/wasmopcodecnt.c, test/find_exe.py, test/opcodecnt/basic.txt, test/run-gen-wasm.py, test/run-opcodecnt.py, test/run-roundtrip.py, test/run-tests.py
Also rename the last few places using SexprWasm, WasmWast. Make
formatting a little nicer too.
Fixes #156.
=> Add wasmopcodecnt tests

test/dump/block.txt, test/dump/expr-br.txt, test/interp/expr-block.txt, test/interp/expr-br.txt, test/parse/expr/block-return.txt, test/parse/expr/return-block.txt
Converted a select few  tests from AST format to new "flat" format
=> updated selected test files to new flat format #139

test/dump/basic.txt, test/dump/basic_dump_only.txt, test/dump/binary.txt, test/dump/block-257-exprs-br.txt, test/dump/block-257-exprs.txt, test/dump/block.txt, test/dump/br-block-named.txt, test/dump/br-block.txt, test/dump/br-loop-inner-expr.txt, test/dump/br-loop.txt, test/dump/brif-loop.txt, test/dump/brif.txt, test/dump/brtable-empty.txt, test/dump/brtable.txt, test/dump/call.txt, test/dump/callimport.txt, test/dump/expr-br.txt, test/interp/expr-block.txt, test/interp/expr-br.txt, test/parse/expr/block-return.txt, test/parse/expr/return-block.txt
few more tests from dump directory added
=> Update tests syntax to new flat syntax

appveyor.yml, scripts/gen-emscripten-exported-json.py
Also update gen-emscripten-exported-json.py to comply (almost) with PEP8
=> Add appveyor.yml from Binaryen

appveyor.yml, scripts/gen-emscripten-exported-json.py
to satisfy Appveyor's version of flake8
=> Move import to top of Python file

test/parse/expr/bad-load-align-misspelled.txt, test/parse/expr/bad-load-align-negative.txt, test/parse/expr/bad-load-align-not-pot.txt, test/parse/expr/bad-load-float-sign.txt, test/parse/expr/bad-load-offset-negative.txt, test/parse/expr/bad-load-type.txt, test/parse/expr/bad-nop.txt, test/parse/expr/bad-return-multi.txt, test/parse/expr/bad-setglobal-name-undefined.txt, test/parse/expr/bad-setglobal-undefined.txt, test/parse/expr/bad-setlocal-name-undefined.txt, test/parse/expr/bad-setlocal-name.txt, test/parse/expr/bad-setlocal-no-value.txt, test/parse/expr/bad-setlocal-undefined.txt, test/parse/expr/bad-store-align-not-pot.txt, test/parse/expr/bad-store-align.txt, test/parse/expr/bad-store-float.sign.txt, test/parse/expr/bad-store-offset-negative.txt, test/parse/expr/bad-store-type.txt
deleted the old branch and started afresh with this new branch , a few tests to start off with
=> more parse tests converted #139

test/typecheck/bad-assertreturn-invoke-type-mismatch.txt, test/typecheck/bad-assertreturn-type-mismatch.txt, test/typecheck/bad-binary-type-mismatch-1.txt, test/typecheck/bad-binary-type-mismatch-2.txt, test/typecheck/bad-br-multi-type.txt, test/typecheck/bad-brtable-type-mismatch.txt, test/typecheck/bad-call-result-mismatch.txt, test/typecheck/bad-call-type-mismatch.txt, test/typecheck/bad-callimport-type-mismatch.txt, test/typecheck/bad-callindirect-func-type-mismatch.txt, test/typecheck/bad-callindirect-type-mismatch.txt, test/typecheck/bad-cast-type-mismatch.txt
=> Converted typecheck tests to flat syntax

src/binary-reader-objdump.c, src/binary-reader-opcnt.c, test/dump/debug-import-names.txt, test/dump/global.txt, test/dump/import.txt
Also, fix bug in on_error handling.
=> Improve handling of globals in wasmdump

src/binary-reader-objdump.c, src/binary-reader.c, src/binary-reader.h, src/binary-writer.c, src/binary.h, test/binary/user-section.txt, test/dump/debug-import-names.txt, test/dump/debug-names.txt
As per https://github.com/WebAssembly/design/pull/87
=> Rename `user` sections to `custom` sections

CMakeLists.txt, src/binary-writer.c, src/binary.c, src/binary.h
This function is also useful for the linker proof-of-concept
I'm working on.
=> Add wasm_get_section_name to binary.h

src/binary-writer-spec.c
`\` are used in paths on Windows and need to be escaped to be valid json
=> Escape source filename when writing to json

CMakeLists.txt
Added symlinks to 'make clean' rule so no broken symlinks are left hanging around after a clean
=>  Added symlinks to 'make clean' rule 

src/common.c, src/common.h, src/tools/wasm-interp.c
These are needed to support the wasm-link utility
that will hopefully be landing soon.
=> Add a couple of string slice utility functions

src/config.h.in
=> On FreeBSD, alloca is in stdlib.h

src/binary-writer.c, src/binary-writer.h, src/tools/wast2wasm.c, test/parse/assert/assertinvalid-binary-module.txt, test/parse/empty-file.txt
=> Fail when running wast2wasm w/ no module

src/binary-writer-spec.c
When running wast2wasm with --spec, but without -o (so no .json file is
written), all modules were being written as .0.wasm, .1.wasm, etc. This
change will prevent those modules from being written too.
=> wast2wasm: don't write .0.wasm, w/ --spec

src/binary-reader-ast.c, test/regress/regress-7.txt, test/regress/regress-8.txt
This fixes issue #304.
Unfortunately not possible to test the same issue with tables and memories because those are restricted to 0 or 1.
=> Fix bug in wasm2wast w/ many imports

test/run-tests.py
This replaces the ad-hoc mechanism we used before with threads. We'll
have to keep an eye on the Travis build, as we switched away from
multiprocessing before because it would flake occasionally. Hopefully
multiprocessing.pool doesn't have the same issue.
This also removes should_stop_on_error from the RunMultiThreaded path,
as it isn't allowed anyway (it early-outs when parsing arguments).
=> Use multiprocessing.pool

src/array.h, src/ast-lexer.cc, src/ast-parser-lexer-shared.cc, src/ast-parser.y, src/ast.cc, src/ast.h, src/binary-reader-ast.cc, src/binary-reader-interpreter.cc, src/binary-writer-spec.cc, src/common.cc, src/common.h, src/interpreter.cc, src/interpreter.h, src/prebuilt/ast-lexer-gen.cc, src/prebuilt/ast-parser-gen.cc, src/tools/wasm-interp.cc, src/tools/wasm-link.cc, src/tools/wasm2wast.cc, src/tools/wasmdump.cc, src/tools/wasmopcodecnt.cc, src/vector.cc, src/vector.h, src/writer.cc, src/writer.h
Also switch some void* -> char*, because it removes some unnecessary
casts. C++ does not like void*.
=> Use new/delete instead of malloc/free

src/ast-parser.y, src/prebuilt/ast-parser-gen.cc
=> Check that bison stacks are trivially copyable

CMakeLists.txt
This should make the waterfall's Travis build happy
=> Define __STDC_*_MACROS for all non-MSVC compilers

src/literal.cc
Use parse_double_hex and parse_float_hex to parse float hexstring on Windows because some crt implementations of strtof and strtod doesn't support hexstrings.
This is related to #362.
After some more thought I decided to approach this issue differently.
First of all, I don't think we should try to keep supporting Visual Studio 2013. There are way too many things that needs to be changed to support it and I don't think it is worth it.
However, in chakra, we are using an older version of the crt that has that strtof/strtod bug. The main issue being not supporting hexstrings. Which this pull request fixes.
There is some precision bugs in the implementation which is not a big deal and hopefully we'll update the crt version soon and this problem will go away.
I hope that this change is not too …
=> Windows parse hexfloat

test/run-tests.py
Without this it can be hard to dig down that find out
exactly what is being run
=> Add -p option to run-tests.py to show the commands it runs

CMakeLists.txt, src/ast-writer.cc, src/ast-writer.h, src/binary-reader-interpreter.cc, src/binary-reader-linker.h, src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-objdump.cc, src/binary-reader.h, src/binary-writer-spec.cc, src/binary-writer-spec.h, src/binary-writer.cc, src/binary-writer.h, src/interpreter.cc, src/interpreter.h, src/stream.cc, src/stream.h, src/tools/wasm-interp.cc, src/tools/wasm-link.cc, src/tools/wasm2wast.cc, src/tools/wasmdump.cc, src/tools/wasmopcodecnt.cc, src/tools/wast-desugar.cc, src/tools/wast2wasm.cc, src/writer.cc, src/writer.h
I also took the opportunity to make classes for
ASTWriter/BinaryWriter/BinaryWriterSpec.
=> Refactor Stream/Writer; write as C++

src/binary-reader-linker.cc, src/binary-reader-linker.h, src/tools/wasm-link.cc, src/wasm-link.h
Make things a little more C++-y and some helper methods
to make the code more clear.
=> [wasm-link] Add some helper methods to LinkerInputBinary

src/binary-writer.cc, test/link/large_code_section.txt
=> Update relocation offsets when fixing up section size

src/tools/wasm2wast.cc, src/wat-writer.cc, src/wat-writer.h, test/help/wasm-wast.txt, test/roundtrip/inline-export-func.txt, test/roundtrip/inline-export-global.txt, test/roundtrip/inline-export-memory.txt, test/roundtrip/inline-export-table.txt, test/run-roundtrip.py
=> Add option to generate inline exports in wat-writer

src/apply-names.cc, src/binary-reader-interpreter.cc, src/binary-reader-ir.cc, src/binary-writer-spec.cc, src/binary-writer.cc, src/binding-hash.cc, src/binding-hash.h, src/generate-names.cc, src/interpreter.cc, src/ir.cc, src/ir.h, src/prebuilt/wast-parser-gen.cc, src/resolve-names.cc, src/tools/wast-desugar.cc, src/tools/wast2wasm.cc, src/validator.cc, src/wast-parser-lexer-shared.h, src/wast-parser.y, src/wat-writer.cc
* Remove destroy_var; use destructor instead
* Add Var copy/move constructor/assignment operator.
=> Use CamelCase names and member functions in ir.h

src/option-parser.cc, src/option-parser.h, src/tools/wasm-interp.cc, src/tools/wasm-link.cc, src/tools/wasm-objdump.cc, src/tools/wasm-opcodecnt.cc, src/tools/wasm2wast.cc, src/tools/wast-desugar.cc, src/tools/wast2wasm.cc, test/help/wasm-interp.txt, test/help/wasm-link.txt, test/help/wasm-objdump.txt, test/help/wasm-opcodecnt.txt, test/help/wasm2wast.txt, test/help/wast-desugar.txt, test/help/wast2wasm.txt, test/too-many-arguments.txt
Added a new feature where you can specify how many arguments are
allowed. It is an error to provide too many or too few.
Also add "help" tests for all of the other tools.
=> Make OptionParser into C++ class

README.md
=> Add some documentation for building on Windows

src/binary-reader-ir.cc, src/binary-reader-ir.h, src/binary-writer-spec.cc, src/common.h, src/emscripten-helpers.cc, src/ir.cc, src/ir.h, src/prebuilt/wast-parser-gen.cc, src/prebuilt/wast-parser-gen.hh, src/source-error-handler.cc, src/source-error-handler.h, src/tools/wasm-interp.cc, src/tools/wasm2wast.cc, src/validator.cc, src/validator.h, src/wast-parser.y, test/binary/bad-typecheck-missing-drop.txt, test/help/wasm2wast.txt, test/run-roundtrip.py
* Modify Location so it can reference a binary file offset
* Set node locations in BinaryReaderIR
* Modify SourceErrorHandler to print text or binary locations
=> Add validation to wasm2wast

CMakeLists.txt, src/apply-names.cc, src/binary-reader-interpreter.cc, src/binary-reader-ir.cc, src/binary-reader-linker.cc, src/binary-reader-logging.cc, src/binary-reader-objdump.cc, src/binary-reader-opcnt.cc, src/binary-reader.cc, src/binary-writer-spec.cc, src/binary-writer.cc, src/common.h, src/generate-names.cc, src/literal.cc, src/opcode.cc, src/opcode.h, src/resolve-names.cc, src/test-string-view.cc, src/test-utf8.cc, src/utf8.cc, src/validator.cc, src/wat-writer.cc
This matches the wording prefered by llvm.
=> Consistent comments when ending anonymous namespace

CMakeLists.txt, src/ir.cc, src/ir.h, src/opcode.h, src/tracing.cc, src/tracing.h, src/wat-writer.cc, test/desugar/fold-catch.txt, test/desugar/fold-export-throw.txt, test/desugar/fold-try-as-argument.txt, test/desugar/fold-try.txt
This is a rebased version of PR #531.
=> Fix wat writer to fold exception handling constructs.

src/binding-hash.h, src/common.cc, src/common.h, src/ir.cc, src/ir.h, src/prebuilt/wast-parser-gen.cc, src/tools/wasm-interp.cc, src/wast-parser.y
This fixes some TODO's although may not be exactly right but is passing
the tests for me.
I've initialized all union fields to 0 and I assume the compiler will
remove any unnecessary initialization.
=> Add default constructor for Location and Const

test/dump/try-details.txt, test/dump/try-exports-details.txt, test/dump/try-imports-details.txt, test/run-objdump.py
Added more test examples for wasm-objdump, and requested by @binji.
=> Add more test examples for wasm-objdump.

src/interpreter.cc, src/interpreter.h, src/tools/wasm-interp.cc, src/wast-lexer.h
There's still more to be done, but this is a decent cleanup.
=> Use templates instead of macros in interpreter

src/binary-reader-interpreter.cc, src/interpreter.cc, src/interpreter.h, src/tools/wasm-interp.cc, src/wast-lexer.h
Use std::string or string_view instead.
=> Remove StringSlice from interpreter

src/common.h, src/interpreter.h, src/intrusive-list.h, src/tracing.h
The pattern should be
```
template <typename... Args>
void foo(Args&&... args) {
bar(std::forward<Args>(args)...);
}
```
=> Properly forward argument packs

src/tools/wasm-link.cc
=> wasm-link: Remove Context, use C++ class instead.

src/binary-reader-ir.cc
This matches the behavior in wast-parser.cc, and is clearer.
=> Use AppendField in binary-reader-ir.cc

src/binary-reader-objdump.cc, src/binary-reader.cc, src/binary-writer.cc, src/common.cc, src/common.h, test/dump/relocations.txt, test/link/export.txt, test/link/function_calls.txt, test/link/function_calls_incremental.txt, test/link/globals.txt, test/link/incremental.txt, test/link/interp.txt, test/link/large_code_section.txt, test/link/names.txt, test/link/table.txt
See https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md#relocation-sections
=> Update relocation names to match tool convention doc

src/writer.cc
=> Fix file descriptor leak in writer.cc

src/binary-reader.cc, src/feature.def, src/interpreter.cc, src/opcode.cc, src/opcode.def, src/prebuilt/wast-lexer-gen.cc, src/wast-lexer.cc, src/wast-parser.cc, test/dump/unary-extend.txt, test/help/wasm-interp.txt, test/help/wasm-objdump.txt, test/help/wasm2wast.txt, test/help/wast-desugar.txt, test/help/wast2wasm.txt, test/interp/unary-extend.txt, test/parse/expr/unary-extend-disabled.txt, test/parse/expr/unary-extend.txt, test/run-interp.py, test/run-objdump.py
Also add thread feature (via `--enable-threads`).
=> Add i{32,64}.extend{8,16,32}_s operators

CMakeLists.txt, src/binary-writer.cc, src/binary-writer.h, src/common.h, src/interpreter.cc, src/leb128.cc, src/leb128.h, src/tools/wasm-link.cc
Also rename some of the functions.
=> Move LEB128 stuff to its own file

src/binary-reader-interpreter.cc, src/binary-reader-ir.cc, src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-objdump.cc, src/wat-writer.cc
Most classes already did this, but there were some that needed to be
fixed.
=> Append trailing underscore on private member names

src/feature.cc, src/feature.h
Make it possible for a consumer other than a console application to set features.
=> Add an interface to enable features

src/wast-parser.cc, test/parse/module/bad-module-no-close.txt, test/regress/regress-13.txt
=> Fix assertion in wat2wasm for `(module (test))`

src/binary-reader.cc
* Remove IN_SIZE macro and use a template instead
* Change C comments to C++ comments
=> Some cleanup in binary-reader.cc

CMakeLists.txt, README.md, src/tools/wat-desugar.cc, test/README.md, test/desugar/basic.txt, test/desugar/fold-catch.txt, test/desugar/fold-export-throw.txt, test/desugar/fold-try-as-argument.txt, test/desugar/fold-try.txt, test/desugar/implicit-func-type.txt, test/desugar/try-exports.txt, test/desugar/try-import.txt, test/desugar/try.txt, test/find_exe.py, test/help/wat-desugar.txt, test/run-tests.py
=> Rename `wast-desugar` to `wat-desugar`.

src/tools/spectest-interp.cc
* `RunAction` now returns an `ExecResult`
* Remove handling of `passed_` and `total_` from command handlers
* Simplify command handlers to have similar structure -- try to error
out early and fall through to success at the bottom.
=> Small cleanup of `CommandRunner`

src/binary-writer-spec.cc, test/spec/address.txt, test/spec/align.txt, test/spec/block.txt, test/spec/call_indirect.txt, test/spec/const.txt, test/spec/float_literals.txt, test/spec/func.txt, test/spec/if.txt, test/spec/imports.txt, test/spec/int_literals.txt, test/spec/loop.txt, test/spec/memory.txt, test/spec/token.txt, test/spec/type.txt, test/spec/utf8-invalid-encoding.txt
=> Use `.wat` extension for wast2json-generated files

test/run-tests.py
This change means that we alwasys parse one of the TOOLS for a given TestInfo.  Previously we had some hardcoded defaults which duplicated the TOOLS entries
=> Remove some duplication in run-tests.py

src/binary-writer.cc, test/dump/relocations.txt
Fixes https://github.com/WebAssembly/wabt/issues/681
=> Always create linking section with write relocatable wasm files

src/tools/spectest-interp.cc, src/tools/wasm-validate.cc, src/tools/wasm2wat.cc, src/tools/wast2json.cc, src/tools/wat2wasm.cc, src/validator.cc, src/validator.h, test/dump/mutable-global.txt, test/parse/export-mutable-global.txt, test/parse/module/import-mutable-global.txt
This matches the threads proposal.
=> Import/export mutable globals w/ threads enabled

src/tools/wasm-link.cc, test/help/wasm-link.txt, test/link/data.txt, test/link/export.txt, test/link/function_calls.txt, test/link/function_calls_incremental.txt, test/link/globals.txt, test/link/incremental.txt, test/link/interp.txt, test/link/large_code_section.txt, test/link/names.txt, test/link/names_import_only.txt, test/link/names_import_only_module_env.txt, test/link/table.txt
=> Add deprecation warning to wasm-link

src/feature.def, src/opcode.cc, src/validator.cc, test/dump/mutable-global.txt, test/dump/unary-extend.txt, test/help/spectest-interp.txt, test/help/wasm-interp.txt, test/help/wasm-validate.txt, test/help/wasm2wat.txt, test/help/wast2json.txt, test/help/wat-desugar.txt, test/help/wat2wasm.txt, test/interp/logging-all-opcodes.txt, test/interp/tracing-all-opcodes.txt, test/interp/unary-extend.txt, test/parse/export-mutable-global.txt, test/parse/expr/unary-extend.txt, test/parse/module/import-mutable-global.txt, test/run-interp.py, test/run-objdump.py, test/run-roundtrip.py
Also reorder the flags so they are alphabetical order.
=> Add feature flags for sign-ext., mutable-globals

test/run-tests.py
Also fix bug when printing the last command that failed.
=> [test] `RUN` command has optional args

src/wast-lexer.cc
=> Fix segfault in wat2wasm when loading invalid file

src/validator.cc
This will make it easier to use a non-recursive visiting strategy that
can be reused elsewhere.
=> Use ExprVisitor in Validator

src/expr-visitor.cc, src/expr-visitor.h
This will help with wasm modules that have very deeply nested blocks.
See issue #752.
=> Rewrite ExprVisitor to be non-recursive

src/binary-reader.cc, src/interp.cc, src/opcode.cc, src/opcode.def, src/prebuilt/wast-lexer-gen.cc, src/wast-lexer.cc, test/interp/simd-unary.txt
Including:
i32x4.trunc_s/f32x4:sat
i32x4.trunc_u/f32x4:sat
i64x2.trunc_s/f64x2:sat
i64x2.trunc_u/f64x2:sat
=> SIMD Floating point to integer with saturation implementation.

src/binary-reader-objdump.cc, test/dump/debug-names.txt, test/dump/getlocal-param.txt, test/dump/getlocal.txt, test/dump/locals.txt, test/dump/setlocal-param.txt, test/dump/setlocal.txt, test/dump/tee_local.txt
=> Print locals in objdump disassembly

src/opcode.cc, src/opcode.h, src/type-checker.cc, src/type-checker.h, test/typecheck/bad-simd-lane.txt
=> Small cleanup to simd extract/replace lane

src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-nop.h, src/binary-reader-objdump.cc, src/binary-reader.cc, src/binary-reader.h, src/binary-writer.cc, test/binary/linking-section.txt, test/binary/relocs.txt, test/dump/relocations.txt
See https://github.com/WebAssembly/tool-conventions/issues/52
=> Refer to target section by index in relocation section

src/binary-reader-objdump.cc, test/dump/debug-import-names.txt, test/dump/debug-names.txt, test/dump/module-name.txt
See comment here: https://github.com/WebAssembly/wabt/pull/831#issuecomment-387491592
=> Display module name in wasm-objdump

README.md, src/prebuilt/wasm2c.include.h, src/wasm2c.h.tmpl, wasm2c.md
Also remove `WASM_RT_DEFINE_EXTERNAL`, as it doesn't seem to be used.
=> Add some documentation for wasm2c

src/tools/spectest-interp.cc, src/tools/wasm-interp.cc
=> Fix GCC 8 error due to `-Werror=class-memaccess`.

src/config.h.in
=> Relax the check for alloca

src/binary-reader-logging.cc
=> Fix typo in BinaryReaderLogging::OnFunctionSymbol

wasm2c/wasm-rt-impl.c
=> [wasm2c] Fix bad realloc in wasm-rt-impl

CMakeLists.txt
This is useful for projects importing wabt only for libwabt.
=> Add BUILD_TOOLS option to CMake

README.md, src/option-parser.cc, src/tools/wasm-opcodecnt.cc, test/README.md, test/help/spectest-interp.txt, test/help/wasm-interp.txt, test/help/wasm-objdump.txt, test/help/wasm-opcodecnt.txt, test/help/wasm-validate.txt, test/help/wasm2wat.txt, test/help/wast2json.txt, test/help/wat-desugar.txt, test/help/wat2wasm.txt
=> Remove short option for --help 

man/wasm-interp.1, man/wasm-objdump.1, man/wasm2c.1, man/wasm2wat.1, man/wat-desugar.1, man/wat2wasm.1
=> add minimal manpages (mdoc-formatted)

CMakeLists.txt
=>  Add manpages to the `make install` target

CMakeLists.txt, src/tools/wasm-strip.cc, test/find_exe.py, test/run-tests.py, test/strip/basic.txt, test/strip/names.txt, test/strip/no-custom-sections.txt
There's a lot more that this tool could do, but even this is helpful for
now.
Fixes issue #631.
=> Add wasm-strip tool to strip custom sections

README.md
=> Update README.md demo links

README.md
=> Use gh-pages instead of rawgit for demo

.gitignore, src/apply-names.cc, src/binary-reader-ir.cc, src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-nop.h, src/binary-reader.cc, src/binary-reader.h, src/binary-writer.cc, src/interp/binary-reader-interp.cc, src/interp/interp.cc, src/ir.h, src/opcode.cc, src/resolve-names.cc, src/type-checker.cc, src/type-checker.h, src/validator.cc, src/wast-parser.cc, test/interp/return-call-import.txt, test/interp/return-call-indirect-import.txt, test/interp/return-call-indirect.txt, test/interp/return-call.txt
return_call
return_call_indirect
with some simple tests thereof.
=> Implemented tail call instructions:

src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-nop.h, src/binary-reader-objdump.cc, src/binary-reader.cc, src/binary-reader.h, src/binary.h, test/binary/dylink-section.txt
See: https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md
=> Add support for dylink section

test/spec/mutable-global/globals.txt, test/spec/mutable-global/linking.txt, test/spec/nontrapping-float-to-int-conversions/conversions.txt, test/spec/sign-extension-ops/i32.txt, test/spec/sign-extension-ops/i64.txt, test/update-spec-tests.py
These tests are already included in third_party/testsuite. The
`update-spec-tests.py` script just needs to be updated to include them.
=> Run more proposal spec tests

src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-nop.h, src/binary-reader-objdump.cc, src/binary-reader.cc, src/binary-reader.h, test/binary/dylink-section.txt
This field was recently added:
https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md
=> Add needed_dynlibs to dylink section

src/common.cc, test/dump/bad-directory.txt
=> Fix segfault when passing wasm-objdump a directory

README.md
=> Clarify build instructions in README.md

src/binary-reader.cc, src/binary-writer.cc, test/dump/bulk-memory.txt
This commit updates wabt wrt to two recent PRs:
* WebAssembly/bulk-memory-operations#43
* WebAssembly/bulk-memory-operations#45
=> Update bulk memory instruction binary encodings

src/binary-reader-objdump.cc, src/common.cc, src/common.h
Also fixed 2 asserts that could trigger on user data.
=> [wasm-objdump] Implemented R_WASM_EVENT_INDEX_LEB reloc type.

src/binary-reader-objdump.cc
The functions BinaryReaderObjdumpBase::GetSymbolName calls may
return null, so it should deal with that case.
=> [wabt-objdump] Refactored some functions to use string_view

src/binary-writer-spec.cc, src/stream.h, test/run-spec-wasm2c.py
=> Rely on UTF-8 encoding in JSON strings

CMakeLists.txt, src/option-parser.cc, src/test-option-parser.cc
Also fix the bug with `--long=value` (see #1095).
=> Add tests for option-parser

CMakeLists.txt
=> Add USE_SYSTEM_GTEST option, to use system copy of GTest

src/wast-lexer.cc, test/regress/regress-31.txt
=> Fix crash when newlines are in string tokens

src/common.h, test/typecheck/if-anyref.txt
Fixes https://github.com/WebAssembly/wabt/issues/1124.
=> Fix parsing of anyref-valued "if" expressions

scripts/fuzz-wasm2wat.sh, src/binary-reader.cc
Also update the fuzz script to enable various features, so they get fuzz
testing too.
=> Fix some fuzz bugs in wasm2wat

scripts/fuzz-wat2wasm.sh, src/wast-lexer.cc, src/wast-parser.cc, test/parse/bad-annotations.txt, test/parse/bad-string-eof.txt, test/parse/bad-string-escape.txt, test/parse/bad-string-hex-escape.txt, test/regress/regress-31.txt, test/regress/regress-32.txt, test/regress/regress-33.txt
* More bugs w/ bad strings (newlines and bad escapes)
* Incorrect hex-float exponent
* Update fuzz-wat2wasm.sh to enable features
=> Fix fuzzing bugs in wat2wasm

src/feature.cc, test/help/spectest-interp.txt, test/help/wasm-interp.txt, test/help/wasm-validate.txt, test/help/wasm2wat.txt, test/help/wast2json.txt, test/help/wat-desugar.txt, test/help/wat2wasm.txt, test/parse/all-features.txt
This adds `--enable-all` option that enables all existing features.
=> Add --enable-all option

README.md
=> Update supported features table

wasm2c/wasm-rt-impl.c
=> [wasm2c] Fix realloc check in wasm_rt_grow_memory

src/decompiler.cc
Previously, this was just the last value(s) of a block.
=> wasm-decompile: added explicit return statements and types.

src/decompiler.cc
br becomes break or continue, and br_if the same, but prefixed
by an if(..).
These refer to the enclosing loop/block by generated label name,
this syntax may change.
We may later want to replace these by while/do-while/switch and
other special cases, but for now this is decently readable.
Also added ; to statements.
=> wasm-decompile: Implement br/br_if

src/decompiler.cc
global myvar:type = initializer;  // At file scope.
var myvar = initializer;  // Local, in a function.
Also takes care of lifting these out to function level if these
happen inside an exp, or make use of uninitialized local.
=> wasm-decompile: Declaring local and global vars.

src/option-parser.cc, src/option-parser.h
Also, inline two trivial methods.
=> Fix unused lambda capture warning

src/binary-writer.cc, test/dump/table-multi.txt
=> Add initial support for multi-table to wat2wasm and wasm-objdump

src/resolve-names.cc, src/wast-parser.cc, test/parse/expr/bulk-memory-named.txt, test/parse/module/bad-elem-redefinition.txt
=> Check for redefinitions of elem segments

CMakeLists.txt, src/decompiler-ast.inl, src/decompiler.cc, test/decompile/basic.txt, test/find_exe.py, test/run-tests.py
These are pretty minimal, more will be added as part of feature-PRs.
=> wasm-decompile: Added initial tests.

src/decompiler-ast.h, src/decompiler.cc
This generally can't work, since the local in question may still be
used after the block, but in this case was also causing some bad
corruption of the exp_stack (thanks, vector::emplace, for not
asserting on values out of range).
Also refactored affected code to be better debuggable.
=> wasm-decompile: fixed PreDecl being added to nested blocks.

.gitattributes, .github/workflows/build.yml, test/run-spec-wasm2c.py, test/run-tests.py
=> run-tests.py works properly with python3

src/apply-names.cc, test/roundtrip/generate-start-name.txt
=> Apply start function name in wasm2wat

.travis.yml, scripts/travis-before-install.sh
We only need sudo for the i686 builder that needs extra packages.
Also, name each element of the matrix
Also, remove a bunch of unuser settings from the emcripten build.
=>  [travis] Limit use of sudo

CMakeLists.txt
=> Include `CMakeParseArguments`

.appveyor.yml
See documentation here:
https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
=> [appveyor] Add script to allow RDP into CI bots

test/gen-spec-wast.py
The one difference is that all `(module...)` are converted to
`(module binary)`.
=> Add Script to generate .wast from .json

src/wat-writer.cc, test/roundtrip/simd.txt
=> Fix whitespace formatting of SIMD ops

CMakeLists.txt, src/interp/interp-wasi.cc, src/interp/wasi_api.def, src/tools/wasm-interp.cc, test/help/wasm-interp.txt
This is almost enough to pass all the tiny tests in the wasi-sdk
repo.
=> Implement more WASI APIs

src/binary-reader.cc, test/binary/bad-alignment.txt
=> Check for malformed alignment

src/binary-reader-ir.cc, src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-nop.h, src/binary-reader.cc, src/binary-reader.h, src/binary-writer.cc, src/interp/binary-reader-interp.cc, src/ir.h, src/shared-validator.cc, src/shared-validator.h, src/type-checker.cc, src/type-checker.h, src/validator.cc, src/wast-parser.cc, src/wat-writer.cc, test/decompile/basic.txt, test/dump/reference-types.txt, test/interp/reference-types.txt, test/parse/expr/reference-types.txt, test/spec/binary.txt, test/spec/bulk-memory-operations/binary.txt, test/spec/reference-types/binary.txt, test/spec/reference-types/br_table.txt, test/spec/reference-types/ref_is_null.txt, test/spec/reference-types/unreached-invalid.txt
See https://github.com/WebAssembly/reference-types/issues/99.
=> Remove ref.is_null type parameter

src/binary-reader-ir.cc, test/binary/bad-linking-data-segment-index.txt, test/binary/bad-linking-event-index.txt, test/binary/bad-linking-function-index.txt, test/binary/bad-linking-global-index.txt
=> Fix linking section symbol name bugs

CMakeLists.txt
This speeds up builds of WABT significantly
=> Enable multi-core build on Windows

src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-nop.h, src/binary-reader-objdump.cc, src/binary-reader-objdump.h, src/binary-reader.cc, src/binary-reader.h, test/binary/bad-export-out-of-range.txt
=> Fix integer overflow in objdump name tracking

src/interp/interp-inl.h, src/test-interp.cc
=> Fix RefPtr::empty()

src/binary-writer.cc, test/dump/elem-mvp-compat.txt, test/dump/relocs-section-target.txt
=> Fix reloc section references when --enable-bulk-memory

src/binary-writer.cc, test/dump/relocations-long-func-bodies.txt, test/dump/relocations-long-func-section.txt
=> wat2wasm: fix relocation offsets

src/binary-reader-logging.cc, src/binary-reader-logging.h, src/binary-reader-nop.h, src/binary-reader-objdump.cc, src/binary-reader.cc, src/binary-reader.h, src/binary-writer.cc, src/binary.cc, src/binary.h, test/dump/debug-import-names.txt, test/dump/debug-names.txt, test/dump/extended-names.txt
See: https://github.com/WebAssembly/extended-name-section
Although this is only a phase 1 proposal its seems pretty
straight forward, and is already being implemented in
binaryen.
=> Add initial support for extended names sections

CMakeLists.txt
Also include header files needed for compilation
=> wasm2c: build library wasm-rt-impl

src/binary-reader-objdump.cc, test/dump/extended-names.txt, test/dump/symbol-tables-all-features.txt, test/dump/symbol-tables.txt
This should really have been part of #1554
=> wasm-objdump: Honor extended names section

wasm2c/wasm-rt-impl.c
We really should enable Werror on CI (See #1185)
=> Fix warning. NFC.

docs/doc/wasm-decompile.1.html, scripts/generate-html-docs.sh
The script regenerates html from all man pages. I ran it once, and only
checked in wasm-decompile.1.html.
=> Add script to generate html from man, and generate wasm-decompile html

docs/demo/wasm2wat/demo.js
add two feature :
1. drag file to editor now will trigger reparse the wasm to wat
2. cache the `features` user checked, so user no need to reselect the features every open.
=> feat: 🎸 drag file to editor trigger recompile

.github/workflows/build_source_release.yml
closes #1315
result can be seen here
https://github.com/rofl0r/wabt/releases/tag/9.9.99d
=> CI: add github action to build source release tarball

CMakeLists.txt
New release.   Partly to test creation of source archives. See #1615
=> Version 1.0.21

src/binary-reader.cc, src/interp/interp.cc, src/interp/istream.cc, src/lexer-keywords.txt, src/opcode.def, src/prebuilt/lexer-keywords.cc, test/spec/simd/simd_i32x4_trunc_sat_f32x4.txt, test/spec/simd/simd_i32x4_trunc_sat_f64x2.txt
Rebase simd_i32x4_trunc_sat_f64x2.txt and
simd_i32x4_trunc_sat_f32x4.txt.
=> [simd] Implement i32x4.trunc_sat_f64x2_[su]_zero

src/binary-reader.cc, src/interp/interp.cc, src/interp/istream.cc, src/lexer-keywords.txt, src/opcode.def, src/prebuilt/lexer-keywords.cc, test/spec/simd/simd_i64x2_arith2.txt
Rebase and unskip simd_i64x2_arith2.txt.
=> [simd] Implement i64x2.abs

src/binary-reader.cc, src/interp/interp-math.h, src/interp/interp.cc, src/interp/istream.cc, src/lexer-keywords.txt, src/opcode.def, src/prebuilt/lexer-keywords.cc, test/spec/simd/simd_i16x8_q15mulr_sat_s.txt
Rebase and unskip simd_i16x8_q15mulr_sat_s.
=> [simd] Implement q15mulrsat_s

src/binary-reader.cc, src/interp/interp.cc, src/interp/interp.h, src/interp/istream.cc, src/lexer-keywords.txt, src/opcode.def, src/prebuilt/lexer-keywords.cc, test/spec/simd/simd_i32x4_dot_i16x8.txt
Rebase and unskip simd_i32x4_dot_i16x8.
=> [simd] Implement i32x4.dot_i16x8_s

CMakeLists.txt
- thirdparty/testsuite updates
- WASI compilation fixes
- 32-bit compile fixes
- SIMD updates
=> Version 1.0.22

CMakeLists.txt
- add _free to exports for building libwabtjs
=> Version 1.0.23

src/binary-reader.cc, src/common.h, src/interp/binary-reader-interp.cc, src/interp/interp.cc, src/shared-validator.cc, src/type-checker.cc, src/wast-parser.cc, test/interp/load64.txt, test/regress/regress-27.txt, test/spec/data.txt
Note: also updates `testsuite`.
=> Memory64: support 64-bit data init-expr

src/decompiler-ast.h
See https://github.com/WebAssembly/wabt/issues/1565
And https://github.com/WebAssembly/wabt/issues/1665
This could be done better, but for now is sufficient.
=> [wasm-decompile] Fix repeated pre-declarations

src/common.h, test/binary/bad-reloc-type.txt
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30792
=> Fix asan error in reading of bad relocation type

src/tools/wasm-strip.cc
=> wasm-strip: enable all features during wasm-strip

test/run-tests.py
=> Improve path canonicalization when running test code. NFC

src/base-types.h, src/string-format.h
This was necessary for me to build and seems to be the correct thing to do. If it's incorrect and my build is somehow misconfigured please let me know! :)
=> add includes for used system headers

src/binary-writer.cc, test/dump/debug-names.txt
=> Don't include empty names for locals

CMakeLists.txt
=> Move to C++17

src/binary-reader-opcnt.cc, src/c-writer.cc, src/ir.cc, src/tools/wasm-opcodecnt.cc, src/wast-parser.cc
=> Use C++17 pair de-structuring for loops

src/tools/wasm2c.cc
=> Add missing wasm2c feature flags

src/interp/interp-inl.h, src/interp/interp.cc, src/interp/interp.h
This patch is a follow-up for #1835. It can be landed independently or merged with the other PR.
=> Rework free list to use less memory.

wasm2c/.gitignore, wasm2c/examples/fac/fac.c, wasm2c/examples/fac/fac.h
Do we really want to have this output checked in like this?
If so, we should probably automate its update ot at least add
a check to avoid it getting out-of-date.
=> Update wasm2c example output. NFC

.github/workflows/build.yml, test/run-spec-wasm2c.py
=> Build and run wasm2c-generated code under sanitizers in CI. NFC

Makefile, wasm2c/examples/fac/Makefile, wasm2c/examples/rot13/Makefile
=> Improve wasm2c example update process. NFC

CMakeLists.txt
See https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html
=> Use CMAKE_CXX_STANDARD and bump cmake minimum version to 3.1

src/c-writer.cc, test/run-spec-wasm2c.py, wasm2c/README.md, wasm2c/examples/fac/fac.c, wasm2c/examples/fac/fac.h, wasm2c/examples/fac/main.c, wasm2c/examples/rot13/main.c, wasm2c/wasm-rt-impl.c, wasm2c/wasm-rt.h
=> wasm2c: export free() function to free module state

src/binary-reader.cc
This is relevant so that when we are dumping a module that contains
unknown sections that the current wabt tooling does not understand, we
still dump all the sections it understands, skipping (and printing an
error) about the unknown sections.
Before this change, we would print partial information, stopping at
the unknown section, without printing the rest of the sections that
wabt could potentially be able to understand.
Motivation: this happened when inspecting with `wasm-objdump` a module produced by [wasmlink](https://github.com/bytecodealliance/wit-bindgen/tree/main/crates/wasmlink).
Output when having produced a module with an unknown section with current version:
```
$ wasm-objdump -x linked.wasm
linked.wasm:	file format wasm 0x1
000020b: error: invalid section code: 14
Section …
```
=> Continue dumping sections even when one is unknown

README.md
Domain name had expired. Closes #1716
=> README.md: update MinGW URL

src/binary-reader-ir.cc, test/roundtrip/debug-names.txt
=> BinaryReaderIR: set name of type if given in name section

CMakeLists.txt
@sbc100 -- when you're ready to cut a new version, merge this PR :slightly_smiling_face:
=> Bump version to 1.0.30

src/c-writer.cc
Also convert a constant from char[] to constexpr std::string_view
Test: builds
=> Remove some consts for std::string_view

src/wast-parser.cc, test/spec/tail-call/return_call.txt, test/spec/tail-call/return_call_indirect.txt, test/update-spec-tests.py
=> Add tail-call spec tests and fix related parser issue

CMakeLists.txt
=> Version 1.0.31

wasm2c/examples/fac/fac.c
=> Update wasm2c fac.c example

docs/demo/wat2wasm/demo.js
Sorry, fixed now. Didn't balance my braces :grimacing:
Thats what you get for editing in the Github editor, opened this file in vscode with the fix now, and no problems reported
=> Typo in previous PR causing unbalanced braces

src/c-writer.cc
Wasm modules may have more static data than the initial memory of the memory provided (this happens particularly when using externally provided memory). Today, wasm2c simply traps if this is the case. With this change, wasm2c's `load_data()` calls `wasm_rt_grow_memory()` to handle this case.
=> wasm2c: expose the initial and max size required from imported memory

test/run-spec-wasm2c.py, test/run-tests.py
I mistakenly broke the wasm2c test runner in #2086.  I guess we need tests for our test runner..
=> Fix wasm2c test runner

CMakeLists.txt, include/wabt/interp/interp-math.h, src/config.h.in
=> Add ARM64 windows compatibility (#2139)

src/binary-reader-ir.cc
Fixes #2151.
Summary: oss-fuzz has discovered that if a module includes an extremely deep series of nested blocks (e.g. a huge number of nested if instructions, each in the parent's "true" block), that wasm2wat will crash when trying to run the Module destructor, just because each Block recursively runs the destructor of its child IfExpr which runs the destructor of its child Block, etc., and eventually all those nested stack frames cause a stack overflow. (This is [oss-fuzz #53958](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53958).)
This PR fixes the problem the dumb/easy way, by making BinaryReaderIR enforce a cap on nesting depth that's likely to be safe given a reasonable stack size. I couldn't easily find what the major Wasm engines do here, but 1,024 seems like a …
=> BinaryReaderIR: limit nesting depth to avoid stack overflow

src/interp/interp-wasm-c-api.cc
Updates wasm-c-api submodule
Fixes #1600
=> Update wasm-c-api support to current API

.github/workflows/build.yml
Sending this PR but not sure if there's any specific reason we target `ubuntu-22.04` for those tests.
=> use ubuntu-latest for sanitize and wasm2c-memchecked

src/binary-reader-ir.cc
Impose implementation-defined limits (matching V8 and other engines) for the number of params, results, and locals a function can have if it wants to pass through the BinaryReaderIR.
V8's limits are here: https://chromium.googlesource.com/v8/v8/+/refs/heads/main/src/wasm/wasm-limits.h
Fixes #2180
=> BinaryReaderIR: Limit number of function params, results, and locals

src/prebuilt/wasm2c_source_includes.cc, src/template/wasm2c.includes.c, test/wasm2c/add.txt, test/wasm2c/check-imports.txt, test/wasm2c/export-names.txt, test/wasm2c/hello.txt, test/wasm2c/minimal.txt
=> Replace alloca.h with stdlib.h on FreeBSD

src/c-writer.cc
This is a prelude to fixing a wasm2c exception-handling issue reported by @SoniEx2 on the Wasm Discord (and related to #2203).
=> c-writer.cc: cleanup name lookups to happen consistently in one place

test/run-spec-wasm2c.py
@sbc100 @keithw Checking if this is a copy-paste typo?
=> wasm2c: Fix typo in testing harness

include/wabt/common.h, include/wabt/interp/interp-inl.h, src/resolve-names.cc, src/wast-lexer.cc
Minor changes to ensure wabt compiles under the C++ 20 standard
=> C++20 compatibility fixes

src/c-writer.cc
Split out from #2271 per https://github.com/WebAssembly/wabt/pull/2271#discussion_r1278609278
=> c-writer.cc: eliminate redundant import_syms_ SymbolSet (NFC)

src/c-writer.cc
Split out from #2272 (tail calls).
This PR consolidates the machinery to spill and unspill groups of params and results to/from a struct, and uses this to handle tags and multi-value results in the same way. In the tail-call PR, we'll use the same machinery to pack/unpack the params and results from a tail-callee function.
This PR also pulls out a function to unwind the try-catch stack to a given label. We currently use this in one place (writing a GotoLabel). In the tail-call PR, we'll also use it in the return_call and return_call_indirect instructions.
=> wasm2c: consolidate pack/unpack of tags, multi-value results (NFC)

src/c-writer.cc
Split out from #2272 per https://github.com/WebAssembly/wabt/pull/2272#discussion_r1326166696. We had been using "Multivalue" for all the typevector structs (both true "multi-value" result types, but also tag types, and then #2272 had used this term to refer to structs that hold the params to a tail-called function).
This PR makes it so we only use "multivalue" to refer to a multi-value result type, not a tag type.
It also deduplicates the typevector struct declarations in the output.
=> c-writer.cc: clean up some handling of typevector structs (NFC)

CMakeLists.txt, test/run-tests.py
=> Clean up WABT_BIG_ENDIAN handling in tests

test/harness-windows/wasm2c/simd_formatting.txt, test/harness/wasm2c/simd_formatting.txt, test/run-spec-wasm2c.py, test/run-tests.py, test/spec-wasm2c-prefix.c, test/utils.py
This was segfaulting/crashing/other issues. Split from #2321
=> wasm2c: Fix test harness UB with SIMD

src/prebuilt/wasm2c_atomicops_source_declarations.cc, src/prebuilt/wasm2c_simd_source_declarations.cc, src/prebuilt/wasm2c_source_declarations.cc, src/template/wasm2c.declarations.c, src/template/wasm2c_atomicops.declarations.c, src/template/wasm2c_simd.declarations.c, test/wasm2c/add.txt, test/wasm2c/check-imports.txt, test/wasm2c/export-names.txt, test/wasm2c/hello.txt, test/wasm2c/minimal.txt, test/wasm2c/tail-calls.txt
This doesn't fix much on BE (fixes atomics, doesn't fix SIMD) but it cleans things up and makes it more maintainable.
=> wasm2c: Improve address abstraction for BE support

wasm2c/examples/fac/fac.c, wasm2c/examples/rot13/rot13.wat
These had slightly bitrotted with some recent changes to the text parser and wasm2c template.
=> Update wasm2c examples

src/c-writer.cc, src/prebuilt/wasm2c_simd_source_declarations.cc, src/template/wasm2c_simd.declarations.c, test/harness/wasm2c/simd_formatting.txt, test/run-spec-wasm2c.py, test/spec-wasm2c-prefix.c
~~This PR does not include the necessary test harness changes, we'll add those in another PR along with some regression tests too.~~
=> wasm2c: Implement big-endian SIMD

.github/workflows/build.yml, src/prebuilt/wasm2c_simd_source_declarations.cc, src/template/wasm2c_simd.declarations.c
What it says on the tin.
Closes #2366 and closes #2373
=> Apple Silicon support 

src/tools/wasm2c.cc, test/regress/issue-2423-wasm2c-no-extension.txt
=> wasm2c: Use wabt::StripExtension

src/wast-parser.cc, test/parse/module/bad-element-followed-by-illegal-expression.txt
=> Fix parsing of malformed element section in text format

src/lexer-keywords.txt, src/prebuilt/lexer-keywords.cc
(`TokenType::Exn` already exists for some reason)
=> lexer-keywords.txt: Recognize exn and exnref

src/prebuilt/wasm2c_source_declarations.cc, src/template/wasm2c.declarations.c, test/wasm2c/add.txt, test/wasm2c/check-imports.txt, test/wasm2c/export-names.txt, test/wasm2c/hello.txt, test/wasm2c/minimal.txt, test/wasm2c/tail-calls.txt, wasm2c/examples/fac/fac.c, wasm2c/wasm-rt-impl.c, wasm2c/wasm-rt.h
Misc cleanups
- Addressing the misc wasm2c cleanups referred here https://github.com/WebAssembly/wabt/pull/2602#discussion_r2124635801
- Re-running clang-format on the source
=> wasm2c: format source and regenerate tests and examples

src/binary-reader-ir.cc, src/binary-reader.cc, test/parse/branch-hints.txt
=> gh-2616 Fix wrong validation of code metadata function index
